// Dubai commercial — full underwriting (office, retail, warehouse).
//
// Commercial differs from Dubai residential in four ways that change the
// arithmetic, not just the labels:
//
//   1. Rent is quoted AED per sqft per year, not as an annual lump sum, and
//      leases carry contractual fixed escalations. The RERA residential
//      increase caps of Decree 43/2013 do not bind a commercial renewal the
//      same way — the contract governs.
//   2. A commercial lease is a standard-rated supply. The landlord charges 5%
//      VAT and RECOVERS input VAT, so the irrecoverable-VAT drag that dominates
//      residential OpEx disappears. The 5% VAT on the purchase price of a
//      commercial building is likewise recoverable — a working-capital event,
//      not a cost.
//   3. Service charge is frequently recoverable from the tenant. Whether it is
//      recoverable is the single biggest swing factor in a Dubai office deal.
//   4. Income is concentrated. WALT, the covenant strength of the largest
//      tenant, and the void and incentive cost at expiry drive the return far
//      more than the going-in yield does.

import type { ModelDefinition } from "../../lib/engine/types.ts";

export const dubaiCommercialFull: ModelDefinition = {
  key: "dubai-commercial-full",
  name: "Dubai Commercial — Full Underwriting",
  description:
    "Full underwriting for a Dubai office, retail or warehouse asset. AED/sqft rent with contractual escalations, WALT-driven reversion with void and incentive costs, recoverable or non-recoverable service charge, recoverable VAT, full DLD acquisition stack, amortising debt, exit on cap rate or price per sqft, levered IRR and equity multiple.",
  // Market KEY, not a display label — matched exactly elsewhere in the system.
  market: "AE",
  currency: "AED",
  depth: "full",
  assetType: "commercial",
  schemaVersion: 1,

  inputs: [
    // ---------------------------------------------------------- property --
    {
      key: "price",
      label: "Purchase price",
      group: "Property",
      type: "currency",
      unit: "AED",
      default: 36000000,
      min: 100000,
      required: true,
      extract: true,
      source: "om",
      help: "Agreed purchase price excluding VAT. A commercial building sale is a standard-rated supply, so 5% VAT is payable on top and is recoverable by a VAT-registered buyer — shown separately below.",
    },
    {
      key: "nla_sqft",
      label: "Net leasable area",
      group: "Property",
      type: "number",
      unit: "sqft",
      default: 22000,
      min: 200,
      required: true,
      extract: true,
      source: "rent_roll",
      derivedFrom: "size_sqft",
      help: "Net leasable area in square feet, summed across the rent roll when one is uploaded. Check whether the OM quotes NLA or gross BUA — the difference on a Dubai office floorplate is routinely 15-20% and it moves the price per sqft accordingly.",
    },
    {
      key: "asset_subtype",
      label: "Asset subtype",
      group: "Property",
      type: "select",
      default: "office",
      options: [
        { value: "office", label: "Office" },
        { value: "retail", label: "Retail" },
        { value: "warehouse", label: "Warehouse / industrial" },
      ],
      help: "Sets the service-charge sanity band: office 18-35, retail 20-40, warehouse 2-6 AED/sqft/yr.",
    },
    {
      key: "community",
      label: "Location",
      group: "Property",
      type: "text",
      extract: true,
      source: "om",
      help: "Free zone or district, e.g. DIFC, Business Bay, JLT, DMCC, Dubai Investments Park, Al Quoz. Free zone location determines who may occupy and materially narrows or widens the tenant pool.",
    },
    {
      key: "building_age_years",
      label: "Building age",
      group: "Property",
      type: "integer",
      unit: "years",
      default: 10,
      min: 0,
      max: 80,
      help: "Years since handover. Past fifteen years, chiller plant, lifts, BMS and facade start arriving as capital events funded by the OA reserve or a special levy.",
    },
    {
      key: "tenure",
      label: "Tenure",
      group: "Property",
      type: "select",
      default: "freehold",
      options: [
        { value: "freehold", label: "Freehold" },
        { value: "leasehold", label: "Leasehold" },
        { value: "usufruct", label: "Usufruct" },
        { value: "musataha", label: "Musataha" },
      ],
      help: "Much Dubai commercial stock in free zones is held on usufruct or musataha from the master developer rather than freehold. Musataha carries a right to build and typically runs to 50 years; both amortise to zero.",
    },
    {
      key: "tenure_years_remaining",
      label: "Tenure years remaining",
      group: "Property",
      type: "integer",
      unit: "years",
      default: 99,
      min: 0,
      max: 999,
      help: "Unexpired term. Below about 30 years the institutional buyer pool and the lending market both thin out sharply.",
    },
    {
      key: "community_price_psf_low",
      label: "Market price/sqft — low",
      group: "Property",
      type: "number",
      unit: "AED/sqft",
      help: "Bottom of the recent transacted range for comparable stock in this submarket. Leave blank if unknown.",
    },
    {
      key: "community_price_psf_high",
      label: "Market price/sqft — high",
      group: "Property",
      type: "number",
      unit: "AED/sqft",
      help: "Top of the recent transacted range for comparable stock in this submarket.",
    },

    // ------------------------------------------------------------ income --
    {
      key: "rent_psf",
      label: "Passing rent",
      group: "Income",
      type: "number",
      unit: "AED/sqft/yr",
      default: 155,
      min: 0,
      required: true,
      extract: true,
      source: "rent_roll",
      help: "Contracted rent per sqft per year across the let area, the way Dubai commercial is quoted. Exclude service charge and VAT.",
    },
    {
      key: "occupancy",
      label: "Physical occupancy",
      group: "Income",
      type: "percent",
      default: 0.95,
      min: 0,
      max: 1,
      extract: true,
      source: "rent_roll",
      // Area-weighted where the rent roll allows it, unit-count otherwise. On a
      // floor of unequal suites the two differ materially and every recovery
      // and service-charge line follows the area, not the unit count.
      derivedFrom: "occupancy",
      help: "Let area as a proportion of NLA at acquisition. Computed from the rent roll's occupancy column when one is uploaded. Distinct from the structural vacancy allowance below, which covers ongoing churn.",
    },
    {
      key: "contract_rent_total",
      label: "Contracted annual rent (total)",
      group: "Income",
      type: "currency",
      unit: "AED",
      extract: true,
      source: "rent_roll",
      derivedFrom: "annual_rent",
      help: "Total contracted annual rent across all tenancies. Summed from the rent roll when one is uploaded, and it OVERRIDES the per-sqft rent above — an actual rent roll beats a blended rate. Deliberately has no default; left blank, the model uses rent per sqft times let area.",
    },
    {
      key: "market_rent_total_input",
      label: "Market rent (total)",
      group: "Income",
      type: "currency",
      unit: "AED",
      extract: true,
      source: "rent_roll",
      derivedFrom: "market_rent_total",
      help: "Total market rent across all suites, from the rent roll's market-rent column. Overrides the per-sqft market rent when present. No default — left blank, the model uses market rent per sqft times NLA.",
    },
    {
      key: "market_rent_psf",
      label: "Market rent",
      group: "Income",
      type: "number",
      unit: "AED/sqft/yr",
      default: 170,
      min: 0,
      source: "assumption",
      help: "Achievable headline rent per sqft on a new letting today, before incentives. The reversion level applied when the current leases expire.",
    },
    {
      key: "walt_years",
      label: "WALT",
      group: "Income",
      type: "number",
      unit: "years",
      default: 5,
      min: 0,
      max: 30,
      required: true,
      extract: true,
      source: "rent_roll",
      help: "Weighted average lease term to expiry, weighted by rent. The single most important number in a commercial deal: it tells you how long the income is contracted for and when the void and incentive costs land. The model reverts income to market in the year after WALT expires, in the proportion set by the expiry concentration below.",
    },
    {
      key: "expiry_share",
      label: "Expiry concentration at WALT",
      group: "Income",
      type: "percent",
      default: 0.6,
      min: 0,
      max: 1,
      extract: true,
      source: "rent_roll",
      help: "Share of income that actually expires at the WALT point. A single-let warehouse is 100%; a well-laddered multi-let office is 30-50%. The void, rent-free, letting commission and fit-out contribution are all weighted by this, so the reversion is a trough rather than a cliff. Set it from the real expiry profile — a blended WALT hides whether the leases are laddered or all fall in the same quarter.",
    },
    {
      key: "rent_escalation_pct",
      label: "Contractual rent escalation",
      group: "Income",
      type: "percent",
      default: 0.03,
      min: 0,
      max: 0.15,
      extract: true,
      source: "rent_roll",
      help: "Fixed annual uplift written into the leases, typically 3-5% in Dubai. Commercial leases are not subject to the RERA residential increase caps — the contract governs, so read the actual review clause rather than assuming.",
    },
    {
      key: "market_rent_growth",
      label: "Market rent growth",
      group: "Income",
      type: "percent",
      default: 0.035,
      min: -0.2,
      max: 0.3,
      help: "Growth in the market rent used at reversion. Kept separate from the contractual escalation because the two diverge — which is exactly what creates over- or under-renting at expiry.",
    },
    {
      key: "void_months",
      label: "Void on expiry",
      group: "Income",
      type: "number",
      unit: "months",
      default: 4,
      min: 0,
      max: 36,
      help: "Re-letting downtime when the WALT expires. Dubai office voids run 3-9 months depending on floorplate size and fit-out condition; a large single-let floor takes longer.",
    },
    {
      key: "rent_free_months",
      label: "Rent-free incentive",
      group: "Income",
      type: "number",
      unit: "months",
      default: 3,
      min: 0,
      max: 36,
      help: "Rent-free period granted on a new letting. Standard in Dubai offices at 1-3 months per year of term. This is why headline rent and effective rent diverge.",
    },
    {
      key: "fitout_contribution_psf",
      label: "Fit-out contribution",
      group: "Income",
      type: "number",
      unit: "AED/sqft",
      default: 0,
      min: 0,
      help: "Capital contribution to the incoming tenant's fit-out at reversion. Common on shell-and-core office lettings and on anchor retail.",
    },
    {
      key: "cheque_count",
      label: "Rent cheques per year",
      group: "Income",
      type: "select",
      default: 4,
      options: [
        { value: 1, label: "1 cheque (annual, in advance)" },
        { value: 2, label: "2 cheques" },
        { value: 4, label: "4 cheques" },
        { value: 6, label: "6 cheques" },
        { value: 12, label: "12 cheques" },
      ],
      extract: true,
      source: "rent_roll",
      derivedFrom: "cheque_count",
      help: "Modal cheque count across the rent roll when one is uploaded. Commercial tenants in Dubai typically pay on 1-4 post-dated cheques; monthly is a weak-covenant signal. The float benefit is priced explicitly below.",
    },
    {
      key: "vacancy_rate",
      label: "Structural vacancy allowance",
      group: "Income",
      type: "percent",
      default: 0.08,
      min: 0,
      max: 0.4,
      help: "Ongoing churn allowance, over and above the modelled void at WALT expiry. 8% is the Dubai commercial working assumption; use 5% for prime DIFC or a long single-let warehouse.",
    },
    {
      key: "bad_debt_rate",
      label: "Bad debt / cheque bounce allowance",
      group: "Income",
      type: "percent",
      default: 0.015,
      min: 0,
      max: 0.2,
      help: "Since the 2022 amendments a bounced cheque is no longer a criminal offence in the UAE, only civilly enforceable. On an SME tenant base this line is real.",
    },
    {
      key: "other_income",
      label: "Other income",
      group: "Income",
      type: "currency",
      unit: "AED",
      default: 0,
      min: 0,
      help: "Parking, signage, antenna and storage income. Keep separate from rent so it is not capitalised at the same yield on exit.",
    },
    {
      key: "largest_tenant_pct",
      label: "Largest tenant share of income",
      group: "Income",
      type: "percent",
      default: 0.35,
      min: 0,
      max: 1,
      extract: true,
      source: "rent_roll",
      help: "Proportion of contracted rent from the single largest tenant. Above 40% the deal is effectively a credit position on that tenant rather than a property investment.",
    },
    {
      key: "tenant_covenant",
      label: "Principal tenant covenant",
      group: "Income",
      type: "select",
      default: "sme",
      options: [
        { value: "government", label: "Government / semi-government" },
        { value: "multinational", label: "Multinational / listed" },
        { value: "sme", label: "SME / local trading" },
        { value: "startup", label: "Startup / early stage" },
      ],
      help: "Covenant strength of the largest tenant. In Dubai the practical questions are trade licence longevity, free zone versus mainland registration, and whether a parent guarantee or a bank guarantee is in place — a UAE branch of a multinational is not the multinational.",
    },
    {
      key: "security_deposit_months",
      label: "Security deposit held",
      group: "Income",
      type: "number",
      unit: "months",
      default: 3,
      min: 0,
      max: 24,
      help: "Months of rent held as deposit or bank guarantee. Three months is the Dubai commercial norm; less than one month on an SME covenant is a material weakness.",
    },

    // -------------------------------------------------- operating costs --
    {
      key: "service_charge_budget_psf",
      label: "Service charge (OA budget)",
      group: "Operating costs",
      type: "number",
      unit: "AED/sqft/yr",
      default: 26,
      min: 0,
      max: 120,
      required: true,
      extract: true,
      source: "om",
      help: "Mollak-approved Owners Association budget per sqft per year, before VAT. Typical: office 18-35, retail 20-40, warehouse 2-6.",
    },
    {
      key: "service_charge_recoverable",
      label: "Service charge recoverable from tenant",
      group: "Operating costs",
      type: "boolean",
      default: true,
      extract: true,
      source: "rent_roll",
      help: "In Dubai commercial the service charge is usually recharged to the tenant on top of rent, but not always, and not on every lease in a multi-let building. This single boolean is the largest swing factor in the deal — read the actual leases, not the OM summary.",
    },
    {
      key: "service_charge_t12_total",
      label: "Service charge (T12 actual, total)",
      group: "Operating costs",
      type: "currency",
      unit: "AED",
      extract: true,
      source: "t12",
      derivedFrom: "t12_service_charge",
      help: "Total annual service charge from the T12. Overrides the per-sqft budget when present. No default — left blank, the model uses the budget rate.",
    },
    {
      key: "t12_opex_total",
      label: "Total OpEx (T12 actual)",
      group: "Operating costs",
      type: "currency",
      unit: "AED",
      extract: true,
      source: "t12",
      derivedFrom: "t12_opex_total",
      help: "Total annualised recurring operating expenses from the T12, used purely as a cross-check against the model's own build-up. It feeds no calculation. A large divergence means the build-up is missing something the building actually pays for.",
    },
    {
      key: "reserve_fund_pct_of_sc",
      label: "Reserve fund share of service charge",
      group: "Operating costs",
      type: "percent",
      default: 0.1,
      min: 0,
      max: 0.5,
      help: "The reserve fund contribution sits inside the OA budget at a typical 8-15%. Memo line only — not added twice.",
    },
    {
      key: "chiller_borne_by",
      label: "District cooling borne by",
      group: "Operating costs",
      type: "select",
      default: "tenant",
      options: [
        { value: "tenant", label: "Tenant" },
        { value: "landlord", label: "Landlord" },
        { value: "master_developer", label: "Master developer / inside service charge" },
        { value: "none", label: "No district cooling" },
      ],
      help: "Empower, Emicool and Tabreed bill a fixed capacity charge per refrigeration ton, payable whether or not the space is occupied. On a void floor the landlord picks it up regardless of who normally pays.",
    },
    {
      key: "chiller_annual_charge",
      label: "District cooling capacity charge",
      group: "Operating costs",
      type: "currency",
      unit: "AED",
      default: 0,
      min: 0,
      extract: true,
      source: "t12",
      derivedFrom: "t12_chiller_cooling",
      help: "Annual fixed capacity charge for the building's connected tonnage, excluding metered consumption. Picked up from the T12 cooling category when a T12 is uploaded.",
    },
    {
      key: "management_fee_pct",
      label: "Property management fee",
      group: "Operating costs",
      type: "percent",
      default: 0.04,
      min: 0,
      max: 0.12,
      help: "Fee on collected rent. Dubai commercial managing agents charge 3-5%, below the residential 5-8% because there are fewer, larger tenancies.",
    },
    {
      key: "leasing_commission_pct",
      label: "Leasing commission",
      group: "Operating costs",
      type: "percent",
      default: 0.05,
      min: 0,
      max: 0.15,
      help: "Agency fee on a new commercial letting, typically 5% of the first year's rent. Charged in full in the reversion year.",
    },
    {
      key: "insurance_rate",
      label: "Insurance",
      group: "Operating costs",
      type: "percent",
      default: 0.0005,
      min: 0,
      max: 0.005,
      help: "Landlord buildings and liability cover, 0.03-0.08% of value.",
    },
    {
      key: "non_recoverable_psf",
      label: "Non-recoverable landlord costs",
      group: "Operating costs",
      type: "number",
      unit: "AED/sqft/yr",
      default: 4,
      min: 0,
      max: 40,
      help: "Landlord-side costs that never reach the service charge: asset management time, letting marketing, legal, and the shortfall on vacant-unit service charge. Do not set this to zero on a multi-let building.",
    },
    {
      key: "opex_growth",
      label: "OpEx growth",
      group: "Operating costs",
      type: "percent",
      default: 0.035,
      min: -0.1,
      max: 0.3,
      help: "Annual escalation on service charge, cooling, insurance and non-recoverable landlord costs. Dubai OA budgets have historically outpaced general inflation as buildings age and reserve funds catch up.",
    },
    {
      key: "vat_treatment",
      label: "VAT treatment",
      group: "Operating costs",
      type: "select",
      default: "standard_rated",
      options: [
        { value: "standard_rated", label: "Standard-rated commercial lease — input VAT recoverable" },
        { value: "exempt_residential", label: "Exempt / residential element — input VAT NOT recoverable" },
      ],
      help: "A commercial lease is standard-rated at 5%, so the landlord charges output VAT and recovers input VAT on service charges and fees. Set to exempt only for a mixed asset with a residential component, where that share of input VAT is blocked.",
    },

    // ------------------------------------------------- acquisition costs --
    {
      key: "dld_fee_pct",
      label: "DLD transfer fee",
      group: "Acquisition costs",
      type: "percent",
      default: 0.04,
      min: 0,
      max: 0.1,
      help: "Dubai Land Department transfer fee, 4% of the price. There is no annual property tax in Dubai.",
    },
    {
      key: "dld_admin_fee",
      label: "DLD administration fee",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 580,
      min: 0,
      help: "Fixed DLD administration charge levied alongside the 4% transfer fee at the trustee office.",
    },
    {
      key: "trustee_fee",
      label: "Registration trustee fee",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 4200,
      min: 0,
      help: "Charged by the DLD-appointed registration trustee office at transfer. AED 4,200 including VAT above AED 500,000; AED 2,000 below it.",
    },
    {
      key: "title_deed_fee",
      label: "Title deed issuance",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 580,
      min: 0,
      help: "Charge for issuing the new title deed in the buyer's name on completion of the transfer.",
    },
    {
      key: "agency_fee_pct",
      label: "Agency commission",
      group: "Acquisition costs",
      type: "percent",
      default: 0.02,
      min: 0,
      max: 0.06,
      help: "Buyer-side brokerage, 2% plus 5% VAT. On a standard-rated commercial acquisition the VAT is recoverable, so it is excluded from the cost base when the VAT treatment is standard-rated.",
    },
    {
      key: "developer_noc_fee",
      label: "Developer / free zone NOC fee",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 5000,
      min: 0,
      max: 50000,
      help: "NOC from the developer or free zone authority confirming service charges are clear. Commercial free zone NOCs run higher than the residential AED 500-5,000 band.",
    },
    {
      key: "valuation_fee",
      label: "Valuation",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 15000,
      min: 0,
      help: "RICS valuation for an income-producing commercial asset, well above the AED 2,500-3,500 residential mortgage valuation.",
    },
    {
      key: "legal_and_dd_fee",
      label: "Legal and technical due diligence",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 75000,
      min: 0,
      help: "Title and lease due diligence, building condition survey, MEP survey. On a multi-let office this is real money and it is the part of the budget that should not be cut.",
    },
    {
      key: "mortgage_reg_pct",
      label: "Mortgage registration",
      group: "Acquisition costs",
      type: "percent",
      default: 0.0025,
      min: 0,
      max: 0.01,
      help: "0.25% of the facility, registered against the title at the DLD, plus the fixed administration charge below.",
    },
    {
      key: "mortgage_admin_fee",
      label: "Mortgage registration admin",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 290,
      min: 0,
      help: "Fixed DLD administration charge added to the mortgage registration fee.",
    },
    {
      key: "bank_arrangement_pct",
      label: "Bank arrangement fee",
      group: "Acquisition costs",
      type: "percent",
      default: 0.01,
      min: 0,
      max: 0.03,
      help: "Processing fee charged by the lender at drawdown, typically 0.5-1.0% of the facility. Payable from equity, not from loan proceeds.",
    },

    // --------------------------------------------------------- financing --
    {
      key: "ltv",
      label: "Loan to value (requested)",
      group: "Financing",
      type: "percent",
      default: 0.55,
      min: 0,
      max: 0.75,
      help: "UAE banks lend 50-65% against income-producing commercial, and size to DSCR rather than to LTV. Set 0 for an all-cash purchase.",
    },
    {
      key: "max_ltv_input",
      label: "Lender LTV ceiling",
      group: "Financing",
      type: "percent",
      default: 0.65,
      min: 0,
      max: 0.75,
      help: "Ceiling the lender will go to for this asset class and covenant. Commercial is not covered by the Central Bank residential mortgage caps; it is a credit decision.",
    },
    {
      key: "interest_rate",
      label: "Interest rate",
      group: "Financing",
      type: "percent",
      default: 0.055,
      min: 0,
      max: 0.15,
      help: "All-in rate. Commercial facilities in the UAE are usually floating at 3M EIBOR plus 1.75-3.00%. Use the reversion rate for the DSCR test.",
    },
    {
      key: "loan_term_years",
      label: "Loan tenor",
      group: "Financing",
      type: "integer",
      unit: "years",
      default: 15,
      min: 1,
      max: 25,
      help: "Commercial tenors in the UAE are shorter than residential — 10-15 years is typical, often with a balloon.",
    },
    {
      key: "io_period_years",
      label: "Interest-only period",
      group: "Financing",
      type: "integer",
      unit: "years",
      default: 0,
      min: 0,
      max: 10,
      help: "Years of interest-only before amortisation begins. More common on commercial than residential in the UAE, often paired with a balloon at maturity — check what the balance is at the end of the tenor, not just the payment during it.",
    },
    {
      key: "dscr_covenant",
      label: "DSCR covenant",
      group: "Financing",
      type: "number",
      unit: "x",
      default: 1.3,
      min: 1,
      max: 2.5,
      help: "UAE lenders test commercial at 1.25-1.40x, tighter than residential because the income is lumpier and the WALT is finite.",
    },

    // -------------------------------------------------------------- exit --
    {
      key: "hold_period",
      label: "Hold period",
      group: "Exit",
      type: "integer",
      unit: "years",
      default: 7,
      min: 1,
      max: 15,
      required: true,
      help: "Years to exit. Seven years is a common commercial hold — long enough to trade through one reversion and re-establish a WALT before selling.",
    },
    {
      key: "exit_basis",
      label: "Exit basis",
      group: "Exit",
      type: "select",
      default: "cap_rate",
      options: [
        { value: "cap_rate", label: "Cap rate on exit-year NOI" },
        { value: "price_psf", label: "Price per sqft" },
      ],
      help: "Cap rate exits are analytically cleaner and are how an institutional buyer will price it; price-per-sqft exits are how strata commercial actually trades in Dubai. Run both.",
    },
    {
      key: "exit_cap_rate",
      label: "Exit cap rate",
      group: "Exit",
      type: "percent",
      default: 0.08,
      min: 0.03,
      max: 0.2,
      help: "Dubai commercial trades wider than residential — 7-9% for good multi-let office, tighter for a long single-let government or multinational covenant, wider for secondary stock or a short WALT.",
    },
    {
      key: "exit_price_psf",
      label: "Exit price per sqft",
      group: "Exit",
      type: "number",
      unit: "AED/sqft",
      help: "Only used when the exit basis is price per sqft. Deliberately has no default — supply a defensible number or the model will show a blank.",
    },
    {
      key: "selling_agency_pct",
      label: "Selling agency commission",
      group: "Exit",
      type: "percent",
      default: 0.02,
      min: 0,
      max: 0.06,
      help: "Sell-side brokerage plus VAT. The 4% DLD transfer fee on exit is a BUYER cost in Dubai and is not deducted from the seller's proceeds.",
    },
    {
      key: "exit_costs_other",
      label: "Other exit costs",
      group: "Exit",
      type: "currency",
      unit: "AED",
      default: 60000,
      min: 0,
      help: "Seller-side legal, trustee attendance, NOC and mortgage discharge on a commercial transfer.",
    },

    // ------------------------------------------------------ tax & returns --
    {
      key: "owner_type",
      label: "Ownership vehicle",
      group: "Tax",
      type: "select",
      default: "uae_mainland_entity",
      options: [
        { value: "individual", label: "Natural person (personal capacity)" },
        { value: "uae_mainland_entity", label: "UAE mainland company" },
        { value: "freezone_entity", label: "Free zone entity" },
        { value: "foreign_entity", label: "Foreign entity" },
      ],
      help: "UAE corporate tax is 9% above AED 375,000 of taxable income. A natural person earning real estate investment income in a personal capacity is out of scope. Commercial assets are usually held corporately, so tax normally applies here even though it usually does not in residential.",
    },
    {
      key: "corporate_tax_rate_input",
      label: "Corporate tax rate",
      group: "Tax",
      type: "percent",
      default: 0.09,
      min: 0,
      max: 0.3,
      help: "UAE headline corporate tax rate, applied only when the ownership vehicle is a company. Applied to NOI less interest.",
    },
    {
      key: "corporate_tax_threshold",
      label: "Corporate tax threshold",
      group: "Tax",
      type: "currency",
      unit: "AED",
      default: 375000,
      min: 0,
      help: "Taxable income below AED 375,000 is taxed at 0%. Applied per entity, not per property, so a portfolio held in one SPV consumes the threshold once.",
    },
    {
      key: "discount_rate",
      label: "Discount rate",
      group: "Returns",
      type: "percent",
      default: 0.11,
      min: 0,
      max: 0.4,
      help: "Required return for the NPV and for valuing the cheque-timing float. Commercial equity is priced wider than residential.",
    },
  ],

  lines: [
    // ---------------------------------------------------------- headline --
    {
      key: "purchase_price",
      label: "Purchase price",
      group: "Headline",
      formula: "price",
      unit: "AED",
      format: "currency",
      emphasis: "hero",
    },
    {
      key: "price_per_sqft",
      label: "Price per sqft (NLA)",
      group: "Headline",
      formula: "purchase_price / nla_sqft",
      unit: "AED/sqft",
      format: "per_sqft",
      precision: 0,
      emphasis: "hero",
    },
    {
      key: "meets_golden_visa",
      label: "Golden Visa eligible",
      group: "Compliance",
      formula: "purchase_price >= 2000000",
      format: "boolean",
      help: "The AED 2,000,000 property threshold for the 10-year renewable Golden Visa applies to commercial property held by a natural person too, though it is rarely the reason for a commercial purchase.",
    },
    {
      key: "short_tenure_tail",
      label: "Short tenure tail",
      group: "Compliance",
      formula: 'if(tenure == "freehold", false, tenure_years_remaining < 30)',
      format: "boolean",
      help: "Non-freehold interest with under 30 years to run. On commercial this bites harder than residential: institutional buyers price a short musataha or usufruct tail aggressively.",
    },

    // ------------------------------------------------------------ income --
    {
      key: "let_area_sqft",
      label: "Let area",
      group: "Income",
      formula: "nla_sqft * occupancy",
      unit: "sqft",
      format: "number",
      precision: 0,
    },
    {
      key: "annual_rent",
      label: "Contracted annual rent",
      group: "Income",
      formula: "ifnull(contract_rent_total, rent_psf * let_area_sqft)",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "The rent roll total where one was uploaded, otherwise passing rent per sqft applied to the currently let area. Contracted income, before the structural vacancy allowance.",
    },
    {
      key: "passing_rent_psf",
      label: "Passing rent per sqft (let area)",
      group: "Income",
      formula: "annual_rent / let_area_sqft",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 0,
      emphasis: "strong",
      help: "Contracted rent over the LET area — the rate an occupier is actually paying, and the correct like-for-like comparison against market rent. Distinct from rent per sqft below, which spreads the same rent over the whole NLA including the void.",
    },
    {
      key: "rent_per_sqft",
      label: "Rent per sqft (NLA)",
      group: "Income",
      formula: "annual_rent / nla_sqft",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 0,
      emphasis: "strong",
      help: "Contracted rent spread over the whole NLA — the number to compare against market rent, because it already carries the drag of the vacant space.",
    },
    {
      key: "market_rent_total",
      label: "Market rent (fully let)",
      group: "Income",
      formula: "ifnull(market_rent_total_input, market_rent_psf * nla_sqft)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "effective_market_rent_psf",
      label: "Market rent per sqft (effective)",
      group: "Income",
      formula: "market_rent_total / nla_sqft",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 0,
      help: "The rent-roll market total per sqft where one was uploaded, otherwise the market rate entered above. Everything downstream uses this.",
    },
    {
      key: "market_rent_let_area",
      label: "Market rent on let area",
      group: "Income",
      formula: "market_rent_total * occupancy",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Market rent applied to the currently let area. The reversion is modelled on this rather than on the fully-let figure, so a partly vacant building is not silently assumed to fill up at expiry.",
    },
    {
      key: "reversion_variance",
      label: "Over/under-rented",
      group: "Income",
      formula: "(passing_rent_psf - effective_market_rent_psf) / effective_market_rent_psf",
      format: "percent",
      precision: 1,
      emphasis: "strong",
      help: "Passing rent against market rent, per sqft. Positive means over-rented — income falls at expiry. Negative means reversionary upside, capturable at the WALT expiry because commercial renewals are not RERA-capped.",
    },
    {
      key: "reversion_year",
      label: "Reversion year",
      group: "Income",
      formula: "ceil(walt_years) + 1",
      unit: "years",
      format: "integer",
      help: "The projection year in which the WALT expires and the whole income reverts to market, carrying the void, rent-free and letting costs. A crude single-expiry proxy for what is really a staggered expiry profile.",
    },
    {
      key: "cheque_advantage_years",
      label: "Cheque timing advantage",
      group: "Income",
      formula: "1 / (2 * cheque_count)",
      unit: "years",
      format: "number",
      precision: 3,
    },
    {
      key: "effective_rent_advantage",
      label: "Value of cheque timing",
      group: "Income",
      formula: "annual_rent * discount_rate * cheque_advantage_years",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Float benefit of rent received in advance, valued at the discount rate. On a large commercial rent roll the difference between one cheque and twelve is a meaningful number.",
    },
    {
      key: "effective_rent",
      label: "Effective rent (incl. cheque timing)",
      group: "Income",
      formula: "annual_rent + effective_rent_advantage",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "vacancy_loss",
      label: "Structural vacancy allowance",
      group: "Income",
      formula: "annual_rent * vacancy_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "bad_debt_loss",
      label: "Bad debt / bounced cheques",
      group: "Income",
      formula: "annual_rent * bad_debt_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "collected_rent",
      label: "Collected rent",
      group: "Income",
      formula: "annual_rent - vacancy_loss - bad_debt_loss",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "security_deposit_held",
      label: "Security deposit held",
      group: "Income",
      formula: "annual_rent * security_deposit_months / 12",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Not income — shown so the reviewer can see how much of the tenant risk is actually collateralised.",
    },

    // --------------------------------------------------- operating costs --
    {
      key: "vat_unrecoverable_rate",
      label: "Irrecoverable VAT rate",
      group: "Operating costs",
      formula: 'if(vat_treatment == "exempt_residential", 5%, 0)',
      format: "percent",
      precision: 0,
      help: "Zero on a standard-rated commercial lease: the landlord charges 5% output VAT and recovers input VAT on service charges and fees. This is the structural cost advantage commercial has over residential in the UAE.",
    },
    {
      key: "vat_on_purchase",
      label: "VAT on purchase (recoverable)",
      group: "Acquisition costs",
      formula: 'if(vat_treatment == "exempt_residential", 0, purchase_price * 5%)',
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "muted",
      help: "Memo only, and deliberately NOT added to the cost base. A commercial building sale is standard-rated, so 5% VAT is payable at transfer and recovered on the next return — a working-capital event of real size, not a cost. Where the transfer qualifies as a transfer of a going concern it may fall outside the scope of VAT entirely.",
    },
    {
      key: "budget_psf",
      label: "Service charge budget per sqft (effective)",
      group: "Operating costs",
      formula: "ifnull(service_charge_t12_total / nla_sqft, service_charge_budget_psf)",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 2,
      help: "The T12 actual per sqft where a T12 was uploaded, otherwise the Mollak budget rate. Everything downstream uses this.",
    },
    {
      key: "service_charge_per_sqft",
      label: "Service charge per sqft (all-in)",
      group: "Operating costs",
      formula: "budget_psf * (1 + vat_unrecoverable_rate)",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 2,
      emphasis: "strong",
    },
    {
      key: "service_charge_total",
      label: "Service charge (gross)",
      group: "Operating costs",
      formula: "service_charge_per_sqft * nla_sqft",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "reserve_fund_contribution",
      label: "Reserve fund (memo, inside service charge)",
      group: "Operating costs",
      formula: "budget_psf * nla_sqft * reserve_fund_pct_of_sc",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "muted",
    },
    {
      key: "service_charge_recovery",
      label: "Service charge recovered from tenants",
      group: "Operating costs",
      formula: "if(service_charge_recoverable, service_charge_total * max(0, occupancy - vacancy_rate), 0)",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "Recovered only against let and paying space. The shortfall on vacant units is the landlord's — which is why a service charge that is 'fully recoverable' still costs money in a partly vacant building.",
    },
    {
      key: "service_charge_shortfall",
      label: "Service charge shortfall (landlord)",
      group: "Operating costs",
      formula: "service_charge_total - service_charge_recovery",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "The net service charge cost the landlord actually bears. Equal to the whole budget where the charge is not recoverable.",
    },
    {
      key: "chiller_cost",
      label: "District cooling capacity charge",
      group: "Operating costs",
      formula: 'if(chiller_borne_by == "landlord", chiller_annual_charge * (1 + vat_unrecoverable_rate), 0)',
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "management_fee",
      label: "Property management fee",
      group: "Operating costs",
      formula: "collected_rent * management_fee_pct * (1 + vat_unrecoverable_rate)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "insurance_cost",
      label: "Insurance",
      group: "Operating costs",
      formula: "purchase_price * insurance_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "non_recoverable_cost",
      label: "Non-recoverable landlord costs",
      group: "Operating costs",
      formula: "non_recoverable_psf * nla_sqft * (1 + vat_unrecoverable_rate)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "effective_gross_income",
      label: "Effective gross income",
      group: "Income",
      formula: "collected_rent + service_charge_recovery + ifnull(other_income, 0) + effective_rent_advantage",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "total_opex",
      label: "Total operating expenses",
      group: "Operating costs",
      formula:
        "service_charge_total + chiller_cost + management_fee + insurance_cost + non_recoverable_cost",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "Gross of recoveries — the recovery sits in income. There is no annual property tax in Dubai.",
    },
    {
      key: "opex_ratio",
      label: "OpEx ratio (net of recoveries)",
      group: "Operating costs",
      formula: "(total_opex - service_charge_recovery) / (effective_gross_income - service_charge_recovery)",
      format: "percent",
      precision: 1,
      help: "Landlord-borne cost over rental income, both stated net of the service charge recharge. A fully recovering Dubai office runs 8-14%; a non-recovering one runs 30%+, which is the whole point of the recoverability switch.",
    },
    {
      key: "opex_variance_to_t12",
      label: "Modelled OpEx vs T12 actual",
      group: "Operating costs",
      formula: "if(isnull(t12_opex_total), null, (total_opex - t12_opex_total) / t12_opex_total)",
      format: "percent",
      precision: 1,
      help: "Blank when no T12 has been uploaded.",
    },
    {
      key: "noi",
      label: "Net operating income",
      group: "Income",
      formula: "effective_gross_income - total_opex",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "hero",
    },
    {
      key: "gross_yield",
      label: "Gross yield",
      group: "Headline",
      formula: "annual_rent / purchase_price",
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "Contracted rent over price. Quoted constantly in the Dubai market; ignores the service charge shortfall, the void at reversion and the DLD fee.",
    },

    // ------------------------------------------------- acquisition costs --
    {
      key: "max_ltv",
      label: "Lender LTV ceiling",
      group: "Financing",
      formula: "max_ltv_input",
      format: "percent",
      precision: 0,
    },
    {
      key: "ltv_applied",
      label: "LTV applied",
      group: "Financing",
      formula: "min(ltv, max_ltv)",
      format: "percent",
      precision: 1,
      emphasis: "strong",
    },
    {
      key: "loan_amount",
      label: "Loan amount",
      group: "Financing",
      formula: "purchase_price * ltv_applied",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "dld_fee",
      label: "DLD transfer fee",
      group: "Acquisition costs",
      formula: "purchase_price * dld_fee_pct + dld_admin_fee",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "agency_fee",
      label: "Agency commission",
      group: "Acquisition costs",
      formula: "purchase_price * agency_fee_pct * (1 + vat_unrecoverable_rate)",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "VAT excluded where the buyer is standard-rated and recovers it; included where the input VAT is blocked.",
    },
    {
      key: "mortgage_registration_fee",
      label: "Mortgage registration",
      group: "Acquisition costs",
      formula: "if(loan_amount > 0, loan_amount * mortgage_reg_pct + mortgage_admin_fee, 0)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "bank_arrangement_fee",
      label: "Bank arrangement fee",
      group: "Acquisition costs",
      formula: "loan_amount * bank_arrangement_pct",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "total_acquisition_costs",
      label: "Total acquisition costs",
      group: "Acquisition costs",
      formula:
        "dld_fee + trustee_fee + title_deed_fee + agency_fee + developer_noc_fee + valuation_fee + legal_and_dd_fee + mortgage_registration_fee + bank_arrangement_fee",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "acquisition_cost_ratio",
      label: "Acquisition costs as % of price",
      group: "Acquisition costs",
      formula: "total_acquisition_costs / purchase_price",
      format: "percent",
      precision: 2,
    },
    {
      key: "all_in_cost",
      label: "All-in cost",
      group: "Acquisition costs",
      formula: "purchase_price + total_acquisition_costs",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "net_yield",
      label: "Net yield",
      group: "Headline",
      formula: "noi / all_in_cost",
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "NOI over all-in cost including the 4% DLD fee. The number an institutional buyer will actually underwrite to.",
    },
    {
      key: "equity_required",
      label: "Equity required",
      group: "Financing",
      formula: "all_in_cost - loan_amount",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },

    // ------------------------------------------------------------- debt --
    {
      key: "monthly_rate",
      label: "Monthly rate",
      group: "Financing",
      formula: "interest_rate / 12",
      format: "percent",
      precision: 4,
      hidden: true,
    },
    {
      key: "amortising_months",
      label: "Amortising months",
      group: "Financing",
      formula: "max(0, (loan_term_years - io_period_years) * 12)",
      format: "integer",
      hidden: true,
    },
    {
      key: "amortising_debt_service",
      label: "Debt service (amortising)",
      group: "Financing",
      formula: "if(loan_amount > 0, pmt(monthly_rate, amortising_months, loan_amount) * 12, 0)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "interest_only_debt_service",
      label: "Debt service (interest only)",
      group: "Financing",
      formula: "loan_amount * interest_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
      hidden: true,
    },
    {
      key: "annual_debt_service",
      label: "Annual debt service (year 1)",
      group: "Financing",
      formula: "if(io_period_years >= 1, interest_only_debt_service, amortising_debt_service)",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "dscr",
      label: "DSCR (year 1)",
      group: "Financing",
      formula: "if(annual_debt_service > 0, noi / annual_debt_service, null)",
      format: "ratio",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "debt_yield",
      label: "Debt yield",
      group: "Financing",
      formula: "if(loan_amount > 0, noi / loan_amount, null)",
      format: "percent",
      precision: 2,
    },
    {
      key: "negative_leverage",
      label: "Negative leverage",
      group: "Financing",
      formula: "if(loan_amount > 0, gross_yield < interest_rate, false)",
      format: "boolean",
    },
    {
      key: "levered_cash_flow",
      label: "Cash flow after debt service (year 1)",
      group: "Returns",
      formula: "noi - annual_debt_service",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "cash_on_cash",
      label: "Cash-on-cash (year 1)",
      group: "Returns",
      formula: "levered_cash_flow / equity_required",
      format: "percent",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "payback_years",
      label: "Payback period",
      group: "Returns",
      formula: "purchase_price / annual_rent",
      unit: "years",
      format: "years",
      precision: 1,
      emphasis: "hero",
    },
    {
      key: "net_payback_years",
      label: "Payback period (net of costs)",
      group: "Returns",
      formula: "all_in_cost / noi",
      unit: "years",
      format: "years",
      precision: 1,
    },
    {
      key: "break_even_occupancy",
      label: "Break-even occupancy",
      group: "Returns",
      formula: "(total_opex - service_charge_recovery + annual_debt_service) / annual_rent",
      format: "percent",
      precision: 1,
    },

    // -------------------------------------------------------------- tax --
    {
      key: "corporate_tax_rate",
      label: "Corporate tax rate applied",
      group: "Tax",
      formula: 'if(owner_type == "individual", 0, corporate_tax_rate_input)',
      format: "percent",
      precision: 0,
    },
    {
      key: "corporate_tax_threshold_applied",
      label: "Corporate tax threshold applied",
      group: "Tax",
      formula: 'if(owner_type == "individual", 0, corporate_tax_threshold)',
      unit: "AED",
      format: "currency",
      precision: 0,
      hidden: true,
    },

    // ------------------------------------------------------------- risk --
    {
      key: "tenant_concentration_risk",
      label: "Tenant concentration risk",
      group: "Risk",
      formula: "largest_tenant_pct > 40%",
      format: "boolean",
    },
    {
      key: "weak_covenant",
      label: "Weak principal covenant",
      group: "Risk",
      formula: 'if(tenant_covenant == "startup", true, tenant_covenant == "sme")',
      format: "boolean",
      help: "SME and startup covenants in Dubai are trade-licence-dependent. A free zone entity can be wound up and the licence surrendered far faster than a lease can be enforced.",
    },
    {
      key: "walt_short",
      label: "Short WALT",
      group: "Risk",
      formula: "walt_years < 3",
      format: "boolean",
    },
  ],

  projection: {
    years: "hold_period",
    rows: [
      {
        key: "is_reversion_year",
        label: "Reversion year",
        formula: "if(year == reversion_year, 1, 0)",
        format: "integer",
      },
      {
        key: "contract_rent_year",
        label: "Passing rent",
        formula:
          "if(year == 1, annual_rent, if(year == reversion_year, prev.contract_rent_year * (1 + rent_escalation_pct) * (1 - expiry_share) + market_rent_let_area * pow(1 + market_rent_growth, year - 1) * expiry_share, prev.contract_rent_year * (1 + rent_escalation_pct)))",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "rent_psf_year",
        label: "Passing rent per sqft (NLA)",
        formula: "contract_rent_year / nla_sqft",
        unit: "AED/sqft/yr",
        format: "per_sqft",
        precision: 0,
      },
      {
        key: "market_rent_psf_year",
        label: "Market rent per sqft",
        formula: "effective_market_rent_psf * pow(1 + market_rent_growth, year - 1)",
        unit: "AED/sqft/yr",
        format: "per_sqft",
        precision: 0,
      },
      {
        key: "void_fraction_year",
        label: "Void at reversion (income-weighted)",
        formula: "if(year == reversion_year, void_months / 12 * expiry_share, 0)",
        format: "percent",
        precision: 1,
      },
      {
        key: "vacancy_year",
        label: "Less: structural vacancy",
        formula: "-contract_rent_year * vacancy_rate",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "void_year",
        label: "Less: void at reversion",
        formula: "if(year == reversion_year, 0 - contract_rent_year * void_fraction_year, 0)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "rent_free_year",
        label: "Less: rent-free incentive",
        formula: "if(year == reversion_year, -contract_rent_year * rent_free_months / 12 * expiry_share, 0)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "bad_debt_year",
        label: "Less: bad debt / bounced cheques",
        formula: "-contract_rent_year * bad_debt_rate",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "collected_rent_year",
        label: "Collected rent",
        formula: "contract_rent_year + vacancy_year + void_year + rent_free_year + bad_debt_year",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "opex_escalator",
        label: "OpEx index (year 1 = 1.00)",
        formula: "pow(1 + opex_growth, year - 1)",
        format: "number",
        precision: 3,
      },
      {
        key: "service_charge_gross_year",
        label: "Service charge (gross budget)",
        formula: "service_charge_total * opex_escalator",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "sc_recovery_year",
        label: "Service charge recovered from tenants",
        formula:
          "if(service_charge_recoverable, service_charge_gross_year * max(0, occupancy - vacancy_rate - void_fraction_year), 0)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "other_income_year",
        label: "Other income",
        formula: "ifnull(other_income, 0) * pow(1 + market_rent_growth, year - 1)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "cheque_benefit_year",
        label: "Cheque timing benefit",
        formula: "contract_rent_year * discount_rate * cheque_advantage_years",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "egi_year",
        label: "Effective gross income",
        formula: "collected_rent_year + sc_recovery_year + other_income_year + cheque_benefit_year",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "chiller_year",
        label: "Less: district cooling capacity charge",
        formula: "0 - chiller_cost * opex_escalator",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "management_fee_year",
        label: "Less: property management fee",
        formula: "-collected_rent_year * management_fee_pct * (1 + vat_unrecoverable_rate)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "insurance_year",
        label: "Less: insurance",
        formula: "-insurance_cost * opex_escalator",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "non_recoverable_year",
        label: "Less: non-recoverable landlord costs",
        formula: "-non_recoverable_cost * opex_escalator",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "letting_costs_year",
        label: "Less: letting commission and fit-out at reversion",
        formula:
          "if(year == reversion_year, -(contract_rent_year * leasing_commission_pct + fitout_contribution_psf * nla_sqft) * expiry_share, 0)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "total_opex_year",
        label: "Total operating expenses",
        formula:
          "-service_charge_gross_year + chiller_year + management_fee_year + insurance_year + non_recoverable_year + letting_costs_year",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "noi_year",
        label: "Net operating income",
        formula: "egi_year + total_opex_year",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "hero",
      },
      {
        key: "loan_balance_open",
        label: "Loan balance (opening)",
        formula: "if(year == 1, loan_amount, prev.loan_balance_close)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "loan_balance_close",
        label: "Loan balance (closing)",
        formula:
          "if(loan_amount <= 0, 0, if(year <= io_period_years, loan_amount, balance(monthly_rate, amortising_months, loan_amount, (year - io_period_years) * 12)))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "debt_service_year",
        label: "Less: debt service",
        formula:
          "if(loan_amount <= 0, 0, if(year <= io_period_years, -interest_only_debt_service, -amortising_debt_service))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "principal_year",
        label: "of which principal repaid",
        formula: "loan_balance_open - loan_balance_close",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "interest_year",
        label: "of which interest",
        formula: "-debt_service_year - principal_year",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "dscr_year",
        label: "DSCR",
        formula: "if(loan_amount > 0, noi_year / -debt_service_year, null)",
        format: "ratio",
        precision: 2,
        emphasis: "strong",
      },
      {
        key: "taxable_income_year",
        label: "Taxable income",
        formula: "noi_year - interest_year",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "tax_year",
        label: "Less: UAE corporate tax",
        formula:
          "if(corporate_tax_rate <= 0, 0, -max(0, taxable_income_year - corporate_tax_threshold_applied) * corporate_tax_rate)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "levered_cf_year",
        label: "Levered cash flow (operations)",
        formula: "noi_year + debt_service_year + tax_year",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "exit_gross_value",
        label: "Exit gross value",
        formula:
          'if(year < years, 0, if(exit_basis == "price_psf", exit_price_psf * nla_sqft, noi_year / exit_cap_rate))',
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "exit_selling_costs",
        label: "Less: selling costs",
        formula:
          "if(year < years, 0, -(exit_gross_value * selling_agency_pct * (1 + vat_unrecoverable_rate) + exit_costs_other))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "exit_tax",
        label: "Less: tax on gain",
        formula:
          "if(year < years, 0, if(corporate_tax_rate <= 0, 0, -max(0, exit_gross_value + exit_selling_costs - all_in_cost) * corporate_tax_rate))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "loan_repayment",
        label: "Less: loan repayment",
        formula: "if(year < years, 0, -loan_balance_close)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "net_sale_proceeds",
        label: "Net sale proceeds",
        formula: "exit_gross_value + exit_selling_costs + exit_tax + loan_repayment",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "unlevered_cf_year",
        label: "Unlevered cash flow",
        formula: "noi_year + if(year < years, 0, exit_gross_value + exit_selling_costs)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "net_cash_flow_year",
        label: "Net cash flow to equity",
        formula: "levered_cf_year + net_sale_proceeds",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "hero",
      },
    ],
  },

  returns: [
    {
      key: "exit_value",
      label: "Exit gross value",
      group: "Returns",
      formula: 'series_last("exit_gross_value")',
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "exit_price_per_sqft",
      label: "Exit price per sqft",
      group: "Returns",
      formula: "exit_value / nla_sqft",
      unit: "AED/sqft",
      format: "per_sqft",
      precision: 0,
    },
    {
      key: "total_distributions",
      label: "Total cash to equity",
      group: "Returns",
      formula: 'series_sum("net_cash_flow_year")',
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "levered_irr",
      label: "Levered IRR",
      group: "Returns",
      formula: 'series_irr("net_cash_flow_year", -equity_required)',
      format: "percent",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "unlevered_irr",
      label: "Unlevered IRR",
      group: "Returns",
      formula: 'series_irr("unlevered_cf_year", -all_in_cost)',
      format: "percent",
      precision: 2,
    },
    {
      key: "equity_multiple",
      label: "Equity multiple",
      group: "Returns",
      formula: "total_distributions / equity_required",
      format: "multiple",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "avg_levered_cash_flow",
      label: "Average annual cash flow",
      group: "Returns",
      formula: 'series_avg("levered_cf_year")',
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "avg_cash_on_cash",
      label: "Average cash-on-cash",
      group: "Returns",
      formula: "avg_levered_cash_flow / equity_required",
      format: "percent",
      precision: 2,
      emphasis: "strong",
    },
    {
      key: "min_levered_cash_flow",
      label: "Worst-year cash flow",
      group: "Returns",
      formula: 'series_min("levered_cf_year")',
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "min_dscr",
      label: "Minimum DSCR",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_min("dscr_year"), null)',
      format: "ratio",
      precision: 2,
      emphasis: "strong",
    },
    {
      key: "peak_dscr",
      label: "Peak DSCR",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_max("dscr_year"), null)',
      format: "ratio",
      precision: 2,
    },
    {
      key: "years_below_covenant",
      label: "Years below DSCR covenant",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_count_below("dscr_year", dscr_covenant), 0)',
      format: "integer",
    },
    {
      key: "npv_at_discount",
      label: "NPV at discount rate",
      group: "Returns",
      formula: 'series_npv("net_cash_flow_year", discount_rate, -equity_required)',
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "reversion_year_noi",
      label: "Reversion-year NOI",
      group: "Returns",
      formula: 'series_at("noi_year", reversion_year)',
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "NOI in the year the WALT expires, carrying the void, rent-free and letting costs. Compare against year one to see the true depth of the reversion trough.",
    },
    {
      key: "reversion_noi_drop",
      label: "Reversion NOI drop vs year 1",
      group: "Returns",
      formula: 'if(isnull(reversion_year_noi), null, (reversion_year_noi - series_first("noi_year")) / series_first("noi_year"))',
      format: "percent",
      precision: 1,
      emphasis: "strong",
    },
    {
      key: "terminal_rent_psf",
      label: "Exit-year rent per sqft",
      group: "Returns",
      formula: 'series_last("rent_psf_year")',
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 0,
    },
  ],

  summary: [
    "price_per_sqft",
    "purchase_price",
    "annual_rent",
    "gross_yield",
    "net_yield",
    "service_charge_per_sqft",
    "cash_on_cash",
    "payback_years",
    "dscr",
  ],

  benchmarks: [
    {
      key: "dscr",
      label: "DSCR (year 1)",
      direction: "higher",
      good: 1.45,
      warn: 1.3,
      unit: "x",
      note: "UAE lenders test commercial at 1.25-1.40x. Hold more headroom than residential — the income is lumpier and the WALT is finite.",
    },
    {
      key: "min_dscr",
      label: "Minimum DSCR over hold",
      direction: "higher",
      good: 1.35,
      warn: 1.25,
      unit: "x",
      note: "The binding test is the reversion year, when the void and letting costs land.",
    },
    {
      key: "gross_yield",
      label: "Gross yield",
      direction: "higher",
      good: 0.09,
      warn: 0.075,
      note: "Dubai commercial trades wider than residential. Below 7.5% gross on a short WALT the price is doing the work.",
    },
    {
      key: "net_yield",
      label: "Net yield",
      direction: "higher",
      good: 0.075,
      warn: 0.06,
      note: "On all-in cost including the 4% DLD fee, after the service charge shortfall and non-recoverables.",
    },
    {
      key: "cash_on_cash",
      label: "Cash-on-cash (year 1)",
      direction: "higher",
      good: 0.08,
      warn: 0.05,
    },
    {
      key: "avg_cash_on_cash",
      label: "Average cash-on-cash",
      direction: "higher",
      good: 0.08,
      warn: 0.05,
    },
    {
      key: "levered_irr",
      label: "Levered IRR",
      direction: "higher",
      good: 0.17,
      warn: 0.13,
      note: "Dubai commercial equity is underwritten wider than residential to compensate for reversion and covenant risk.",
    },
    {
      key: "equity_multiple",
      label: "Equity multiple",
      direction: "higher",
      good: 2,
      warn: 1.6,
      unit: "x",
    },
    {
      key: "debt_yield",
      label: "Debt yield",
      direction: "higher",
      good: 0.11,
      warn: 0.09,
      note: "Rate-independent leverage test. UAE commercial lenders look for 10%+.",
    },
    {
      key: "walt_years",
      label: "WALT",
      direction: "higher",
      good: 5,
      warn: 3,
      unit: "years",
      note: "Below three years the deal is a leasing project, not an income investment.",
    },
    {
      key: "payback_years",
      label: "Payback",
      direction: "lower",
      good: 11,
      warn: 14,
      unit: "years",
    },
  ],

  flags: [
    {
      id: "dscr_below_covenant",
      when: "loan_amount > 0 and dscr < dscr_covenant",
      severity: "red",
      title: "Year-one DSCR below the covenant",
      detail:
        "DSCR is {dscr} against a {dscr_covenant}× covenant, on NOI of {noi} and debt service of {annual_debt_service}. Debt yield is {debt_yield}.",
      metric: "dscr",
      dd: "Ask the lender whether it sizes on DSCR or LTV, whether it stresses at the EIBOR reversion, and whether it applies a WALT haircut to the income used in the test.",
    },
    {
      id: "dscr_breach_at_reversion",
      when: "loan_amount > 0 and years_below_covenant > 0 and dscr >= dscr_covenant",
      severity: "amber",
      title: "DSCR breaches at the reversion",
      detail:
        "The deal opens at {dscr} but breaches the {dscr_covenant}× covenant in {years_below_covenant} of the projected years, bottoming at {min_dscr}. The void, rent-free and letting costs at the WALT expiry are what break it.",
      metric: "min_dscr",
      dd: "Ask the lender for a cash-sweep or covenant holiday around the reversion year, or size the facility to survive it. Confirm the actual expiry profile lease by lease rather than relying on a single blended WALT.",
    },
    {
      id: "short_walt",
      when: "walt_years < 3",
      severity: "red",
      title: "WALT under three years",
      detail:
        "WALT is {walt_years} years, so {expiry_share} of the income reverts in year {reversion_year} of a {hold_period}-year hold. Reversion-year NOI is {reversion_year_noi}, a change of {reversion_noi_drop} against year one. This is a leasing project priced as an income investment.",
      metric: "walt_years",
      dd: "Obtain the full expiry profile lease by lease, each tenant's break option and renewal right, and the current fit-out condition of every suite. Establish which tenants have already indicated they are leaving.",
    },
    {
      id: "over_rented",
      when: "reversion_variance > 10%",
      severity: "red",
      title: "Over-rented against market",
      detail:
        "Passing rent of {passing_rent_psf} AED/sqft is {reversion_variance} above market rent of {effective_market_rent_psf} AED/sqft. Income falls at the reversion in year {reversion_year} and the exit valuation will be struck on the reverted level, not the passing level.",
      metric: "reversion_variance",
      dd: "Establish why the rent is above market — legacy lease, fit-out amortisation, or an inflated pre-sale letting. Check whether the tenant has a break option before the WALT expiry.",
    },
    {
      id: "under_rented_upside",
      when: "reversion_variance < -10%",
      severity: "positive",
      title: "Under-rented — reversionary upside",
      detail:
        "Passing rent of {passing_rent_psf} AED/sqft is {reversion_variance} against market of {effective_market_rent_psf} AED/sqft. Unlike Dubai residential, a commercial renewal is not subject to the RERA increase caps, so the full reversion is capturable at expiry in year {reversion_year} — net of a {void_months}-month void and {rent_free_months} months rent-free.",
      metric: "reversion_variance",
      dd: "Confirm no lease contains a renewal option at a fixed or indexed rent that would block the reversion, and that the market evidence supports the assumed market rent for this floorplate size.",
    },
    {
      id: "service_charge_not_recoverable",
      when: "not service_charge_recoverable",
      severity: "red",
      title: "Service charge is not recoverable from tenants",
      detail:
        "The landlord carries the full service charge of {service_charge_total} ({service_charge_per_sqft} AED/sqft), with no recovery. That is the single largest swing factor in the deal and it takes the net yield to {net_yield} against a gross of {gross_yield}.",
      metric: "service_charge_shortfall",
      dd: "Read every lease for the service charge clause, any cap on the recharge, and any exclusion for capital items. A cap that has not moved since signing is effectively a non-recovery.",
    },
    {
      id: "service_charge_out_of_band",
      when:
        'budget_psf > if(asset_subtype == "warehouse", 6, if(asset_subtype == "retail", 40, 35))',
      severity: "amber",
      title: "Service charge above the normal band",
      detail:
        "The Mollak OA budget is {budget_psf} AED/sqft/yr, above the band for this asset type (office 18-35, retail 20-40, warehouse 2-6). The landlord's net shortfall is {service_charge_shortfall}.",
      metric: "service_charge_per_sqft",
      dd: "Pull three years of Mollak-approved budgets and the reserve fund study. Ask what proportion is district cooling and whether the recharge is capped.",
    },
    {
      id: "expiry_cliff",
      when: "expiry_share > 75%",
      severity: "amber",
      title: "Lease expiries are not laddered",
      detail:
        "{expiry_share} of income expires at the same point, in year {reversion_year}. Reversion-year NOI falls to {reversion_year_noi} ({reversion_noi_drop} against year one) and the worst projected cash flow is {min_levered_cash_flow}. A laddered expiry profile would spread the same reversion over several years.",
      metric: "expiry_share",
      dd: "Obtain the expiry profile by quarter, not by year, and check for co-terminous break options. Ask whether the leases can be re-geared on a staggered basis before the cliff arrives.",
    },
    {
      id: "opex_diverges_from_t12",
      when: "abs(opex_variance_to_t12) > 20%",
      severity: "amber",
      title: "Modelled OpEx diverges from the T12",
      detail:
        "The model carries {total_opex} of gross operating expenses against a T12 actual of {t12_opex_total}, a variance of {opex_variance_to_t12}. That flows straight through to NOI of {noi} and the {net_yield} net yield.",
      metric: "opex_variance_to_t12",
      dd: "Reconcile line by line. On a commercial building the usual gaps are service charge billed on a different area basis, non-recoverables the seller absorbed personally, and one-off capital works sitting in a recurring category.",
    },
    {
      id: "tenant_concentration",
      when: "tenant_concentration_risk",
      severity: "amber",
      title: "Income concentrated in one tenant",
      detail:
        "The largest tenant provides {largest_tenant_pct} of contracted rent on a {tenant_covenant} covenant, with {security_deposit_months} months of deposit held ({security_deposit_held}). At that share the investment is a credit position on one counterparty.",
      metric: "largest_tenant_pct",
      dd: "Obtain audited accounts or a parent guarantee for the largest tenant, and confirm whether the UAE entity is a branch or a separately capitalised free zone company. A branch of a multinational is not the multinational.",
    },
    {
      id: "weak_covenant_short_deposit",
      when: "weak_covenant and security_deposit_months < 3",
      severity: "amber",
      title: "Weak covenant with a thin deposit",
      detail:
        "The principal tenant is a {tenant_covenant} covenant and only {security_deposit_months} months of rent is held as security ({security_deposit_held}). Since 2022 a bounced cheque in the UAE is civilly enforceable only, so the deposit is most of the practical recovery.",
      metric: "security_deposit_held",
      dd: "Request a bank guarantee or an uplift to three months' deposit as a condition, and check the trade licence expiry and renewal history of each material tenant.",
    },
    {
      id: "twelve_cheque_tenant",
      when: "cheque_count >= 12",
      severity: "amber",
      title: "Twelve-cheque tenancies — collection risk",
      detail:
        "Rent is collected on {cheque_count} cheques. Monthly payment on a commercial letting in Dubai is a weak-covenant signal, and since the 2022 amendments a bounced cheque is no longer a criminal offence — only civilly enforceable through the courts, which takes months.",
      metric: "bad_debt_loss",
      dd: "Check the payment history and whether the landlord has been holding cheques rather than banking them. Stress the bad-debt allowance.",
    },
    {
      id: "negative_leverage",
      when: "negative_leverage",
      severity: "red",
      title: "Negative leverage",
      detail:
        "Gross yield of {gross_yield} is below the interest rate of {interest_rate}. The levered IRR of {levered_irr} against an unlevered {unlevered_irr} shows leverage is not paying for itself.",
      metric: "gross_yield",
      dd: "Re-run unlevered and at a lower LTV. Establish whether the lender would accept a smaller facility at a better margin.",
    },
    {
      id: "building_age_capex_risk",
      when: "building_age_years > 15",
      severity: "amber",
      title: "Building past fifteen years — capital works cycle",
      detail:
        "The building is {building_age_years} years old. Chiller plant, lifts, BMS and facade all fall due around this point, arriving as an OA special levy or as a step change in the {service_charge_per_sqft} AED/sqft service charge. Reserve fund is {reserve_fund_contribution} a year.",
      metric: "reserve_fund_contribution",
      dd: "Commission a building condition and MEP survey. Obtain the OA reserve fund study and forward capital plan, and price any shortfall into the offer.",
    },
    {
      id: "short_tenure_tail",
      when: "short_tenure_tail",
      severity: "red",
      title: "Short tenure tail destroys exit value",
      detail:
        "Tenure is {tenure} with {tenure_years_remaining} years remaining. Institutional buyers and lenders both price a short musataha or usufruct tail aggressively, so the exit at {exit_price_per_sqft} AED/sqft is unlikely to hold.",
      metric: "tenure_years_remaining",
      dd: "Obtain the head lease or musataha agreement and check the renewal mechanism, ground rent review, assignment consent and reinstatement obligation at expiry.",
    },
    {
      id: "vacancy_above_norm",
      when: "occupancy < 90%",
      severity: "amber",
      title: "Occupancy below 90%",
      detail:
        "Physical occupancy is {occupancy}, so the landlord is carrying the service charge on the void space. Break-even occupancy is {break_even_occupancy} and the service charge shortfall is {service_charge_shortfall}.",
      metric: "occupancy",
      dd: "Establish how long the space has been vacant, what fit-out condition it is in, and what the letting agent's realistic absorption estimate is for this floorplate in {community}.",
    },
    {
      id: "price_psf_outside_range",
      when:
        "price_per_sqft > community_price_psf_high * 1.1 or price_per_sqft < community_price_psf_low * 0.9",
      severity: "amber",
      title: "Price per sqft outside the submarket range",
      detail:
        "At {price_per_sqft} AED/sqft the asset sits outside the {community} range of {community_price_psf_low} to {community_price_psf_high}.",
      metric: "price_per_sqft",
      dd: "Assemble transacted comparables for the same free zone and building grade over the last eighteen months. Confirm whether the quoted areas are NLA or gross BUA — the difference alone can explain the variance.",
    },
    {
      id: "negative_cash_flow_year",
      when: "min_levered_cash_flow < 0",
      severity: "red",
      title: "Negative levered cash flow in at least one year",
      detail:
        "The worst projected year produces {min_levered_cash_flow} after debt service and tax, almost certainly the reversion year in year {reversion_year} when the void, rent-free and letting costs land together. Average annual cash flow is {avg_levered_cash_flow}.",
      metric: "min_levered_cash_flow",
      dd: "Confirm the equity has committed reserves to fund the reversion trough, and that the facility documentation permits the resulting covenant position.",
    },
    {
      id: "payback_too_long",
      when: "payback_years > 14",
      severity: "amber",
      title: "Payback beyond fourteen years",
      detail:
        "Contracted rent repays the price in {payback_years} years ({gross_yield} gross yield); net of all-in costs the payback is {net_payback_years} years. Dubai commercial normally prices to a shorter payback than residential because the income is less durable.",
      metric: "payback_years",
      dd: "Compare against transacted yields for comparable WALT and covenant. If this is tighter, identify what the market is paying for that this model has not captured.",
    },
    {
      id: "exit_yield_compression_assumed",
      when: "exit_cap_rate < net_yield",
      severity: "amber",
      title: "Exit assumes yield compression",
      detail:
        "The exit cap of {exit_cap_rate} is tighter than the going-in net yield of {net_yield}. Part of the {levered_irr} levered IRR is a market call, not an operating result — and it is being made on an asset whose WALT at exit will be shorter than at entry unless the reversion is re-let long.",
      metric: "exit_cap_rate",
      dd: "Re-run at an exit cap 75bps wider than going-in. Establish what WALT the exit assumption implicitly requires and whether the reversion strategy delivers it.",
    },
    {
      id: "corporate_tax_in_scope",
      when: "corporate_tax_rate > 0",
      severity: "info",
      title: "UAE corporate tax applies to this vehicle",
      detail:
        "Held through a {owner_type}, income is within the scope of UAE corporate tax at {corporate_tax_rate} above the AED 375,000 threshold.",
      metric: "corporate_tax_rate",
      dd: "Confirm with a UAE tax adviser whether free zone Qualifying Income treatment is available for real estate held in a free zone, and how the general interest limitation rule affects deductibility of the {interest_rate} facility.",
    },
    {
      id: "landlord_carries_chiller",
      when: 'chiller_borne_by == "landlord" and chiller_cost > 0',
      severity: "info",
      title: "Landlord carries the district cooling capacity charge",
      detail:
        "District cooling costs the landlord {chiller_cost} a year. The capacity charge is payable in full on vacant space, so it compounds the cost of the void in year {reversion_year}.",
      metric: "chiller_cost",
      dd: "Obtain the Empower / Emicool / Tabreed contract and the connected tonnage, and check whether the capacity charge can be passed through in the service charge or novated to incoming tenants.",
    },
  ],

  methodology:
    "Rent is modelled per sqft per year on the let area, escalated at the contractual review rate written into the leases. Dubai commercial renewals are governed by the lease, not by the RERA residential increase caps of Decree 43/2013, so no statutory cap is applied — read the actual review clause. The WALT is treated as a single blended expiry: in the year after it elapses, the expiry-concentration share of income reverts to grown market rent on the currently let area, and the model charges a re-letting void, a rent-free incentive, leasing commission and any fit-out contribution on that same share in that year. The rest of the income continues to escalate at the contractual rate. That is still a simplification of a real expiry profile — it concentrates the pain into one year rather than spreading it across the quarters in which leases actually fall — so the reversion-year DSCR is conservative and the surrounding years are optimistic. A commercial lease is a standard-rated supply: the landlord charges 5% output VAT and recovers input VAT, so the irrecoverable-VAT drag that dominates residential OpEx is zero here. The 5% VAT on the purchase price is shown as a memo and deliberately excluded from the cost base, because it is recovered on the next return and may fall outside the scope of VAT altogether where the sale qualifies as a transfer of a going concern. Service charge is modelled gross in OpEx with the recovery shown in income, recovered only against let and paying space, so a vacant floor correctly costs the landlord its own service charge. Yields are struck on all-in cost including the 4% DLD transfer fee; the exit deducts selling agency and costs but not the DLD fee, which is a buyer cost in Dubai. UAE corporate tax at 9% above AED 375,000 applies to corporate vehicles, with interest deducted. What this model does NOT do: it does not model a lease-by-lease rent roll or a staggered expiry profile, does not model break options, does not model turnover rent or stepped retail rents, does not model a service charge cap or a capital-expenditure exclusion in the recharge, does not model a refinance or an interest rate hedge, does not apply a WALT-driven adjustment to the exit cap rate, and does not test free zone occupier eligibility. Where a rent roll is uploaded, the contracted and market rent totals, area, occupancy and cheque count come from it and override the per-sqft rates; where a T12 is uploaded, the actual service charge and cooling charge override the budget assumptions and the modelled OpEx is cross-checked against the T12 total. On any asset with more than a handful of tenants, replace the blended WALT with the actual expiry profile before this output is relied on.",
};
