// Dubai residential — full underwriting.
//
// The distinguishing feature of this model is that rental growth is not an
// assumption. On renewal of an existing tenancy, Decree 43 of 2013 caps the
// permitted increase against the RERA rental index in fixed tiers, and the tier
// is recomputed every year as the passing rent catches up. A unit 45% below
// index does not jump to market: it takes +20%, then re-tests, then +15%, and
// so on over several years. Any model that applies a flat 5% growth rate to a
// Dubai residential asset is wrong, and wrong in the optimistic direction.
//
// The second feature is cost base. Dubai has no annual property tax, so the
// service charge billed by the Owners Association through Mollak is the whole
// of the operating burden — and because a residential lease is a VAT-exempt
// supply, the landlord cannot recover the 5% VAT charged on it. That
// irrecoverable VAT is a real cost and is carried explicitly.

import type { ModelDefinition } from "../../lib/engine/types.ts";

export const dubaiResidentialFull: ModelDefinition = {
  key: "dubai-residential-full",
  name: "Dubai Residential — Full Underwriting",
  description:
    "Full underwriting for a Dubai apartment, villa or townhouse. RERA-capped rent projection with multi-year catch-up, Mollak service charge with irrecoverable VAT, district cooling, full DLD acquisition stack, amortising debt with an optional interest-only period, exit on cap rate or price per sqft, levered IRR and equity multiple.",
  // Market KEY, not a display label — matched exactly elsewhere in the system.
  market: "AE",
  currency: "AED",
  depth: "full",
  assetType: "residential",
  schemaVersion: 1,

  inputs: [
    // ---------------------------------------------------------- property --
    {
      key: "price",
      label: "Purchase price",
      group: "Property",
      type: "currency",
      unit: "AED",
      default: 2200000,
      min: 100000,
      required: true,
      extract: true,
      source: "om",
      help: "Agreed purchase price on the Form F / MOU, before acquisition costs.",
    },
    {
      key: "size_sqft",
      label: "Size",
      group: "Property",
      type: "number",
      unit: "sqft",
      default: 1250,
      min: 200,
      required: true,
      extract: true,
      source: "rent_roll",
      derivedFrom: "size_sqft",
      help: "Net saleable / BUA area from the title deed or Oqood, in square feet. Summed across the rent roll when one is uploaded. Multiply sqm by 10.7639 if the OM is metric.",
    },
    {
      key: "property_type",
      label: "Property type",
      group: "Property",
      type: "select",
      default: "apartment",
      options: [
        { value: "apartment", label: "Apartment" },
        { value: "villa", label: "Villa" },
        { value: "townhouse", label: "Townhouse" },
      ],
      help: "Sets the service-charge sanity band. Apartments carry the full OA budget (lifts, chillers, lobbies, pool); villas usually carry master-community charges only.",
    },
    {
      key: "community",
      label: "Community",
      group: "Property",
      type: "text",
      extract: true,
      source: "om",
      help: "Master community or district, e.g. Dubai Marina, JVC, Downtown, Arabian Ranches. Used in the write-up and to frame the price-per-sqft comparables.",
    },
    {
      key: "building_age_years",
      label: "Building age",
      group: "Property",
      type: "integer",
      unit: "years",
      default: 8,
      min: 0,
      max: 80,
      extract: true,
      source: "om",
      help: "Years since handover. Past roughly 15 years Dubai towers start hitting first-cycle capital works — chiller replacement, facade, lifts — which arrive as a reserve-fund top-up or a special levy on the owners.",
    },
    {
      key: "tenure",
      label: "Tenure",
      group: "Property",
      type: "select",
      default: "freehold",
      options: [
        { value: "freehold", label: "Freehold" },
        { value: "leasehold", label: "Leasehold" },
        { value: "usufruct", label: "Usufruct" },
        { value: "musataha", label: "Musataha" },
      ],
      help: "Freehold is available to all nationalities only in designated areas. Leasehold, usufruct (up to 99 years) and musataha (up to 50 years, with a right to build) all amortise to zero, and the exit market thins badly once the tail is short.",
    },
    {
      key: "tenure_years_remaining",
      label: "Tenure years remaining",
      group: "Property",
      type: "integer",
      unit: "years",
      default: 99,
      min: 0,
      max: 999,
      help: "Unexpired term. Ignore for freehold. Below about 30 years a leasehold or usufruct tail materially restricts the buyer pool — most UAE banks will not lend where the tail is under tenor plus 10 years.",
    },
    {
      key: "community_price_psf_low",
      label: "Community price/sqft — low",
      group: "Property",
      type: "number",
      unit: "AED/sqft",
      help: "Bottom of the recent DLD transacted range for comparable units in this community. Leave blank if unknown; the out-of-range flag simply will not fire.",
      source: "assumption",
    },
    {
      key: "community_price_psf_high",
      label: "Community price/sqft — high",
      group: "Property",
      type: "number",
      unit: "AED/sqft",
      help: "Top of the recent DLD transacted range for comparable units in this community.",
      source: "assumption",
    },

    // ------------------------------------------------------------ income --
    {
      key: "is_vacant",
      label: "Vacant on completion",
      group: "Income",
      type: "boolean",
      default: false,
      extract: true,
      source: "rent_roll",
      help: "If vacant, the model underwrites the market rent and the RERA cap does not bind on the first letting. If tenanted, the in-place contract rent is inherited along with its renewal cap.",
    },
    {
      key: "in_place_rent",
      label: "In-place contract rent",
      group: "Income",
      type: "currency",
      unit: "AED",
      default: 165000,
      min: 0,
      extract: true,
      source: "rent_roll",
      derivedFrom: "in_place_rent_total",
      help: "Annual rent as a lump sum on the current Ejari tenancy contract. Summed across units from the rent roll when one is uploaded. A buyer inherits the contract and its renewal position — this is the number the RERA cap is applied to.",
    },
    {
      key: "market_rent",
      label: "Market rent",
      group: "Income",
      type: "currency",
      unit: "AED",
      default: 185000,
      min: 0,
      extract: true,
      source: "rent_roll",
      derivedFrom: "market_rent_total",
      help: "Annual rent achievable today on a fresh letting of a vacant unit, from live listings and recent Ejari registrations in the building. Summed from the rent roll's market-rent column when one is uploaded.",
    },
    {
      key: "rera_index_rent",
      label: "RERA index rent",
      group: "Income",
      type: "currency",
      unit: "AED",
      default: 190000,
      min: 0,
      required: true,
      source: "assumption",
      help: "Annual rent the RERA rental index (the DLD Smart Rental Index) shows for this unit type in this building or area. This is the reference the permitted increase is measured against — not the asking rent, not the market rent.",
    },
    {
      key: "rent_regime",
      label: "Renewal regime",
      group: "Income",
      type: "select",
      default: "rera_capped_renewal",
      options: [
        { value: "rera_capped_renewal", label: "Existing tenant renews — RERA cap applies" },
        { value: "relet_at_market", label: "Tenant vacates — re-let at market/index" },
      ],
      help: "The RERA increase cap binds on the renewal of a subsisting tenancy. Where the tenant genuinely vacates the landlord may re-let at the index level, but eviction requires 12 months' notarised notice on statutory grounds and cannot be engineered simply to raise rent. Default assumes the cap binds.",
    },
    {
      key: "cheque_count",
      label: "Rent cheques per year",
      group: "Income",
      type: "select",
      default: 4,
      options: [
        { value: 1, label: "1 cheque (annual, in advance)" },
        { value: 2, label: "2 cheques" },
        { value: 4, label: "4 cheques" },
        { value: 6, label: "6 cheques" },
        { value: 12, label: "12 cheques" },
      ],
      extract: true,
      source: "rent_roll",
      derivedFrom: "cheque_count",
      help: "Post-dated cheques handed over at signing. Taken as the modal cheque count across the rent roll when one is uploaded. Fewer cheques means earlier cash and a stronger covenant, at the cost of a lower headline rent. The timing benefit is priced explicitly below.",
    },
    {
      key: "vacancy_rate",
      label: "Vacancy allowance",
      group: "Income",
      type: "percent",
      default: 0.05,
      min: 0,
      max: 0.4,
      source: "assumption",
      help: "Structural vacancy plus re-letting downtime. 5% is the Dubai residential norm; 8-10% for secondary communities or large units with a thin tenant pool.",
    },
    {
      key: "bad_debt_rate",
      label: "Bad debt / cheque bounce allowance",
      group: "Income",
      type: "percent",
      default: 0.015,
      min: 0,
      max: 0.2,
      source: "assumption",
      help: "Bounced post-dated cheques and eviction lag. Since 2022 a bounced cheque is no longer a criminal offence in the UAE, only civilly enforceable through the Rental Dispute Centre, so recovery is slower than the market remembers.",
    },
    {
      key: "other_income",
      label: "Other income",
      group: "Income",
      type: "currency",
      unit: "AED",
      default: 0,
      min: 0,
      help: "Parking bays let separately, storage, or a furniture premium. Keep out of the rent line so it is not capitalised at the same multiple on exit.",
    },
    {
      key: "market_rent_growth",
      label: "Market rent growth",
      group: "Income",
      type: "percent",
      default: 0.04,
      min: -0.2,
      max: 0.3,
      source: "assumption",
      help: "Annual growth in the RERA index itself. Note that this drives the ceiling, not the passing rent — the passing rent can only move by the permitted increase tier each year.",
    },

    // -------------------------------------------------- operating costs --
    {
      key: "service_charge_budget_psf",
      label: "Service charge (OA budget)",
      group: "Operating costs",
      type: "number",
      unit: "AED/sqft/yr",
      default: 16,
      min: 0,
      max: 80,
      required: true,
      extract: true,
      source: "om",
      help: "Mollak-approved Owners Association budget per sqft per year, before VAT. A landlord cost in residential and not recoverable from the tenant. Typical: apartment 10-25, villa 3-8.",
    },
    {
      key: "service_charge_t12_total",
      label: "Service charge (T12 actual, total)",
      group: "Operating costs",
      type: "currency",
      unit: "AED",
      extract: true,
      source: "t12",
      derivedFrom: "t12_service_charge",
      help: "Total annual service charge from the T12, if one is uploaded. When present it OVERRIDES the per-sqft budget above, because an actual beats an assumption. Deliberately has no default — left blank, the model uses the budget rate.",
    },
    {
      key: "t12_opex_total",
      label: "Total OpEx (T12 actual)",
      group: "Operating costs",
      type: "currency",
      unit: "AED",
      extract: true,
      source: "t12",
      derivedFrom: "t12_opex_total",
      help: "Total annualised recurring operating expenses from the T12. Used only as a cross-check against the model's own build-up — it does not feed any calculation. A large divergence means the build-up is missing a line the property actually incurs.",
    },
    {
      key: "reserve_fund_pct_of_sc",
      label: "Reserve fund share of service charge",
      group: "Operating costs",
      type: "percent",
      default: 0.1,
      min: 0,
      max: 0.5,
      help: "The reserve fund contribution is normally embedded inside the OA budget at 8-15%. Shown as a memo line — it is already inside the service charge and is not added again. A materially lower share is a warning sign for future special levies.",
    },
    {
      key: "chiller_borne_by",
      label: "District cooling borne by",
      group: "Operating costs",
      type: "select",
      default: "tenant",
      options: [
        { value: "tenant", label: "Tenant" },
        { value: "landlord", label: "Landlord" },
        { value: "master_developer", label: "Master developer / inside service charge" },
        { value: "none", label: "No district cooling" },
      ],
      extract: true,
      source: "om",
      help: "Empower, Emicool and Tabreed bill a fixed capacity charge per refrigeration ton that is payable whether or not the unit is occupied. Who carries it varies by building and by lease. If the landlord carries it, it is a fixed cost that does not fall with vacancy.",
    },
    {
      key: "chiller_annual_charge",
      label: "District cooling capacity charge",
      group: "Operating costs",
      type: "currency",
      unit: "AED",
      default: 0,
      min: 0,
      extract: true,
      source: "t12",
      derivedFrom: "t12_chiller_cooling",
      help: "Annual fixed capacity (demand) charge for the unit's connected refrigeration tonnage, excluding metered consumption. Picked up from the T12 cooling category when a T12 is uploaded. Only charged to the landlord when 'borne by' is set to landlord.",
    },
    {
      key: "management_fee_pct",
      label: "Property management fee",
      group: "Operating costs",
      type: "percent",
      default: 0.06,
      min: 0,
      max: 0.15,
      help: "Fee on collected rent. Dubai residential managing agents charge 5-8% for full management.",
    },
    {
      key: "leasing_commission_pct",
      label: "Leasing commission",
      group: "Operating costs",
      type: "percent",
      default: 0.05,
      min: 0,
      max: 0.15,
      help: "Agency fee on a new letting, market standard 5% of the annual rent. Only incurred when a tenant is replaced, so it is scaled by the turnover rate below.",
    },
    {
      key: "tenant_turnover_rate",
      label: "Tenant turnover rate",
      group: "Operating costs",
      type: "percent",
      default: 0.35,
      min: 0,
      max: 1,
      help: "Probability of having to re-let in any given year. Dubai residential tenancies average roughly three years, so 0.30-0.40 is the working range. Drives the leasing commission line.",
    },
    {
      key: "insurance_rate",
      label: "Insurance",
      group: "Operating costs",
      type: "percent",
      default: 0.0005,
      min: 0,
      max: 0.005,
      help: "Landlord contents and liability cover as a percentage of value; the range is 0.03-0.08%. Building cover normally sits inside the OA budget.",
    },
    {
      key: "maintenance_psf",
      label: "Landlord maintenance",
      group: "Operating costs",
      type: "number",
      unit: "AED/sqft/yr",
      default: 3,
      min: 0,
      max: 30,
      help: "In-unit maintenance the landlord carries beyond the OA scope — AC servicing inside the demise, white goods, make-good between tenancies.",
    },
    {
      key: "opex_growth",
      label: "OpEx growth",
      group: "Operating costs",
      type: "percent",
      default: 0.035,
      min: -0.1,
      max: 0.3,
      help: "Annual escalation on service charge, cooling, insurance and maintenance. Dubai OA budgets have historically grown ahead of general inflation as buildings age.",
    },
    {
      key: "vat_treatment",
      label: "VAT treatment",
      group: "Operating costs",
      type: "select",
      default: "exempt_residential",
      options: [
        { value: "exempt_residential", label: "Residential lease — VAT exempt (input VAT NOT recoverable)" },
        { value: "standard_rated", label: "Standard-rated — 5% VAT, input VAT recoverable" },
      ],
      help: "Residential leases are VAT exempt in the UAE. The landlord makes no taxable supply, so the 5% VAT charged on service charges, management fees and maintenance is a dead cost and is added to OpEx. Only a standard-rated letting (e.g. a licensed holiday home operation) recovers it.",
    },

    // ------------------------------------------------- acquisition costs --
    {
      key: "dld_fee_pct",
      label: "DLD transfer fee",
      group: "Acquisition costs",
      type: "percent",
      default: 0.04,
      min: 0,
      max: 0.1,
      help: "Dubai Land Department transfer fee, 4% of the price. There is no annual property tax in Dubai — this one-off is the whole of the transfer taxation.",
    },
    {
      key: "dld_admin_fee",
      label: "DLD administration fee",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 580,
      min: 0,
      help: "Fixed DLD administration charge levied alongside the 4% transfer fee at the trustee office. AED 580 for a property; AED 40 for land.",
    },
    {
      key: "trustee_fee",
      label: "Registration trustee fee",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 4200,
      min: 0,
      help: "Charged by the DLD-appointed registration trustee office at transfer. AED 4,200 including VAT above AED 500,000; AED 2,000 below it.",
    },
    {
      key: "title_deed_fee",
      label: "Title deed issuance",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 580,
      min: 0,
      help: "Charge for issuing the new title deed in the buyer's name once the transfer completes.",
    },
    {
      key: "agency_fee_pct",
      label: "Agency commission",
      group: "Acquisition costs",
      type: "percent",
      default: 0.02,
      min: 0,
      max: 0.06,
      help: "Buyer-side brokerage, market standard 2% plus 5% VAT (VAT added by the model).",
    },
    {
      key: "developer_noc_fee",
      label: "Developer NOC fee",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 2000,
      min: 0,
      max: 20000,
      help: "No Objection Certificate from the developer confirming service charges are clear. AED 500-5,000 depending on the developer; some charge considerably more for villas.",
    },
    {
      key: "valuation_fee",
      label: "Bank valuation",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 3000,
      min: 0,
      help: "AED 2,500-3,500 for a mortgage valuation by a bank-panel valuer.",
    },
    {
      key: "conveyancing_fee",
      label: "Conveyancing",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 8000,
      min: 0,
      help: "AED 6,000-12,000 for a conveyancer to run the Form F, NOC, trustee appointment and transfer.",
    },
    {
      key: "mortgage_reg_pct",
      label: "Mortgage registration",
      group: "Acquisition costs",
      type: "percent",
      default: 0.0025,
      min: 0,
      max: 0.01,
      help: "0.25% of the loan amount registered against the title at the DLD, plus a fixed administration charge.",
    },
    {
      key: "mortgage_admin_fee",
      label: "Mortgage registration admin",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 290,
      min: 0,
      help: "Fixed administration charge the DLD adds to the 0.25% mortgage registration fee when the charge is noted against the title.",
    },
    {
      key: "bank_arrangement_pct",
      label: "Bank arrangement fee",
      group: "Acquisition costs",
      type: "percent",
      default: 0.01,
      min: 0,
      max: 0.03,
      help: "Processing fee at drawdown, typically 0.5-1.0% of the facility.",
    },

    // --------------------------------------------------------- financing --
    {
      key: "buyer_profile",
      label: "Buyer profile",
      group: "Financing",
      type: "select",
      default: "expat_resident",
      options: [
        { value: "expat_resident", label: "Expat resident — first property" },
        { value: "uae_national", label: "UAE national — first property" },
        { value: "second_property", label: "Second or subsequent property" },
        { value: "non_resident", label: "Non-resident" },
        { value: "corporate_spv", label: "Corporate / SPV" },
        { value: "off_plan", label: "Off-plan" },
      ],
      help: "Drives the regulatory LTV ceiling under the UAE Central Bank mortgage regulations. The model caps the requested LTV at the ceiling and flags when it has done so.",
    },
    {
      key: "ltv",
      label: "Loan to value (requested)",
      group: "Financing",
      type: "percent",
      default: 0.6,
      min: 0,
      max: 0.85,
      help: "Requested LTV against the purchase price. Capped at the regulatory ceiling for the selected buyer profile. Set 0 for an all-cash purchase.",
    },
    {
      key: "interest_rate",
      label: "Mortgage rate",
      group: "Financing",
      type: "percent",
      default: 0.0475,
      min: 0,
      max: 0.15,
      help: "All-in annual rate. Use the EIBOR-plus-margin reversion rate rather than a 1-5 year fixed teaser when testing DSCR — UAE lenders stress the reversion, and so should you.",
    },
    {
      key: "loan_term_years",
      label: "Loan tenor",
      group: "Financing",
      type: "integer",
      unit: "years",
      default: 25,
      min: 1,
      max: 25,
      help: "Fully amortising on monthly rests. UAE banks cap residential tenor at 25 years and at age 65 (70 self-employed) at maturity.",
    },
    {
      key: "io_period_years",
      label: "Interest-only period",
      group: "Financing",
      type: "integer",
      unit: "years",
      default: 0,
      min: 0,
      max: 10,
      help: "Years of interest-only before amortisation begins. Genuinely rare in the UAE residential market — default 0. If a lender is offering it, understand why.",
    },
    {
      key: "dscr_covenant",
      label: "DSCR covenant",
      group: "Financing",
      type: "number",
      unit: "x",
      default: 1.25,
      min: 1,
      max: 2,
      help: "Minimum debt service cover the lender requires. UAE banks underwrite investment mortgages to 1.25x.",
    },

    // -------------------------------------------------------------- exit --
    {
      key: "hold_period",
      label: "Hold period",
      group: "Exit",
      type: "integer",
      unit: "years",
      default: 5,
      min: 1,
      max: 15,
      required: true,
      help: "Years to exit. Drives the length of the projection. Five years is the Dubai residential default and roughly matches the fixed-rate reversion point.",
    },
    {
      key: "exit_basis",
      label: "Exit basis",
      group: "Exit",
      type: "select",
      default: "cap_rate",
      options: [
        { value: "cap_rate", label: "Net yield / cap rate on exit-year NOI" },
        { value: "price_psf", label: "Price per sqft" },
      ],
      help: "Cap rate exits are analytically cleaner; price-per-sqft exits are how Dubai residential actually trades. Run both.",
    },
    {
      key: "exit_cap_rate",
      label: "Exit cap rate",
      group: "Exit",
      type: "percent",
      default: 0.055,
      min: 0.02,
      max: 0.15,
      help: "Net yield a buyer will pay on the exit-year NOI. Dubai residential net cap rates run roughly 5.0-5.75% for a well-located apartment at a 7-8% gross yield — do not confuse this with the gross yield the market quotes. Setting it above the going-in cap is the honest default; below it is a bet on yield compression.",
    },
    {
      key: "exit_price_psf",
      label: "Exit price per sqft",
      group: "Exit",
      type: "number",
      unit: "AED/sqft",
      help: "Only used when the exit basis is price per sqft. Left blank deliberately — if you choose that basis you must supply a defensible number, and the model will show a blank rather than invent one.",
    },
    {
      key: "selling_agency_pct",
      label: "Selling agency commission",
      group: "Exit",
      type: "percent",
      default: 0.02,
      min: 0,
      max: 0.06,
      help: "Sell-side brokerage, 2% plus 5% VAT. Note the 4% DLD transfer fee on exit is a BUYER cost in Dubai and is not deducted from the seller's proceeds.",
    },
    {
      key: "exit_costs_other",
      label: "Other exit costs",
      group: "Exit",
      type: "currency",
      unit: "AED",
      default: 5000,
      min: 0,
      help: "Seller-side trustee attendance, developer NOC for the sale, mortgage discharge and conveyancing.",
    },

    // ------------------------------------------------------ tax & returns --
    {
      key: "owner_type",
      label: "Ownership vehicle",
      group: "Tax",
      type: "select",
      default: "individual",
      options: [
        { value: "individual", label: "Natural person (personal capacity)" },
        { value: "uae_mainland_entity", label: "UAE mainland company" },
        { value: "freezone_entity", label: "Free zone entity" },
        { value: "foreign_entity", label: "Foreign entity" },
      ],
      help: "UAE corporate tax is 9% on taxable income above AED 375,000. A natural person earning real estate investment income in a personal capacity is out of scope entirely — no corporate tax and no licensing requirement. Holding through a company brings the income into scope.",
    },
    {
      key: "corporate_tax_rate_input",
      label: "Corporate tax rate",
      group: "Tax",
      type: "percent",
      default: 0.09,
      min: 0,
      max: 0.3,
      help: "UAE headline corporate tax rate, applied only when the ownership vehicle is a company.",
    },
    {
      key: "corporate_tax_threshold",
      label: "Corporate tax threshold",
      group: "Tax",
      type: "currency",
      unit: "AED",
      default: 375000,
      min: 0,
      help: "Taxable income below AED 375,000 is taxed at 0%. Applied per entity, not per property.",
    },
    {
      key: "discount_rate",
      label: "Discount rate",
      group: "Returns",
      type: "percent",
      default: 0.09,
      min: 0,
      max: 0.4,
      help: "Required return used for the NPV and to value the cheque-timing float. Set at the investor's cost of equity, not the mortgage rate.",
    },
  ],

  lines: [
    // ---------------------------------------------------------- headline --
    {
      key: "purchase_price",
      label: "Purchase price",
      group: "Headline",
      formula: "price",
      unit: "AED",
      format: "currency",
      emphasis: "hero",
    },
    {
      key: "price_per_sqft",
      label: "Price per sqft",
      group: "Headline",
      formula: "purchase_price / size_sqft",
      unit: "AED/sqft",
      format: "per_sqft",
      precision: 0,
      emphasis: "hero",
      help: "Benchmark against recent DLD transactions in the same tower or cluster, not the community average.",
    },
    {
      key: "meets_golden_visa",
      label: "Golden Visa eligible",
      group: "Compliance",
      formula: "purchase_price >= 2000000",
      format: "boolean",
      emphasis: "strong",
      help: "AED 2,000,000 or more qualifies the owner for the 10-year renewable UAE Golden Visa, mortgaged and off-plan units included subject to the bank NOC.",
    },
    {
      key: "short_tenure_tail",
      label: "Short tenure tail",
      group: "Compliance",
      formula: 'if(tenure == "freehold", false, tenure_years_remaining < 30)',
      format: "boolean",
      help: "True where a non-freehold interest has under 30 years to run. Most UAE banks will not lend where the unexpired term is less than the tenor plus ten years, which removes the mortgaged buyer pool at exit.",
    },

    // -------------------------------------------------- rent and the cap --
    {
      key: "annual_rent",
      label: "Annual rent (year 1)",
      group: "Income",
      formula: "if(is_vacant, market_rent, in_place_rent)",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "Market rent if the unit is delivered vacant (the first letting is uncapped), otherwise the inherited in-place contract rent.",
    },
    {
      key: "rent_per_sqft",
      label: "Rent per sqft",
      group: "Income",
      formula: "annual_rent / size_sqft",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "index_rent_per_sqft",
      label: "RERA index rent per sqft",
      group: "Income",
      formula: "rera_index_rent / size_sqft",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 0,
    },
    {
      key: "variance_to_index",
      label: "Variance to RERA index",
      group: "Income",
      formula: "(rera_index_rent - annual_rent) / rera_index_rent",
      format: "percent",
      precision: 1,
      emphasis: "strong",
      help: "How far the passing rent sits below the RERA rental index, as a positive percentage. A negative figure means the passing rent is ABOVE the index — no increase is permitted and the tenant may apply to have it reduced.",
    },
    {
      key: "permitted_increase_pct",
      label: "Permitted increase on renewal",
      group: "Income",
      formula:
        "if(variance_to_index <= 10%, 0, if(variance_to_index <= 20%, 5%, if(variance_to_index <= 30%, 10%, if(variance_to_index <= 40%, 15%, 20%))))",
      format: "percent",
      precision: 0,
      emphasis: "hero",
      help: "Decree 43 of 2013. Up to 10% below index: no increase. 11-20% below: 5%. 21-30% below: 10%. 31-40% below: 15%. More than 40% below: 20%. This is the ceiling on the passing rent next year regardless of what the market does.",
    },
    {
      key: "rent_above_index",
      label: "Passing rent above index",
      group: "Income",
      formula: "annual_rent > rera_index_rent",
      format: "boolean",
    },
    {
      key: "renewal_headroom",
      label: "Headroom to index",
      group: "Income",
      formula: "rera_index_rent - annual_rent",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "The absolute gap between passing rent and index. Positive is upside, but it can only be captured in permitted-increase steps over several years.",
    },
    {
      key: "year_one_capped_rent",
      label: "Rent after first permitted increase",
      group: "Income",
      formula: "annual_rent * (1 + permitted_increase_pct)",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "What the passing rent can legally become at the next renewal — the number to test a broker's 'it will re-let at market' claim against.",
    },

    // -------------------------------------------------- cheque structure --
    {
      key: "cheque_advantage_years",
      label: "Cheque timing advantage",
      group: "Income",
      formula: "1 / (2 * cheque_count)",
      unit: "years",
      format: "number",
      precision: 3,
      help: "With N equal instalments paid in advance, each is received on average 1/(2N) of a year before the rent it covers is earned.",
    },
    {
      key: "effective_rent_advantage",
      label: "Value of cheque timing",
      group: "Income",
      formula: "annual_rent * discount_rate * cheque_advantage_years",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Float benefit of receiving rent in advance, valued at the investor's discount rate. The economic reason a landlord will trade headline rent for fewer cheques.",
    },
    {
      key: "effective_rent",
      label: "Effective rent (incl. cheque timing)",
      group: "Income",
      formula: "annual_rent + effective_rent_advantage",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "vacancy_loss",
      label: "Vacancy allowance",
      group: "Income",
      formula: "annual_rent * vacancy_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "bad_debt_loss",
      label: "Bad debt / bounced cheques",
      group: "Income",
      formula: "annual_rent * bad_debt_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "collected_rent",
      label: "Collected rent",
      group: "Income",
      formula: "annual_rent - vacancy_loss - bad_debt_loss",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "effective_gross_income",
      label: "Effective gross income",
      group: "Income",
      formula: "collected_rent + ifnull(other_income, 0) + effective_rent_advantage",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },

    // --------------------------------------------------- operating costs --
    {
      key: "vat_unrecoverable_rate",
      label: "Irrecoverable VAT rate",
      group: "Operating costs",
      formula: 'if(vat_treatment == "exempt_residential", 5%, 0)',
      format: "percent",
      precision: 0,
      help: "5% on a VAT-exempt residential lease, because the exempt supply blocks input VAT recovery. Zero when the letting is standard-rated.",
    },
    {
      key: "budget_psf",
      label: "Service charge budget per sqft (effective)",
      group: "Operating costs",
      formula: "ifnull(service_charge_t12_total / size_sqft, service_charge_budget_psf)",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 2,
      help: "The T12 actual per sqft where a T12 was uploaded, otherwise the Mollak budget rate entered above. Everything downstream uses this, so an uploaded T12 silently but correctly beats the assumption.",
    },
    {
      key: "service_charge_per_sqft",
      label: "Service charge per sqft (all-in)",
      group: "Operating costs",
      formula: "budget_psf * (1 + vat_unrecoverable_rate)",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 2,
      emphasis: "strong",
      help: "Mollak OA budget grossed up for irrecoverable VAT — the real landlord cost, and the figure to benchmark.",
    },
    {
      key: "service_charge_total",
      label: "Service charge",
      group: "Operating costs",
      formula: "service_charge_per_sqft * size_sqft",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "reserve_fund_contribution",
      label: "Reserve fund (memo, inside service charge)",
      group: "Operating costs",
      formula: "budget_psf * size_sqft * reserve_fund_pct_of_sc",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "muted",
      help: "Memo only — this sits inside the OA budget already and is NOT added again. Shown because a reserve fund below 8-10% of budget is the leading indicator of a future special levy.",
    },
    {
      key: "chiller_cost",
      label: "District cooling capacity charge",
      group: "Operating costs",
      formula: 'if(chiller_borne_by == "landlord", chiller_annual_charge * (1 + vat_unrecoverable_rate), 0)',
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Charged only where the landlord carries it. Payable in full even when the unit is vacant, so it does not flex with occupancy.",
    },
    {
      key: "management_fee",
      label: "Property management fee",
      group: "Operating costs",
      formula: "collected_rent * management_fee_pct * (1 + vat_unrecoverable_rate)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "leasing_commission",
      label: "Leasing commission (annualised)",
      group: "Operating costs",
      formula: "annual_rent * leasing_commission_pct * tenant_turnover_rate * (1 + vat_unrecoverable_rate)",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "5% of annual rent on a new letting, scaled by the probability of turnover in any given year.",
    },
    {
      key: "insurance_cost",
      label: "Insurance",
      group: "Operating costs",
      formula: "purchase_price * insurance_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "maintenance_cost",
      label: "Landlord maintenance",
      group: "Operating costs",
      formula: "maintenance_psf * size_sqft * (1 + vat_unrecoverable_rate)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "total_opex",
      label: "Total operating expenses",
      group: "Operating costs",
      formula:
        "service_charge_total + chiller_cost + management_fee + leasing_commission + insurance_cost + maintenance_cost",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "No annual property tax: Dubai does not levy one. The service charge does the work a property tax does elsewhere.",
    },
    {
      key: "opex_ratio",
      label: "OpEx ratio",
      group: "Operating costs",
      formula: "total_opex / effective_gross_income",
      format: "percent",
      precision: 1,
    },
    {
      key: "opex_variance_to_t12",
      label: "Modelled OpEx vs T12 actual",
      group: "Operating costs",
      formula: "if(isnull(t12_opex_total), null, (total_opex - t12_opex_total) / t12_opex_total)",
      format: "percent",
      precision: 1,
      help: "Blank when no T12 has been uploaded. Positive means the model is carrying more cost than the property actually incurred; negative means the build-up is missing something.",
    },
    {
      key: "noi",
      label: "Net operating income",
      group: "Income",
      formula: "effective_gross_income - total_opex",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "hero",
    },
    {
      key: "gross_yield",
      label: "Gross yield",
      group: "Headline",
      formula: "annual_rent / purchase_price",
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "Annual rent over purchase price. Crude but dominant in the local vernacular; every counterparty will quote it.",
    },

    // ------------------------------------------------- acquisition costs --
    {
      key: "max_ltv",
      label: "Regulatory LTV ceiling",
      group: "Financing",
      formula:
        'if(buyer_profile == "uae_national", if(purchase_price <= 5000000, 85%, 70%), if(buyer_profile == "expat_resident", if(purchase_price <= 5000000, 80%, 65%), if(buyer_profile == "second_property", 65%, if(buyer_profile == "non_resident", 60%, if(buyer_profile == "corporate_spv", 65%, 50%)))))',
      format: "percent",
      precision: 0,
      help: "UAE Central Bank mortgage regulation caps. Expat resident 80% under AED 5m / 65% above; UAE national 85% / 70%; second property 65%; non-resident 60%; corporate or SPV 65%; off-plan 50%.",
    },
    {
      key: "ltv_applied",
      label: "LTV applied",
      group: "Financing",
      formula: "min(ltv, max_ltv)",
      format: "percent",
      precision: 1,
      emphasis: "strong",
    },
    {
      key: "loan_amount",
      label: "Loan amount",
      group: "Financing",
      formula: "purchase_price * ltv_applied",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "dld_fee",
      label: "DLD transfer fee",
      group: "Acquisition costs",
      formula: "purchase_price * dld_fee_pct + dld_admin_fee",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "agency_fee",
      label: "Agency commission (incl. VAT)",
      group: "Acquisition costs",
      formula: "purchase_price * agency_fee_pct * 1.05",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "mortgage_registration_fee",
      label: "Mortgage registration",
      group: "Acquisition costs",
      formula: "if(loan_amount > 0, loan_amount * mortgage_reg_pct + mortgage_admin_fee, 0)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "bank_arrangement_fee",
      label: "Bank arrangement fee",
      group: "Acquisition costs",
      formula: "loan_amount * bank_arrangement_pct",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "total_acquisition_costs",
      label: "Total acquisition costs",
      group: "Acquisition costs",
      formula:
        "dld_fee + trustee_fee + title_deed_fee + agency_fee + developer_noc_fee + valuation_fee + conveyancing_fee + mortgage_registration_fee + bank_arrangement_fee",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "acquisition_cost_ratio",
      label: "Acquisition costs as % of price",
      group: "Acquisition costs",
      formula: "total_acquisition_costs / purchase_price",
      format: "percent",
      precision: 2,
      help: "Typically 6.5-7.5% all-in with a mortgage. None of it is recoverable on exit, and it is the reason a two-year flip in Dubai rarely works.",
    },
    {
      key: "all_in_cost",
      label: "All-in cost",
      group: "Acquisition costs",
      formula: "purchase_price + total_acquisition_costs",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "net_yield",
      label: "Net yield",
      group: "Headline",
      formula: "noi / all_in_cost",
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "NOI over all-in cost including the DLD transfer fee. The correct denominator, and the reason this number sits well below the broker's gross yield.",
    },
    {
      key: "equity_required",
      label: "Equity required",
      group: "Financing",
      formula: "all_in_cost - loan_amount",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "Cash to close. UAE banks lend against the price only, so the whole acquisition cost stack is equity.",
    },

    // ------------------------------------------------------------- debt --
    {
      key: "monthly_rate",
      label: "Monthly rate",
      group: "Financing",
      formula: "interest_rate / 12",
      format: "percent",
      precision: 4,
      hidden: true,
    },
    {
      key: "amortising_months",
      label: "Amortising months",
      group: "Financing",
      formula: "max(0, (loan_term_years - io_period_years) * 12)",
      format: "integer",
      hidden: true,
    },
    {
      key: "amortising_debt_service",
      label: "Debt service (amortising)",
      group: "Financing",
      formula: "if(loan_amount > 0, pmt(monthly_rate, amortising_months, loan_amount) * 12, 0)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "interest_only_debt_service",
      label: "Debt service (interest only)",
      group: "Financing",
      formula: "loan_amount * interest_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
      hidden: true,
    },
    {
      key: "annual_debt_service",
      label: "Annual debt service (year 1)",
      group: "Financing",
      formula: "if(io_period_years >= 1, interest_only_debt_service, amortising_debt_service)",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "dscr",
      label: "DSCR (year 1)",
      group: "Financing",
      formula: "if(annual_debt_service > 0, noi / annual_debt_service, null)",
      format: "ratio",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "debt_yield",
      label: "Debt yield",
      group: "Financing",
      formula: "if(loan_amount > 0, noi / loan_amount, null)",
      format: "percent",
      precision: 2,
      help: "NOI over loan. Rate-independent, so it does not flatter the deal when EIBOR falls.",
    },
    {
      key: "negative_leverage",
      label: "Negative leverage",
      group: "Financing",
      formula: "if(loan_amount > 0, gross_yield < interest_rate, false)",
      format: "boolean",
    },
    {
      key: "levered_cash_flow",
      label: "Cash flow after debt service (year 1)",
      group: "Returns",
      formula: "noi - annual_debt_service",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "cash_on_cash",
      label: "Cash-on-cash (year 1)",
      group: "Returns",
      formula: "levered_cash_flow / equity_required",
      format: "percent",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "payback_years",
      label: "Payback period",
      group: "Returns",
      formula: "purchase_price / annual_rent",
      unit: "years",
      format: "years",
      precision: 1,
      emphasis: "hero",
      help: "Years of gross rent to repay the price — the local vernacular and the inverse of the gross yield.",
    },
    {
      key: "net_payback_years",
      label: "Payback period (net of costs)",
      group: "Returns",
      formula: "all_in_cost / noi",
      unit: "years",
      format: "years",
      precision: 1,
    },
    {
      key: "break_even_occupancy",
      label: "Break-even occupancy",
      group: "Returns",
      formula: "(total_opex + annual_debt_service) / (annual_rent + ifnull(other_income, 0))",
      format: "percent",
      precision: 1,
    },

    // -------------------------------------------------------------- tax --
    {
      key: "corporate_tax_rate",
      label: "Corporate tax rate applied",
      group: "Tax",
      formula: 'if(owner_type == "individual", 0, corporate_tax_rate_input)',
      format: "percent",
      precision: 0,
      help: "Zero for a natural person holding in a personal capacity — real estate investment income of an individual is outside the scope of UAE corporate tax. 9% above the threshold for any corporate vehicle.",
    },
    {
      key: "corporate_tax_threshold_applied",
      label: "Corporate tax threshold applied",
      group: "Tax",
      formula: 'if(owner_type == "individual", 0, corporate_tax_threshold)',
      unit: "AED",
      format: "currency",
      precision: 0,
      hidden: true,
    },

    // ------------------------------------------------------------- exit --
    {
      key: "exit_value_indicative",
      label: "Indicative exit value (year 1 basis)",
      group: "Exit",
      formula: 'if(exit_basis == "price_psf", exit_price_psf * size_sqft, noi / exit_cap_rate)',
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Sense check only. The projection computes the exit on the final-year NOI or the supplied exit price per sqft.",
    },
  ],

  projection: {
    years: "hold_period",
    rows: [
      {
        key: "index_rent_year",
        label: "RERA index rent",
        formula: "if(year == 1, rera_index_rent, prev.index_rent_year * (1 + market_rent_growth))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "rent_variance_year",
        label: "Variance to index (opening)",
        formula:
          "if(year == 1, variance_to_index, (index_rent_year - prev.contract_rent_year) / index_rent_year)",
        format: "percent",
        precision: 1,
      },
      {
        key: "permitted_increase_year",
        label: "RERA permitted increase",
        formula:
          "if(rent_variance_year <= 10%, 0, if(rent_variance_year <= 20%, 5%, if(rent_variance_year <= 30%, 10%, if(rent_variance_year <= 40%, 15%, 20%))))",
        format: "percent",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "contract_rent_year",
        label: "Passing rent",
        formula:
          'if(year == 1, annual_rent, if(rent_regime == "relet_at_market", index_rent_year, prev.contract_rent_year * (1 + permitted_increase_year)))',
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "rent_psf_year",
        label: "Passing rent per sqft",
        formula: "contract_rent_year / size_sqft",
        unit: "AED/sqft/yr",
        format: "per_sqft",
        precision: 0,
      },
      {
        key: "vacancy_year",
        label: "Less: vacancy",
        formula: "-contract_rent_year * vacancy_rate",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "bad_debt_year",
        label: "Less: bad debt / bounced cheques",
        formula: "-contract_rent_year * bad_debt_rate",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "collected_rent_year",
        label: "Collected rent",
        formula: "contract_rent_year + vacancy_year + bad_debt_year",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "other_income_year",
        label: "Other income",
        formula: "ifnull(other_income, 0) * pow(1 + market_rent_growth, year - 1)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "cheque_benefit_year",
        label: "Cheque timing benefit",
        formula: "contract_rent_year * discount_rate * cheque_advantage_years",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "egi_year",
        label: "Effective gross income",
        formula: "collected_rent_year + other_income_year + cheque_benefit_year",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "opex_escalator",
        label: "OpEx index (year 1 = 1.00)",
        formula: "pow(1 + opex_growth, year - 1)",
        format: "number",
        precision: 3,
      },
      {
        key: "service_charge_year",
        label: "Less: service charge (Mollak, incl. irrecoverable VAT)",
        formula: "-service_charge_total * opex_escalator",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "chiller_year",
        label: "Less: district cooling capacity charge",
        formula: "0 - chiller_cost * opex_escalator",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "management_fee_year",
        label: "Less: property management fee",
        formula: "-collected_rent_year * management_fee_pct * (1 + vat_unrecoverable_rate)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "leasing_commission_year",
        label: "Less: leasing commission",
        formula:
          "-contract_rent_year * leasing_commission_pct * tenant_turnover_rate * (1 + vat_unrecoverable_rate)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "insurance_year",
        label: "Less: insurance",
        formula: "-insurance_cost * opex_escalator",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "maintenance_year",
        label: "Less: landlord maintenance",
        formula: "-maintenance_cost * opex_escalator",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "total_opex_year",
        label: "Total operating expenses",
        formula:
          "service_charge_year + chiller_year + management_fee_year + leasing_commission_year + insurance_year + maintenance_year",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "noi_year",
        label: "Net operating income",
        formula: "egi_year + total_opex_year",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "hero",
      },
      {
        key: "loan_balance_open",
        label: "Loan balance (opening)",
        formula: "if(year == 1, loan_amount, prev.loan_balance_close)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "loan_balance_close",
        label: "Loan balance (closing)",
        formula:
          "if(loan_amount <= 0, 0, if(year <= io_period_years, loan_amount, balance(monthly_rate, amortising_months, loan_amount, (year - io_period_years) * 12)))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "debt_service_year",
        label: "Less: debt service",
        formula:
          "if(loan_amount <= 0, 0, if(year <= io_period_years, -interest_only_debt_service, -amortising_debt_service))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "principal_year",
        label: "of which principal repaid",
        formula: "loan_balance_open - loan_balance_close",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "interest_year",
        label: "of which interest",
        formula: "-debt_service_year - principal_year",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "dscr_year",
        label: "DSCR",
        formula: "if(loan_amount > 0, noi_year / -debt_service_year, null)",
        format: "ratio",
        precision: 2,
        emphasis: "strong",
      },
      {
        key: "taxable_income_year",
        label: "Taxable income",
        formula: "noi_year - interest_year",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "tax_year",
        label: "Less: UAE corporate tax",
        formula:
          "if(corporate_tax_rate <= 0, 0, -max(0, taxable_income_year - corporate_tax_threshold_applied) * corporate_tax_rate)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "levered_cf_year",
        label: "Levered cash flow (operations)",
        formula: "noi_year + debt_service_year + tax_year",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "exit_gross_value",
        label: "Exit gross value",
        formula:
          'if(year < years, 0, if(exit_basis == "price_psf", exit_price_psf * size_sqft, noi_year / exit_cap_rate))',
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "exit_selling_costs",
        label: "Less: selling costs",
        formula:
          "if(year < years, 0, -(exit_gross_value * selling_agency_pct * 1.05 + exit_costs_other))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "exit_tax",
        label: "Less: tax on gain",
        formula:
          "if(year < years, 0, if(corporate_tax_rate <= 0, 0, -max(0, exit_gross_value + exit_selling_costs - all_in_cost) * corporate_tax_rate))",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "loan_repayment",
        label: "Less: loan repayment",
        formula: "if(year < years, 0, -loan_balance_close)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "net_sale_proceeds",
        label: "Net sale proceeds",
        formula: "exit_gross_value + exit_selling_costs + exit_tax + loan_repayment",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "unlevered_cf_year",
        label: "Unlevered cash flow",
        formula: "noi_year + if(year < years, 0, exit_gross_value + exit_selling_costs)",
        unit: "AED",
        format: "currency",
        precision: 0,
      },
      {
        key: "net_cash_flow_year",
        label: "Net cash flow to equity",
        formula: "levered_cf_year + net_sale_proceeds",
        unit: "AED",
        format: "currency",
        precision: 0,
        emphasis: "hero",
      },
    ],
  },

  returns: [
    {
      key: "exit_value",
      label: "Exit gross value",
      group: "Returns",
      formula: 'series_last("exit_gross_value")',
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "exit_price_per_sqft",
      label: "Exit price per sqft",
      group: "Returns",
      formula: "exit_value / size_sqft",
      unit: "AED/sqft",
      format: "per_sqft",
      precision: 0,
      help: "Implied by the exit basis. Sense-check it against the going-in price per sqft and the community range before believing the IRR.",
    },
    {
      key: "total_distributions",
      label: "Total cash to equity",
      group: "Returns",
      formula: 'series_sum("net_cash_flow_year")',
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "levered_irr",
      label: "Levered IRR",
      group: "Returns",
      formula: 'series_irr("net_cash_flow_year", -equity_required)',
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "Annual cash flows to equity after debt service and tax, plus net sale proceeds in the final year, against the equity cheque at t=0.",
    },
    {
      key: "unlevered_irr",
      label: "Unlevered IRR",
      group: "Returns",
      formula: 'series_irr("unlevered_cf_year", -all_in_cost)',
      format: "percent",
      precision: 2,
      help: "Property-level return on all-in cost, ignoring debt. Compare against the levered IRR to see whether leverage is actually adding anything.",
    },
    {
      key: "equity_multiple",
      label: "Equity multiple",
      group: "Returns",
      formula: "total_distributions / equity_required",
      format: "multiple",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "avg_levered_cash_flow",
      label: "Average annual cash flow",
      group: "Returns",
      formula: 'series_avg("levered_cf_year")',
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "avg_cash_on_cash",
      label: "Average cash-on-cash",
      group: "Returns",
      formula: "avg_levered_cash_flow / equity_required",
      format: "percent",
      precision: 2,
      emphasis: "strong",
    },
    {
      key: "min_levered_cash_flow",
      label: "Worst-year cash flow",
      group: "Returns",
      formula: 'series_min("levered_cf_year")',
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "min_dscr",
      label: "Minimum DSCR",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_min("dscr_year"), null)',
      format: "ratio",
      precision: 2,
      emphasis: "strong",
    },
    {
      key: "peak_dscr",
      label: "Peak DSCR",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_max("dscr_year"), null)',
      format: "ratio",
      precision: 2,
    },
    {
      key: "years_below_covenant",
      label: "Years below DSCR covenant",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_count_below("dscr_year", dscr_covenant), 0)',
      format: "integer",
    },
    {
      key: "npv_at_discount",
      label: "NPV at discount rate",
      group: "Returns",
      formula: 'series_npv("net_cash_flow_year", discount_rate, -equity_required)',
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "terminal_rent_psf",
      label: "Exit-year rent per sqft",
      group: "Returns",
      formula: 'series_last("rent_psf_year")',
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 0,
    },
    {
      key: "terminal_variance_to_index",
      label: "Exit-year variance to index",
      group: "Returns",
      formula: 'series_last("rent_variance_year")',
      format: "percent",
      precision: 1,
      help: "How far below the RERA index the passing rent still sits at exit. A large residual gap is unharvested value the next buyer will pay for — or evidence that the catch-up assumption never worked.",
    },
  ],

  summary: [
    "price_per_sqft",
    "purchase_price",
    "annual_rent",
    "gross_yield",
    "net_yield",
    "service_charge_per_sqft",
    "cash_on_cash",
    "payback_years",
    "dscr",
  ],

  benchmarks: [
    {
      key: "dscr",
      label: "DSCR (year 1)",
      direction: "higher",
      good: 1.35,
      warn: 1.25,
      unit: "x",
      note: "UAE bank covenant on an investment mortgage is 1.25x. 1.35x gives headroom for the EIBOR reversion.",
    },
    {
      key: "min_dscr",
      label: "Minimum DSCR over hold",
      direction: "higher",
      good: 1.35,
      warn: 1.25,
      unit: "x",
    },
    {
      key: "gross_yield",
      label: "Gross yield",
      direction: "higher",
      good: 0.07,
      warn: 0.055,
      note: "Dubai apartments transact at 6-8% gross. Below 5.5% the buyer is paying for growth or a visa, not income.",
    },
    {
      key: "net_yield",
      label: "Net yield",
      direction: "higher",
      good: 0.055,
      warn: 0.04,
      note: "On all-in cost after service charge, vacancy and irrecoverable VAT.",
    },
    {
      key: "cash_on_cash",
      label: "Cash-on-cash (year 1)",
      direction: "higher",
      good: 0.05,
      warn: 0.03,
      note: "Levered cash yield on equity in year one, after full amortisation. A 25-year amortising Dubai mortgage routes most of the spread to principal, so this sits well below the net yield.",
    },
    {
      key: "avg_cash_on_cash",
      label: "Average cash-on-cash",
      direction: "higher",
      good: 0.05,
      warn: 0.03,
    },
    {
      key: "levered_irr",
      label: "Levered IRR",
      direction: "higher",
      good: 0.15,
      warn: 0.11,
      note: "Dubai residential equity is generally underwritten to a mid-teens levered IRR over a five-year hold.",
    },
    {
      key: "equity_multiple",
      label: "Equity multiple",
      direction: "higher",
      good: 1.9,
      warn: 1.5,
      unit: "x",
      note: "Over a five-year hold. Below 1.5x the deal is not paying for the illiquidity.",
    },
    {
      key: "payback_years",
      label: "Payback",
      direction: "lower",
      good: 14,
      warn: 18,
      unit: "years",
    },
    {
      key: "opex_ratio",
      label: "OpEx ratio",
      direction: "lower",
      good: 0.25,
      warn: 0.35,
    },
  ],

  flags: [
    {
      id: "dscr_below_covenant",
      when: "loan_amount > 0 and dscr < dscr_covenant",
      severity: "red",
      title: "Year-one DSCR below the covenant",
      detail:
        "DSCR is {dscr} against a {dscr_covenant}× covenant, on NOI of {noi} and debt service of {annual_debt_service}. UAE lenders will resize the facility or reprice it.",
      metric: "dscr",
      dd: "Ask the lender for its DSCR test basis: stressed at the EIBOR reversion or at the fixed teaser, and struck on gross rent or NOI after service charge?",
    },
    {
      id: "dscr_breach_in_projection",
      when: "loan_amount > 0 and years_below_covenant > 0 and dscr >= dscr_covenant",
      severity: "amber",
      title: "DSCR falls below covenant later in the hold",
      detail:
        "The deal opens above covenant but breaches in {years_below_covenant} of the projected years, with a minimum DSCR of {min_dscr}. Rising OpEx outpaces the RERA-capped rent.",
      metric: "min_dscr",
      dd: "Model the OpEx escalation against the last three years of actual Mollak budgets for this building rather than a general inflation assumption.",
    },
    {
      id: "rent_above_rera_index",
      when: "annual_rent > rera_index_rent * 1.05",
      severity: "red",
      title: "In-place rent is above the RERA index",
      detail:
        "Passing rent of {annual_rent} sits above the index rent of {rera_index_rent} — a variance of {variance_to_index}. No increase is permitted on renewal, and the tenant can apply to the Rental Dispute Centre to have the rent REDUCED to the index level. Underwriting the current rent into perpetuity overstates income.",
      metric: "variance_to_index",
      dd: "Pull the DLD Smart Rental Index for this exact building and unit type, and check whether the seller signed the tenancy at an inflated rent shortly before marketing the unit.",
    },
    {
      id: "rent_far_below_index",
      when: "variance_to_index > 20%",
      severity: "info",
      title: "Reversionary upside, but capped by RERA",
      detail:
        "Passing rent is {variance_to_index} below the RERA index, worth {renewal_headroom} a year at full reversion. The permitted increase this year is only {permitted_increase_pct}, taking rent to {year_one_capped_rent}, and at exit the passing rent is still {terminal_variance_to_index} below index. The upside is real but it arrives in legislated steps over several years, not on the first renewal.",
      metric: "permitted_increase_pct",
      dd: "Confirm the Ejari expiry date and whether the seller has already served the 90-day notice of variation required to change any term on renewal.",
    },
    {
      id: "twelve_cheque_tenant",
      when: "cheque_count >= 12",
      severity: "amber",
      title: "Twelve-cheque tenancy — collection risk",
      detail:
        "The tenancy runs on {cheque_count} cheques, the weakest covenant tier in Dubai. Since the 2022 amendments a bounced cheque is no longer a criminal offence in the UAE — it is civilly enforceable only, through the Rental Dispute Centre, and recovery typically takes months. The bad-debt allowance of {bad_debt_loss} may be light.",
      metric: "bad_debt_loss",
      dd: "Obtain the tenant's salary certificate or trade licence and the payment history on the existing Ejari. Stress the bad-debt allowance to 3-4%.",
    },
    {
      id: "single_cheque_tenant",
      when: "cheque_count <= 1",
      severity: "positive",
      title: "Single-cheque tenancy",
      detail:
        "Rent is paid annually in advance, worth {effective_rent_advantage} of float per year at the {discount_rate} discount rate and removing collection risk for the term.",
      metric: "effective_rent_advantage",
      dd: "Confirm the cheque has cleared and the Ejari is registered for the full term.",
    },
    {
      id: "service_charge_out_of_band",
      when: 'budget_psf > if(property_type == "villa", 8, 25)',
      severity: "amber",
      title: "Service charge above the normal band",
      detail:
        "The Mollak OA budget is {budget_psf} AED/sqft/yr, above the usual band (apartment 10-25, villa 3-8). All-in with irrecoverable VAT that is {service_charge_per_sqft} AED/sqft, or {service_charge_total} a year — {opex_ratio} of effective gross income.",
      metric: "service_charge_per_sqft",
      dd: "Pull three years of Mollak-approved budgets and the OA reserve fund study. A high charge usually means district cooling, an oversized amenity deck, or a reserve fund catching up on deferred work.",
    },
    {
      id: "opex_diverges_from_t12",
      when: "abs(opex_variance_to_t12) > 20%",
      severity: "amber",
      title: "Modelled OpEx diverges from the T12",
      detail:
        "The model carries {total_opex} of operating expenses against a T12 actual of {t12_opex_total}, a variance of {opex_variance_to_t12}. One of the two is wrong, and it changes NOI of {noi} directly.",
      metric: "opex_variance_to_t12",
      dd: "Reconcile the build-up line by line against the T12. The usual culprits are a service charge billed on a different area basis, a management fee inside a related-party invoice, and one-off maintenance sitting in a recurring category.",
    },
    {
      id: "reserve_fund_light",
      when: "reserve_fund_pct_of_sc < 8%",
      severity: "amber",
      title: "Reserve fund contribution below the normal range",
      detail:
        "The reserve fund is {reserve_fund_pct_of_sc} of the OA budget, or {reserve_fund_contribution} a year, against a normal 8-15%. An under-funded reserve on a {building_age_years}-year-old building is a special levy waiting to happen.",
      metric: "reserve_fund_contribution",
      dd: "Request the OA reserve fund study and the last general assembly minutes. Ask whether any capital works have been deferred and what the current fund balance is per unit.",
    },
    {
      id: "building_age_capex_risk",
      when: "building_age_years > 15",
      severity: "amber",
      title: "Building past fifteen years — first-cycle capital works",
      detail:
        "The building is {building_age_years} years old. Dubai towers hit chiller, lift and facade replacement around this point, funded by a reserve top-up or a special levy on owners. The service charge of {service_charge_per_sqft} AED/sqft is likely to step up rather than escalate.",
      metric: "service_charge_per_sqft",
      dd: "Obtain the building condition survey, the reserve fund study, and the OA's forward capital plan. Ask specifically about the chiller plant and the facade.",
    },
    {
      id: "short_tenure_tail",
      when: "short_tenure_tail",
      severity: "red",
      title: "Short tenure tail destroys exit value",
      detail:
        "Tenure is {tenure} with {tenure_years_remaining} years remaining. Most UAE banks will not lend where the unexpired term is under the mortgage tenor plus ten years, so the mortgaged buyer pool disappears well before expiry and the exit assumption of {exit_value} is unlikely to hold.",
      metric: "tenure_years_remaining",
      dd: "Obtain the head lease and check the renewal mechanism, ground rent review and any assignment restriction. Confirm with two UAE banks whether they would lend against this tail.",
    },
    {
      id: "negative_leverage",
      when: "negative_leverage",
      severity: "red",
      title: "Negative leverage",
      detail:
        "Gross yield of {gross_yield} is below the mortgage rate of {interest_rate}. Debt is subtracting from the return on equity — the levered IRR of {levered_irr} against an unlevered {unlevered_irr} is being carried entirely by the exit assumption.",
      metric: "gross_yield",
      dd: "Re-run at zero LTV. If the deal only clears levered, the underwriting rests on capital growth, not income.",
    },
    {
      id: "vacancy_above_norm",
      when: "vacancy_rate > 8%",
      severity: "amber",
      title: "Vacancy assumption above the Dubai residential norm",
      detail:
        "Vacancy is set at {vacancy_rate} against a 5% market norm, costing {vacancy_loss} a year. Break-even occupancy is {break_even_occupancy}.",
      metric: "vacancy_rate",
      dd: "Check actual void history in the building over the last three years and the current absorption rate for this unit type in {community}.",
    },
    {
      id: "price_psf_outside_community_range",
      when:
        "price_per_sqft > community_price_psf_high * 1.1 or price_per_sqft < community_price_psf_low * 0.9",
      severity: "amber",
      title: "Price per sqft outside the community range",
      detail:
        "At {price_per_sqft} AED/sqft the unit sits outside the {community} range of {community_price_psf_low} to {community_price_psf_high}. Either there is something specific about the unit, or the price is wrong.",
      metric: "price_per_sqft",
      dd: "Pull the last twelve months of DLD transactions for the same tower and unit type. Establish whether the variance is floor level, view, layout, or an off-market discount that will not repeat at exit.",
    },
    {
      id: "golden_visa_threshold_bunching",
      when: "purchase_price >= 2000000 and purchase_price < 2300000",
      severity: "info",
      title: "Priced just above the Golden Visa threshold",
      detail:
        "At {purchase_price} the unit sits in the AED 2.0-2.3m band where visa-driven end-user demand bunches. Pricing here is structurally firm and yields structurally suppressed — the gross yield of {gross_yield} reflects a visa premium, not an income premium.",
      metric: "gross_yield",
      dd: "Compare DLD comparables immediately below AED 2m in the same tower. If the discount exceeds 5%, the visa premium is being paid twice: once on entry and again on a thinner exit pool.",
    },
    {
      id: "golden_visa_eligible",
      when: "meets_golden_visa and purchase_price >= 2300000",
      severity: "positive",
      title: "Golden Visa eligible",
      detail:
        "At {purchase_price} the property clears the AED 2,000,000 threshold for the 10-year renewable Golden Visa without sitting in the crowded band immediately above it.",
      metric: "purchase_price",
      dd: "Confirm eligibility with the DLD for the specific unit; mortgaged and off-plan units qualify but need a bank NOC.",
    },
    {
      id: "payback_too_long",
      when: "payback_years > 20",
      severity: "amber",
      title: "Payback beyond twenty years",
      detail:
        "Gross rent repays the price in {payback_years} years ({gross_yield} gross yield). Net of all-in costs the payback is {net_payback_years} years.",
      metric: "payback_years",
      dd: "Establish what is being bought instead of income and price it explicitly. Then test whether the exit at {exit_price_per_sqft} AED/sqft is supported by anything other than momentum.",
    },
    {
      id: "negative_cash_flow_year",
      when: "min_levered_cash_flow < 0",
      severity: "red",
      title: "Negative levered cash flow in at least one year",
      detail:
        "The worst projected year produces {min_levered_cash_flow} of cash flow after debt service and tax, against average annual cash flow of {avg_levered_cash_flow}. The position requires a capital call or a reserve.",
      metric: "min_levered_cash_flow",
      dd: "Size the facility to hold a {dscr_covenant}× cover in every year, or confirm committed sponsor reserves for the shortfall.",
    },
    {
      id: "ltv_capped_by_regulation",
      when: "ltv > max_ltv",
      severity: "amber",
      title: "Requested LTV exceeds the regulatory ceiling",
      detail:
        "The model has capped LTV at {ltv_applied} against a requested {ltv}. The UAE Central Bank ceiling for this buyer profile at this price is {max_ltv}, so the equity cheque rises to {equity_required}.",
      metric: "ltv_applied",
      dd: "Confirm the buyer profile with the lender — first property versus second, resident versus non-resident, and whether the purchase is in personal or corporate name. The distinction is worth 15-20 points of LTV.",
    },
    {
      id: "landlord_carries_chiller",
      when: 'chiller_borne_by == "landlord" and chiller_cost > 0',
      severity: "info",
      title: "Landlord carries the district cooling capacity charge",
      detail:
        "District cooling costs the landlord {chiller_cost} a year. The capacity charge is payable in full whether or not the unit is occupied, so it does not flex with vacancy and it worsens the break-even occupancy of {break_even_occupancy}.",
      metric: "chiller_cost",
      dd: "Obtain the Empower / Emicool / Tabreed account statement and the connected refrigeration tonnage. Check whether the charge can be novated to the tenant on the next renewal.",
    },
    {
      id: "corporate_tax_in_scope",
      when: "corporate_tax_rate > 0",
      severity: "info",
      title: "UAE corporate tax applies to this vehicle",
      detail:
        "Held through a {owner_type}, rental income is within the scope of UAE corporate tax at {corporate_tax_rate} above the AED 375,000 threshold. A natural person holding in a personal capacity would be out of scope entirely.",
      metric: "corporate_tax_rate",
      dd: "Confirm with a UAE tax adviser whether the structure qualifies for free zone Qualifying Income treatment, and whether interest deductibility is restricted under the general interest limitation rule.",
    },
    {
      id: "exit_yield_compression_assumed",
      when: "exit_cap_rate < net_yield",
      severity: "amber",
      title: "Exit assumes yield compression",
      detail:
        "The exit cap rate of {exit_cap_rate} is tighter than the going-in net yield of {net_yield}. Part of the levered IRR of {levered_irr} is a bet on the market repricing, not on operating performance.",
      metric: "exit_cap_rate",
      dd: "Re-run at an exit cap 50bps wider than going-in and confirm the deal still clears the hurdle.",
    },
  ],

  methodology:
    "Rental growth is not assumed; it is legislated. On renewal of a subsisting tenancy the model computes the variance of the passing rent to the RERA rental index and applies the Decree 43/2013 tiers (up to 10% below index: no increase; 11-20%: 5%; 21-30%: 10%; 31-40%: 15%; over 40%: 20%), re-testing the variance every year so a deeply reversionary unit catches up in legislated steps over several years rather than jumping to market. The index itself is grown at the market growth assumption. Selecting the re-let regime lifts the cap, which is the correct treatment only where a tenant genuinely vacates. Income is adjusted for vacancy, a bad-debt allowance for bounced post-dated cheques, and a cheque-timing benefit valued as rent x discount rate x 1/(2N) for N cheques. Operating costs are the Mollak service charge (a landlord cost in residential), district cooling capacity charges where the landlord carries them, management, leasing commission scaled by turnover, insurance and maintenance — all grossed up for the 5% VAT that a VAT-exempt residential landlord cannot recover. There is no annual property tax in Dubai and none is modelled. Yields are struck on all-in cost including the 4% DLD transfer fee. Debt amortises monthly with an optional interest-only period; the exit deducts selling agency and costs but NOT the 4% DLD fee, which is a buyer cost in Dubai. UAE corporate tax is applied only to corporate vehicles, at 9% above AED 375,000, with interest deducted; a natural person holding in a personal capacity is out of scope. What this model does NOT do: it does not model off-plan payment plans or construction risk, does not model a refinance or a rate reset mid-hold, treats the exit cap rate as an input rather than deriving it, applies a single blended tenancy rather than a unit-by-unit rent roll, does not model service-charge special levies as discrete events, and takes the RERA index rent as supplied rather than reading it from the DLD Smart Rental Index. Where a rent roll is uploaded, in-place rent, market rent, area and the cheque count come from it; where a T12 is uploaded, the actual service charge and cooling charge override the per-sqft assumptions and the modelled OpEx is cross-checked against the T12 total. Every figure is only as good as the index rent, the Mollak budget and the price-per-sqft comparables that were fed to it.",
};
