// Dubai residential — quick screen.
//
// The sixty-second pass an acquisitions person makes on a WhatsApp forward:
// price, size, rent, cheques, service charge, and a debt sketch. It answers the
// three questions a Dubai buyer asks first — gross yield, net yield, and how
// many years the rent takes to pay the price back — and it does so on a cost
// base that includes the DLD transfer fee, because a net yield quoted on the
// headline price alone is wrong by roughly 7%.
//
// No projection, no returns stage. If the screen survives, run the full model.

import type { ModelDefinition } from "../../lib/engine/types.ts";

export const dubaiResidentialQuick: ModelDefinition = {
  key: "dubai-residential-quick",
  name: "Dubai Residential — Quick Screen",
  description:
    "Sixty-second screen for a Dubai apartment, villa or townhouse. Gross and net yield, NOI, service charge burden, DSCR, cash-on-cash and payback, on an all-in cost base including DLD and agency fees.",
  // Market KEY, not a display label — the rest of the system matches on it
  // exactly (selfcheck, default-model selection from env.defaultMarket).
  market: "AE",
  currency: "AED",
  depth: "quick",
  assetType: "residential",
  schemaVersion: 1,

  inputs: [
    // ---------------------------------------------------------- property --
    {
      key: "price",
      label: "Purchase price",
      group: "Property",
      type: "currency",
      unit: "AED",
      default: 2200000,
      min: 100000,
      required: true,
      extract: true,
      source: "om",
      help: "Agreed purchase price before any acquisition costs. This is the number on the Form F / MOU, not the all-in cost — DLD and agency fees are added separately below.",
    },
    {
      key: "size_sqft",
      label: "Size",
      group: "Property",
      type: "number",
      unit: "sqft",
      default: 1250,
      min: 200,
      required: true,
      extract: true,
      source: "rent_roll",
      derivedFrom: "size_sqft",
      help: "Net saleable / BUA area from the title deed or Oqood, in square feet. Summed from the rent roll when one is uploaded. Dubai is quoted in sqft throughout; if the OM quotes sqm, multiply by 10.7639.",
    },
    {
      key: "property_type",
      label: "Property type",
      group: "Property",
      type: "select",
      default: "apartment",
      options: [
        { value: "apartment", label: "Apartment" },
        { value: "villa", label: "Villa" },
        { value: "townhouse", label: "Townhouse" },
      ],
      help: "Drives the service-charge sanity band only. Apartments carry the Owners Association budget for lifts, chillers, lobbies and pool; villas are typically master-community charges only and run far lower per sqft.",
    },

    // ------------------------------------------------------------ income --
    {
      key: "contract_rent",
      label: "Annual rent",
      group: "Income",
      type: "currency",
      unit: "AED",
      default: 165000,
      min: 0,
      required: true,
      extract: true,
      source: "rent_roll",
      derivedFrom: "annual_rent",
      help: "Annual rent as a lump sum, the way Dubai quotes it — the headline figure on the Ejari tenancy contract. Summed across units from the rent roll when one is uploaded. Use the in-place contract rent if tenanted, or the achievable market rent if vacant.",
    },
    {
      key: "cheque_count",
      label: "Rent cheques per year",
      group: "Income",
      type: "select",
      default: 4,
      options: [
        { value: 1, label: "1 cheque (annual, in advance)" },
        { value: 2, label: "2 cheques" },
        { value: 4, label: "4 cheques" },
        { value: 6, label: "6 cheques" },
        { value: 12, label: "12 cheques" },
      ],
      extract: true,
      source: "rent_roll",
      derivedFrom: "cheque_count",
      help: "Number of post-dated cheques the tenant hands over at signing. Taken as the modal cheque count across the rent roll when one is uploaded. Fewer cheques means the landlord holds the cash earlier and carries less counterparty risk, but the headline rent achievable is lower. The model prices that timing advantage explicitly.",
    },
    {
      key: "vacancy_rate",
      label: "Vacancy allowance",
      group: "Income",
      type: "percent",
      default: 0.05,
      min: 0,
      max: 0.4,
      source: "assumption",
      help: "Structural vacancy plus re-letting downtime between tenancies. 5% is the Dubai residential norm for a well-located, well-managed unit; use 8-10% for a secondary community or a large unit with a thin tenant pool.",
    },
    {
      key: "bad_debt_rate",
      label: "Bad debt / cheque bounce allowance",
      group: "Income",
      type: "percent",
      default: 0.015,
      min: 0,
      max: 0.2,
      source: "assumption",
      help: "Allowance for bounced post-dated cheques and eviction lag. Since the 2022 amendments a bounced cheque is no longer a criminal offence in the UAE, only civilly enforceable, so recovery is slower and this line is no longer notional.",
    },

    // -------------------------------------------------- operating costs --
    {
      key: "service_charge_budget_psf",
      label: "Service charge (OA budget)",
      group: "Operating costs",
      type: "number",
      unit: "AED/sqft/yr",
      default: 16,
      min: 0,
      max: 80,
      extract: true,
      source: "om",
      help: "Mollak-approved Owners Association budget per sqft per year, before VAT. This is a landlord cost in residential and is not recoverable from the tenant. Typical: apartment 10-25, villa 3-8. It is the dominant OpEx line in almost every Dubai residential deal.",
    },
    {
      key: "management_fee_pct",
      label: "Property management fee",
      group: "Operating costs",
      type: "percent",
      default: 0.06,
      min: 0,
      max: 0.15,
      source: "assumption",
      help: "Fee on collected rent. Dubai residential managing agents charge 5-8% for full management including Ejari, cheque handling and maintenance coordination.",
    },
    {
      key: "vat_treatment",
      label: "VAT treatment",
      group: "Operating costs",
      type: "select",
      default: "exempt_residential",
      options: [
        { value: "exempt_residential", label: "Residential lease — VAT exempt (input VAT NOT recoverable)" },
        { value: "standard_rated", label: "Standard-rated — 5% VAT, input VAT recoverable" },
      ],
      help: "Residential leases in the UAE are VAT exempt. That sounds like a saving but it is a cost: the landlord makes no taxable supply, cannot register a recovery position, and therefore eats the 5% VAT charged on service charges and management fees. The model adds that irrecoverable VAT to OpEx.",
    },

    // ------------------------------------------------------- acquisition --
    {
      key: "dld_fee_pct",
      label: "DLD transfer fee",
      group: "Acquisition costs",
      type: "percent",
      default: 0.04,
      min: 0,
      max: 0.1,
      help: "Dubai Land Department transfer fee, 4% of the purchase price, plus an AED 580 administration charge. Payable by the buyer at the trustee office on transfer. There is no annual property tax in Dubai — this one-off is the whole of it.",
    },
    {
      key: "agency_fee_pct",
      label: "Agency commission",
      group: "Acquisition costs",
      type: "percent",
      default: 0.02,
      min: 0,
      max: 0.06,
      help: "Buyer-side brokerage, market standard 2% of the price plus 5% VAT (VAT is added by the model). Some off-market and developer transactions carry none.",
    },
    {
      key: "other_acquisition_costs",
      label: "Other transaction costs",
      group: "Acquisition costs",
      type: "currency",
      unit: "AED",
      default: 17800,
      min: 0,
      help: "Registration trustee fee ~AED 4,200 incl. VAT (AED 2,000 under AED 500k), title deed issuance ~AED 580, developer NOC AED 500-5,000, valuation AED 2,500-3,500, conveyancing AED 6,000-12,000. Default is a typical AED 17,800 bundle.",
    },

    // --------------------------------------------------------- financing --
    {
      key: "ltv",
      label: "Loan to value",
      group: "Financing",
      type: "percent",
      default: 0.6,
      min: 0,
      max: 0.85,
      help: "Regulatory caps: expat resident 80% under AED 5m / 65% above, UAE national 85% / 70%, second property 60-65%, non-resident 50-60%, corporate or SPV 50-65%, off-plan ~50%. Set 0 for an all-cash purchase.",
    },
    {
      key: "interest_rate",
      label: "Mortgage rate",
      group: "Financing",
      type: "percent",
      default: 0.0475,
      min: 0,
      max: 0.15,
      help: "All-in annual rate. Either a 1-5 year fixed that reverts to EIBOR plus margin, or floating 3M EIBOR plus 1.25-2.50%. Use the reversion rate, not the teaser, when testing DSCR.",
    },
    {
      key: "loan_term_years",
      label: "Loan tenor",
      group: "Financing",
      type: "integer",
      unit: "years",
      default: 25,
      min: 1,
      max: 25,
      help: "Fully amortising, monthly payments. UAE banks cap residential tenor at 25 years and at age 65 (70 for self-employed) at maturity. Interest-only is rare in the UAE residential market.",
    },
  ],

  lines: [
    // ---------------------------------------------------------- headline --
    {
      key: "purchase_price",
      label: "Purchase price",
      group: "Headline",
      formula: "price",
      unit: "AED",
      format: "currency",
      emphasis: "hero",
      help: "The agreed price, carried through as a computed headline so it sits in the KPI band next to the metrics derived from it.",
    },
    {
      key: "price_per_sqft",
      label: "Price per sqft",
      group: "Headline",
      formula: "purchase_price / size_sqft",
      unit: "AED/sqft",
      format: "per_sqft",
      precision: 0,
      emphasis: "hero",
      help: "The single number every Dubai buyer benchmarks first. Compare against recent DLD transactions in the same tower or cluster, not the community average.",
    },
    {
      key: "annual_rent",
      label: "Annual rent",
      group: "Headline",
      formula: "contract_rent",
      unit: "AED",
      format: "currency",
      emphasis: "strong",
    },
    {
      key: "rent_per_sqft",
      label: "Rent per sqft",
      group: "Headline",
      formula: "annual_rent / size_sqft",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 0,
      emphasis: "strong",
      help: "Annual rent divided by area. The cleanest way to test whether a quoted rent is real against the RERA rental index for the building.",
    },
    {
      key: "gross_yield",
      label: "Gross yield",
      group: "Headline",
      formula: "annual_rent / purchase_price",
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "Annual rent divided by purchase price. Analytically crude — it ignores service charge, vacancy and the 4% DLD fee entirely — but it is the dominant local vernacular and every counterparty will quote it, so it is shown first.",
    },

    // ------------------------------------------------- cheque structure --
    {
      key: "cheque_advantage_years",
      label: "Cheque timing advantage",
      group: "Income",
      formula: "1 / (2 * cheque_count)",
      unit: "years",
      format: "number",
      precision: 3,
      help: "With N equal instalments paid in advance, each cheque is received on average 1/(2N) of a year before the rent it covers is earned. One cheque buys half a year of float; twelve cheques buy two weeks.",
    },
    {
      key: "effective_rent_advantage",
      label: "Value of cheque timing",
      group: "Income",
      formula: "annual_rent * interest_rate * cheque_advantage_years",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "The float benefit of receiving rent in advance, valued at the cost of money. This is why a landlord will accept a lower headline rent for one cheque — and the amount by which a 12-cheque tenant should be discounted.",
    },
    {
      key: "effective_rent",
      label: "Effective rent (incl. cheque timing)",
      group: "Income",
      formula: "annual_rent + effective_rent_advantage",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "vacancy_loss",
      label: "Vacancy allowance",
      group: "Income",
      formula: "annual_rent * vacancy_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "bad_debt_loss",
      label: "Bad debt / bounced cheques",
      group: "Income",
      formula: "annual_rent * bad_debt_rate",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "effective_gross_income",
      label: "Effective gross income",
      group: "Income",
      formula: "annual_rent - vacancy_loss - bad_debt_loss + effective_rent_advantage",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },

    // --------------------------------------------------- operating costs --
    {
      key: "vat_unrecoverable_rate",
      label: "Irrecoverable VAT rate",
      group: "Operating costs",
      formula: 'if(vat_treatment == "exempt_residential", 5%, 0)',
      format: "percent",
      precision: 0,
      help: "5% on a residential lease, because the exempt supply blocks input VAT recovery. Zero when the lease is standard-rated and the landlord is VAT registered.",
    },
    {
      key: "service_charge_per_sqft",
      label: "Service charge per sqft (all-in)",
      group: "Operating costs",
      formula: "service_charge_budget_psf * (1 + vat_unrecoverable_rate)",
      unit: "AED/sqft/yr",
      format: "per_sqft",
      precision: 2,
      emphasis: "strong",
      help: "Mollak OA budget per sqft grossed up for irrecoverable VAT — the actual cost to the landlord, which is what should be benchmarked, not the headline budget.",
    },
    {
      key: "service_charge_total",
      label: "Service charge",
      group: "Operating costs",
      formula: "service_charge_per_sqft * size_sqft",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "management_fee",
      label: "Property management fee",
      group: "Operating costs",
      formula: "effective_gross_income * management_fee_pct * (1 + vat_unrecoverable_rate)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "insurance_cost",
      label: "Insurance",
      group: "Operating costs",
      formula: "purchase_price * 0.05%",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Landlord contents and liability cover at 5 basis points of value. Building cover is normally inside the OA budget; the range is 0.03-0.08%.",
    },
    {
      key: "total_opex",
      label: "Total operating expenses",
      group: "Operating costs",
      formula: "service_charge_total + management_fee + insurance_cost",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "opex_ratio",
      label: "OpEx ratio",
      group: "Operating costs",
      formula: "total_opex / effective_gross_income",
      format: "percent",
      precision: 1,
      help: "Dubai apartments typically run 20-30% of EGI, driven almost entirely by the service charge. Above 35% the service charge is doing the underwriting.",
    },
    {
      key: "noi",
      label: "Net operating income",
      group: "Income",
      formula: "effective_gross_income - total_opex",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "hero",
    },

    // ------------------------------------------------------- acquisition --
    {
      key: "loan_amount",
      label: "Loan amount",
      group: "Financing",
      formula: "purchase_price * ltv",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "dld_fee",
      label: "DLD transfer fee",
      group: "Acquisition costs",
      formula: "purchase_price * dld_fee_pct + 580",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "agency_fee",
      label: "Agency commission (incl. VAT)",
      group: "Acquisition costs",
      formula: "purchase_price * agency_fee_pct * 1.05",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "mortgage_registration_fee",
      label: "Mortgage registration",
      group: "Acquisition costs",
      formula: "if(loan_amount > 0, loan_amount * 0.25% + 290, 0)",
      unit: "AED",
      format: "currency",
      precision: 0,
    },
    {
      key: "bank_arrangement_fee",
      label: "Bank arrangement fee",
      group: "Acquisition costs",
      formula: "loan_amount * 1%",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Processing fee charged by UAE banks at drawdown, typically 0.5-1.0% of the facility.",
    },
    {
      key: "total_acquisition_costs",
      label: "Total acquisition costs",
      group: "Acquisition costs",
      formula:
        "dld_fee + agency_fee + mortgage_registration_fee + bank_arrangement_fee + other_acquisition_costs",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "all_in_cost",
      label: "All-in cost",
      group: "Acquisition costs",
      formula: "purchase_price + total_acquisition_costs",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "Price plus every one-off cost of getting the title in your name. This, not the price, is the correct denominator for a net yield.",
    },
    {
      key: "net_yield",
      label: "Net yield",
      group: "Headline",
      formula: "noi / all_in_cost",
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "NOI over all-in cost. The honest number: it carries the service charge, vacancy, irrecoverable VAT and the 4% DLD fee. Expect 150-250bps below the gross yield a broker will quote.",
    },
    {
      key: "equity_required",
      label: "Equity required",
      group: "Financing",
      formula: "all_in_cost - loan_amount",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "Cash to close. Note that UAE banks lend against the price only — the DLD fee, agency commission and bank fees are all cash out of the buyer's pocket.",
    },

    // ---------------------------------------------------------- returns --
    {
      key: "annual_debt_service",
      label: "Annual debt service",
      group: "Financing",
      formula: "if(loan_amount > 0, pmt(interest_rate / 12, loan_term_years * 12, loan_amount) * 12, 0)",
      unit: "AED",
      format: "currency",
      precision: 0,
      help: "Twelve level monthly payments on a fully amortising facility.",
    },
    {
      key: "dscr",
      label: "DSCR",
      group: "Financing",
      formula: "if(annual_debt_service > 0, noi / annual_debt_service, null)",
      format: "ratio",
      precision: 2,
      emphasis: "hero",
      help: "NOI over debt service. UAE banks underwrite to 1.25x minimum on an investment mortgage; below that the facility is resized or declined.",
    },
    {
      key: "debt_yield",
      label: "Debt yield",
      group: "Financing",
      formula: "if(loan_amount > 0, noi / loan_amount, null)",
      format: "percent",
      precision: 2,
      help: "NOI over loan amount — the rate-independent leverage test. Unlike DSCR it does not flatter a deal when rates fall.",
    },
    {
      key: "levered_cash_flow",
      label: "Cash flow after debt service",
      group: "Returns",
      formula: "noi - annual_debt_service",
      unit: "AED",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "cash_on_cash",
      label: "Cash-on-cash return",
      group: "Returns",
      formula: "levered_cash_flow / equity_required",
      format: "percent",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "payback_years",
      label: "Payback period",
      group: "Returns",
      formula: "purchase_price / annual_rent",
      unit: "years",
      format: "years",
      precision: 1,
      emphasis: "hero",
      help: "Years of gross rent to repay the purchase price — the local vernacular, and the arithmetic inverse of the gross yield. Dubai buyers routinely quote a deal as a 'fourteen-year payback'.",
    },
    {
      key: "net_payback_years",
      label: "Payback period (net of costs)",
      group: "Returns",
      formula: "all_in_cost / noi",
      unit: "years",
      format: "years",
      precision: 1,
      help: "All-in cost over NOI. Typically five to eight years longer than the gross payback, and the version worth arguing about.",
    },
    {
      key: "break_even_occupancy",
      label: "Break-even occupancy",
      group: "Returns",
      formula: "(total_opex + annual_debt_service) / annual_rent",
      format: "percent",
      precision: 1,
      help: "The proportion of the year the unit must be let to cover OpEx and debt service. Above 90% there is no room for a single void period.",
    },

    // ------------------------------------------------------- compliance --
    {
      key: "meets_golden_visa",
      label: "Golden Visa eligible",
      group: "Compliance",
      formula: "purchase_price >= 2000000",
      format: "boolean",
      emphasis: "strong",
      help: "Property of AED 2,000,000 or more qualifies the owner for the 10-year renewable UAE Golden Visa, including off-plan and mortgaged units subject to the bank NOC. Worth real money to an end-user buyer and it distorts pricing just above the threshold.",
    },
  ],

  summary: [
    "price_per_sqft",
    "purchase_price",
    "annual_rent",
    "gross_yield",
    "net_yield",
    "service_charge_per_sqft",
    "cash_on_cash",
    "payback_years",
    "dscr",
  ],

  benchmarks: [
    {
      key: "dscr",
      label: "DSCR",
      direction: "higher",
      good: 1.35,
      warn: 1.25,
      unit: "x",
      note: "UAE bank covenant on an investment mortgage is 1.25x. 1.35x gives headroom for the EIBOR reversion.",
    },
    {
      key: "gross_yield",
      label: "Gross yield",
      direction: "higher",
      good: 0.07,
      warn: 0.055,
      note: "Dubai apartments have been transacting at 6-8% gross. Below 5.5% the buyer is paying for capital growth or a Golden Visa, not income.",
    },
    {
      key: "net_yield",
      label: "Net yield",
      direction: "higher",
      good: 0.055,
      warn: 0.04,
      note: "On all-in cost after service charge, vacancy and irrecoverable VAT. 5.5%+ is a good residential result in Dubai.",
    },
    {
      key: "cash_on_cash",
      label: "Cash-on-cash",
      direction: "higher",
      good: 0.05,
      warn: 0.03,
      note: "Levered cash yield on equity in year one. A 25-year amortising Dubai mortgage routes most of the spread to principal, so this sits well below the net yield.",
    },
    {
      key: "payback_years",
      label: "Payback",
      direction: "lower",
      good: 14,
      warn: 18,
      unit: "years",
      note: "Gross rent payback. 14 years is roughly a 7% gross yield.",
    },
    {
      key: "opex_ratio",
      label: "OpEx ratio",
      direction: "lower",
      good: 0.25,
      warn: 0.35,
      note: "Service charge dominates. Above 35% of EGI the OA budget is the deal risk.",
    },
  ],

  flags: [
    {
      id: "dscr_below_covenant",
      when: "loan_amount > 0 and dscr < 1.25",
      severity: "red",
      title: "DSCR below the UAE bank covenant",
      detail:
        "Year-one DSCR is {dscr} against NOI of {noi} and debt service of {annual_debt_service}. UAE lenders underwrite investment mortgages to a 1.25x minimum, so the facility will be resized or the rate repriced.",
      metric: "dscr",
      dd: "Ask the lender for its DSCR test basis — is it stress-tested at the reversion rate or at the fixed teaser, and does it use gross rent or NOI after service charge?",
    },
    {
      id: "negative_leverage",
      when: "loan_amount > 0 and gross_yield < interest_rate",
      severity: "red",
      title: "Negative leverage",
      detail:
        "Gross yield of {gross_yield} is below the mortgage rate of {interest_rate}. Every dirham of debt reduces the return on equity; the deal only works on capital growth.",
      metric: "gross_yield",
      dd: "Model the deal unlevered and at a lower LTV. If it only clears levered, ask what the exit assumption is doing.",
    },
    {
      id: "twelve_cheque_tenant",
      when: "cheque_count >= 12",
      severity: "amber",
      title: "Twelve-cheque tenancy — collection risk",
      detail:
        "The tenancy is on {cheque_count} cheques. Twelve-cheque tenants are the weakest covenant tier in Dubai, and since the 2022 amendments a bounced cheque is no longer a criminal offence in the UAE — it is civilly enforceable only, so recovery runs through the Rental Dispute Centre and takes months.",
      metric: "bad_debt_loss",
      dd: "Obtain the tenant's salary certificate or trade licence and check the payment history on the existing Ejari before relying on the headline rent.",
    },
    {
      id: "single_cheque_tenant",
      when: "cheque_count <= 1",
      severity: "positive",
      title: "Single-cheque tenancy",
      detail:
        "Rent is paid in one cheque in advance, worth {effective_rent_advantage} of float per year at the current cost of money and effectively removing collection risk for the term.",
      metric: "effective_rent_advantage",
      dd: "Confirm the cheque has cleared and the Ejari is registered for the full term.",
    },
    {
      id: "service_charge_out_of_band",
      when: 'service_charge_budget_psf > if(property_type == "villa", 8, 25)',
      severity: "amber",
      title: "Service charge above the normal band",
      detail:
        "The OA budget is {service_charge_budget_psf} AED/sqft/yr, above the usual band for this asset type (apartment 10-25, villa 3-8). All-in with irrecoverable VAT that is {service_charge_per_sqft} AED/sqft, or {service_charge_total} a year.",
      metric: "service_charge_per_sqft",
      dd: "Pull the last three years of Mollak-approved budgets and the OA reserve fund study. A high charge usually means district cooling, a large pool deck, or a reserve fund catching up on deferred work.",
    },
    {
      id: "payback_too_long",
      when: "payback_years > 20",
      severity: "amber",
      title: "Payback beyond twenty years",
      detail:
        "Gross rent repays the price in {payback_years} years, implying a gross yield of {gross_yield}. Net of costs the payback is {net_payback_years} years.",
      metric: "payback_years",
      dd: "Establish what is being bought instead of income — capital growth, a Golden Visa, or an end-user premium — and price it explicitly.",
    },
    {
      id: "golden_visa_eligible",
      when: "meets_golden_visa",
      severity: "positive",
      title: "Golden Visa eligible",
      detail:
        "At {purchase_price} the property clears the AED 2,000,000 threshold for the 10-year renewable Golden Visa.",
      metric: "purchase_price",
      dd: "Confirm eligibility with the DLD for the specific unit — mortgaged and off-plan units qualify but need a bank NOC and a paid-up threshold.",
    },
    {
      id: "golden_visa_threshold_bunching",
      when: "purchase_price >= 2000000 and purchase_price < 2300000",
      severity: "info",
      title: "Priced just above the Golden Visa threshold",
      detail:
        "At {purchase_price} the unit sits in the AED 2.0-2.3m band where visa-driven demand bunches. Pricing in this band is structurally firm and yields structurally suppressed relative to the same unit at AED 1.9m.",
      metric: "gross_yield",
      dd: "Check DLD comparables immediately below AED 2m in the same tower. If the discount is more than 5% the visa premium is being paid twice.",
    },
    {
      id: "negative_cash_flow",
      when: "levered_cash_flow < 0",
      severity: "red",
      title: "Negative cash flow after debt service",
      detail:
        "NOI of {noi} does not cover debt service of {annual_debt_service}; the position bleeds {levered_cash_flow} a year before any capital expenditure.",
      metric: "levered_cash_flow",
      dd: "Size the facility down to a 1.25x DSCR and re-test the equity cheque, or confirm the sponsor has committed reserves for the shortfall.",
    },
    {
      id: "thin_net_yield",
      when: "net_yield < 4%",
      severity: "amber",
      title: "Net yield below 4%",
      detail:
        "Net yield on all-in cost of {all_in_cost} is {net_yield}, against a gross yield of {gross_yield}. The gap is service charge, vacancy, irrecoverable VAT and the 4% DLD fee.",
      metric: "net_yield",
      dd: "Test the deal against a UAE fixed-deposit or sukuk rate. If income is not competitive with cash, the underwriting rests entirely on the exit.",
    },
    {
      id: "break_even_occupancy_high",
      when: "break_even_occupancy > 90%",
      severity: "amber",
      title: "Break-even occupancy above 90%",
      detail:
        "The unit must be let {break_even_occupancy} of the year just to cover OpEx and debt service. A single two-month void turns the year negative.",
      metric: "break_even_occupancy",
      dd: "Check the historic void pattern in the building and the current absorption rate for this unit type in the community.",
    },
  ],

  methodology:
    "A stabilised single-year screen. Rent is taken as an annual lump sum in the Dubai convention and adjusted for a vacancy allowance, a bad-debt allowance covering bounced post-dated cheques, and a cheque-timing benefit valued at the cost of money as rent x rate x 1/(2N) for N cheques. Operating costs are the Mollak service charge (a landlord cost in residential, grossed up for the 5% VAT a VAT-exempt residential landlord cannot recover), a management fee on collected income, and insurance at 5 basis points of value. There is no annual property tax in Dubai and none is modelled. Net yield is struck on all-in cost including the 4% DLD transfer fee, agency commission, trustee, NOC, valuation, conveyancing and bank fees, because a net yield on the headline price alone overstates the return by roughly 7%. Debt is fully amortising on monthly rests. What this model does NOT do: it does not apply the RERA rental-increase cap, does not project forward, does not model an exit or an IRR, does not model district cooling capacity charges, and does not apply UAE corporate tax. Use the full Dubai residential model for any of those. Where a rent roll is uploaded, annual rent, area and the cheque count are taken from it rather than from the defaults. Treat this as a screen, not an underwriting.",
};
