// US multifamily — full underwriting.
//
// The trap this model exists to catch is property tax. In most US jurisdictions
// the assessor reassesses on transfer, at or near the purchase price, so a T12
// that shows the seller's long-held, appeal-suppressed tax bill understates the
// buyer's year-one expense — frequently by enough to move the going-in cap rate
// 40-60 basis points. Every broker's OM carries the seller's number. This model
// computes the reassessed liability from the purchase basis, assessment ratio
// and millage rate, and shows the step-up explicitly.
//
// The second thing it insists on is the difference between physical vacancy and
// economic vacancy. Loss-to-lease, concessions, non-revenue units and bad debt
// are separate lines because they behave differently and they are the lines an
// aggressive seller compresses.

import type { ModelDefinition } from "../../lib/engine/types.ts";

export const usMultifamilyFull: ModelDefinition = {
  key: "us-multifamily-full",
  name: "US Multifamily — Full Underwriting",
  description:
    "Full underwriting for a US multifamily asset. Per-unit rents with loss-to-lease, concessions and economic vacancy, T12 operating expenses with property tax reassessed at the purchase basis, replacement reserves per unit, agency-style debt with an optional interest-only period, going-in and exit cap rates, levered IRR, equity multiple, DSCR and debt yield.",
  market: "US",
  currency: "USD",
  depth: "full",
  assetType: "multifamily",
  schemaVersion: 1,

  inputs: [
    // ---------------------------------------------------------- property --
    {
      key: "price",
      label: "Purchase price",
      group: "Property",
      type: "currency",
      unit: "USD",
      default: 24000000,
      min: 100000,
      required: true,
      extract: true,
      source: "om",
      help: "Contract purchase price before closing costs. Also the assessor's likely new basis in a reassessment-on-transfer state.",
    },
    {
      key: "unit_count",
      label: "Units",
      group: "Property",
      type: "integer",
      default: 150,
      min: 1,
      required: true,
      extract: true,
      source: "rent_roll",
      derivedFrom: "units_count",
      help: "Total units including any employee or model units. Counted from the rent roll when one is uploaded. Non-revenue units are handled separately below so they do not silently inflate gross potential rent.",
    },
    {
      key: "avg_unit_sqft",
      label: "Average unit size",
      group: "Property",
      type: "number",
      unit: "sqft",
      default: 900,
      min: 100,
      extract: true,
      source: "om",
      help: "Average net rentable square feet per unit. Drives rent per square foot, which is the only way to compare a 1BR-heavy property against a 2BR-heavy one.",
    },
    {
      key: "total_rentable_sqft",
      label: "Total rentable area",
      group: "Property",
      type: "number",
      unit: "sqft",
      extract: true,
      source: "rent_roll",
      derivedFrom: "size_sqft",
      help: "Total net rentable square feet. Summed from the rent roll when one is uploaded, and it overrides units times average unit size. No default — left blank, the model multiplies out.",
    },
    {
      key: "year_built",
      label: "Year built",
      group: "Property",
      type: "integer",
      default: 1998,
      min: 1850,
      max: 2100,
      extract: true,
      source: "om",
      help: "Vintage drives the capital plan and the insurance rate. Pre-1980 stock carries plumbing, electrical and cladding exposure; post-2015 stock generally does not yet.",
    },
    {
      key: "submarket",
      label: "Submarket",
      group: "Property",
      type: "text",
      extract: true,
      source: "om",
      help: "MSA and submarket, used in the write-up and to frame the rent and cap rate comparables.",
    },

    // ------------------------------------------------------------ income --
    {
      key: "in_place_rent_per_unit",
      label: "In-place rent per unit",
      group: "Income",
      type: "currency",
      unit: "USD/month",
      default: 1450,
      min: 0,
      required: true,
      extract: true,
      source: "rent_roll",
      help: "Average monthly rent actually contracted across occupied units, from the current rent roll. Not the asking rent and not the trailing-three annualised figure.",
    },
    {
      key: "market_rent_per_unit",
      label: "Market rent per unit",
      group: "Income",
      type: "currency",
      unit: "USD/month",
      default: 1550,
      min: 0,
      required: true,
      extract: true,
      source: "assumption",
      help: "Achievable asking rent today for the same unit mix in the same condition. The gap to in-place rent is the loss-to-lease and it is the most commonly overstated number in a multifamily OM.",
    },
    {
      key: "in_place_rent_total",
      label: "In-place rent (annual total)",
      group: "Income",
      type: "currency",
      unit: "USD",
      extract: true,
      source: "rent_roll",
      derivedFrom: "in_place_rent_total",
      help: "Total annual in-place rent across the rent roll. Overrides the per-unit figure above when present — an actual rent roll beats an average. No default; left blank, the model uses per-unit rent times revenue units.",
    },
    {
      key: "market_rent_total",
      label: "Market rent (annual total)",
      group: "Income",
      type: "currency",
      unit: "USD",
      extract: true,
      source: "rent_roll",
      derivedFrom: "market_rent_total",
      help: "Total annual market rent across the rent roll. Overrides the per-unit market rent when present. No default.",
    },
    {
      key: "physical_vacancy",
      label: "Physical vacancy",
      group: "Income",
      type: "percent",
      default: 0.06,
      min: 0,
      max: 0.5,
      extract: true,
      source: "rent_roll",
      help: "Units vacant as a share of total units. Distinct from economic vacancy, which also carries concessions, bad debt and non-revenue units.",
    },
    {
      key: "concessions_pct",
      label: "Concessions",
      group: "Income",
      type: "percent",
      default: 0.02,
      min: 0,
      max: 0.3,
      extract: true,
      source: "t12",
      help: "Free rent and move-in incentives as a share of gross potential rent. One month free on a twelve-month lease is roughly 8% — check the actual concession log rather than the T12 summary line.",
    },
    {
      key: "bad_debt_pct",
      label: "Bad debt",
      group: "Income",
      type: "percent",
      default: 0.01,
      min: 0,
      max: 0.2,
      extract: true,
      source: "t12",
      help: "Uncollected rent and write-offs as a share of gross potential rent. Look at the trailing three months separately from the trailing twelve — a deteriorating trend is usually hidden by the annual average.",
    },
    {
      key: "non_revenue_units",
      label: "Non-revenue units",
      group: "Income",
      type: "integer",
      default: 1,
      min: 0,
      help: "Model units, employee units and down units. They occupy square footage and generate no rent, and they are frequently left inside gross potential rent in a seller's presentation.",
    },
    {
      key: "other_income_per_unit",
      label: "Other income per unit",
      group: "Income",
      type: "currency",
      unit: "USD/month",
      default: 75,
      min: 0,
      extract: true,
      source: "t12",
      help: "RUBS utility reimbursement, parking, pet rent, storage, application and late fees, per occupied unit per month. Verify RUBS against the actual utility bills — an aggressive RUBS assumption is a classic value-add overstatement.",
    },
    {
      key: "rent_growth",
      label: "Rent growth",
      group: "Income",
      type: "percent",
      default: 0.03,
      min: -0.2,
      max: 0.2,
      help: "Annual growth in market rent. The model also burns off half the loss-to-lease each year, so effective rent growth in the early years is higher than this figure.",
    },
    {
      key: "loss_to_lease_burnoff",
      label: "Loss-to-lease burn-off",
      group: "Income",
      type: "percent",
      default: 0.5,
      min: 0,
      max: 1,
      help: "Share of the remaining gap between in-place and market rent captured each year as leases roll. 0.5 approximates a twelve-month lease term with normal turnover; set lower where the resident base is sticky or rent-regulated.",
    },

    // ------------------------------------------------------ property tax --
    {
      key: "property_tax_t12",
      label: "Property tax (seller T12)",
      group: "Operating expenses",
      type: "currency",
      unit: "USD",
      default: 240000,
      min: 0,
      extract: true,
      source: "t12",
      derivedFrom: "t12_property_tax",
      help: "The seller's trailing-twelve property tax bill, picked up from the T12 tax category when a T12 is uploaded. Almost always understated relative to what the buyer will pay, because it reflects a stale assessed value and any successful appeals the seller has run.",
    },
    {
      key: "reassess_on_sale",
      label: "Reassessed on transfer",
      group: "Operating expenses",
      type: "boolean",
      default: true,
      help: "True in most US jurisdictions: the assessor resets the assessed value at or near the transaction price on transfer. Underwriting the seller's T12 tax bill in a reassessment state is the single most common error in multifamily underwriting and it can move the going-in cap rate 40-60bps.",
    },
    {
      key: "assessment_ratio",
      label: "Assessment ratio",
      group: "Operating expenses",
      type: "percent",
      default: 0.9,
      min: 0,
      max: 1.5,
      help: "Assessed value as a share of market value. Varies widely by state — 100% in some, statutory fractions elsewhere, and often lower in practice than the statute implies.",
    },
    {
      key: "millage_rate",
      label: "Millage / effective tax rate",
      group: "Operating expenses",
      type: "percent",
      default: 0.0185,
      min: 0,
      max: 0.1,
      help: "Combined county, city, school and special district rate applied to assessed value. Get the actual parcel millage from the assessor rather than an MSA average.",
    },

    // -------------------------------------------------- operating expenses --
    {
      key: "payroll_per_unit",
      label: "Payroll",
      group: "Operating expenses",
      type: "currency",
      unit: "USD/unit/yr",
      default: 1100,
      min: 0,
      extract: true,
      source: "t12",
      help: "On-site management, leasing and maintenance staff including benefits and payroll taxes. Below about 100 units the per-unit figure rises sharply because the staffing model cannot flex.",
    },
    {
      key: "repairs_per_unit",
      label: "Repairs and maintenance",
      group: "Operating expenses",
      type: "currency",
      unit: "USD/unit/yr",
      default: 750,
      min: 0,
      extract: true,
      source: "t12",
      help: "Turn costs, make-ready, and routine repairs. Check what the seller has capitalised — an unusually low R&M line usually means turns were being run through the capital budget.",
    },
    {
      key: "utilities_per_unit",
      label: "Utilities",
      group: "Operating expenses",
      type: "currency",
      unit: "USD/unit/yr",
      default: 620,
      min: 0,
      extract: true,
      source: "t12",
      help: "Gross utility cost borne by the property before RUBS reimbursement, which sits in other income.",
    },
    {
      key: "contract_services_per_unit",
      label: "Contract services",
      group: "Operating expenses",
      type: "currency",
      unit: "USD/unit/yr",
      default: 380,
      min: 0,
      extract: true,
      source: "t12",
      help: "Landscaping, pest, pool, trash, elevator and security contracts.",
    },
    {
      key: "marketing_per_unit",
      label: "Marketing",
      group: "Operating expenses",
      type: "currency",
      unit: "USD/unit/yr",
      default: 190,
      min: 0,
      extract: true,
      source: "t12",
      help: "ILS listings, referral fees and advertising. Rises sharply in a lease-up or a heavy-concession market.",
    },
    {
      key: "admin_per_unit",
      label: "General and administrative",
      group: "Operating expenses",
      type: "currency",
      unit: "USD/unit/yr",
      default: 320,
      min: 0,
      extract: true,
      source: "t12",
      help: "Office, legal, eviction, credit screening, software and licences.",
    },
    {
      key: "insurance_per_unit",
      label: "Insurance",
      group: "Operating expenses",
      type: "currency",
      unit: "USD/unit/yr",
      default: 650,
      min: 0,
      extract: true,
      source: "t12",
      help: "Property and liability. In coastal, wildfire and hail-exposed markets this line has repriced 50-200% since 2021 — never inherit the seller's premium without a fresh quote.",
    },
    {
      key: "management_fee_pct",
      label: "Property management fee",
      group: "Operating expenses",
      type: "percent",
      default: 0.03,
      min: 0,
      max: 0.1,
      help: "Third-party management fee on effective gross income. US multifamily runs 2.5-4% depending on size; a 2% fee in an OM usually means an affiliate manager, and a lender will underwrite a market fee regardless.",
    },
    {
      key: "replacement_reserves_per_unit",
      label: "Replacement reserves",
      group: "Operating expenses",
      type: "currency",
      unit: "USD/unit/yr",
      default: 300,
      min: 0,
      help: "Below-the-line capital reserve. Agency lenders require $250-350 per unit per year on stabilised stock and more on older vintage. Deducted in arriving at NOI here, which is the conservative treatment and the one a lender will use.",
    },
    {
      key: "t12_opex_total",
      label: "Total OpEx (T12 actual)",
      group: "Operating expenses",
      type: "currency",
      unit: "USD",
      extract: true,
      source: "t12",
      derivedFrom: "t12_opex_total",
      help: "Total annualised recurring operating expenses from the T12, used as a cross-check against the model's own per-unit build-up. It feeds no calculation. Note the T12 will not contain replacement reserves — those are a below-the-line underwriting item, not an operating expense the seller incurred.",
    },
    {
      key: "opex_growth",
      label: "OpEx growth",
      group: "Operating expenses",
      type: "percent",
      default: 0.03,
      min: -0.1,
      max: 0.2,
      help: "Applied to all controllable expenses. Property tax grows separately at the assessment growth rate below, and insurance often needs its own, higher, assumption.",
    },
    {
      key: "tax_growth",
      label: "Assessed value growth",
      group: "Operating expenses",
      type: "percent",
      default: 0.03,
      min: -0.1,
      max: 0.2,
      help: "Annual growth in the assessed value after the reassessment. Several states cap this statutorily; check the parcel's jurisdiction before accepting the default.",
    },

    // ------------------------------------------------------ capital costs --
    {
      key: "closing_costs_pct",
      label: "Closing costs",
      group: "Acquisition costs",
      type: "percent",
      default: 0.02,
      min: 0,
      max: 0.08,
      help: "Title, escrow, transfer tax, survey, legal, third-party reports and acquisition fee, as a share of price. Transfer tax alone ranges from nothing to over 2% depending on the jurisdiction.",
    },
    {
      key: "loan_fee_pct",
      label: "Loan origination fee",
      group: "Acquisition costs",
      type: "percent",
      default: 0.01,
      min: 0,
      max: 0.05,
      help: "Origination plus lender legal and third-party costs, as a share of the loan amount.",
    },
    {
      key: "capex_budget_per_unit",
      label: "Upfront capital budget",
      group: "Acquisition costs",
      type: "currency",
      unit: "USD/unit",
      default: 0,
      min: 0,
      help: "Day-one capital plan per unit, funded from equity at closing. Set above zero for a value-add business plan; the interior scope should tie to the rent premium assumed in market rent.",
    },

    // --------------------------------------------------------- financing --
    {
      key: "ltv",
      label: "Loan to value",
      group: "Financing",
      type: "percent",
      default: 0.6,
      min: 0,
      max: 0.85,
      help: "Requested proceeds against price. Agency debt reaches 65-75% on stabilised stock but is usually constrained by the DSCR and debt yield tests before it reaches the LTV cap.",
    },
    {
      key: "interest_rate",
      label: "Interest rate",
      group: "Financing",
      type: "percent",
      default: 0.058,
      min: 0,
      max: 0.15,
      help: "All-in coupon. For agency debt this is the index plus the guaranty fee and servicing spread.",
    },
    {
      key: "amort_years",
      label: "Amortisation",
      group: "Financing",
      type: "integer",
      unit: "years",
      default: 30,
      min: 1,
      max: 40,
      help: "Amortisation schedule, usually 30 years on agency debt regardless of the loan term.",
    },
    {
      key: "io_period_years",
      label: "Interest-only period",
      group: "Financing",
      type: "integer",
      unit: "years",
      default: 2,
      min: 0,
      max: 10,
      help: "Years of interest-only before amortisation begins. Common on agency and bridge debt, and it materially flatters early cash-on-cash — check what the return looks like after it burns off.",
    },
    {
      key: "dscr_covenant",
      label: "DSCR covenant",
      group: "Financing",
      type: "number",
      unit: "x",
      default: 1.25,
      min: 1,
      max: 2.5,
      help: "Agency minimum is typically 1.25x on a fixed-rate stabilised loan; bridge lenders test lower going in but require a stabilised exit test.",
    },

    // -------------------------------------------------------------- exit --
    {
      key: "hold_period",
      label: "Hold period",
      group: "Exit",
      type: "integer",
      unit: "years",
      default: 5,
      min: 1,
      max: 15,
      required: true,
      help: "Years to exit. Drives the length of the pro forma. Five years is the standard US multifamily syndication hold and usually matches the loan term or the interest-only burn-off plus stabilisation.",
    },
    {
      key: "exit_cap_rate",
      label: "Exit cap rate",
      group: "Exit",
      type: "percent",
      default: 0.06,
      min: 0.02,
      max: 0.15,
      help: "Applied to the exit-year NOI. Convention is to set this at least 25-50bps above the going-in cap to reflect the asset being five years older; setting it below going-in is an explicit bet on cap rate compression.",
    },
    {
      key: "selling_costs_pct",
      label: "Selling costs",
      group: "Exit",
      type: "percent",
      default: 0.02,
      min: 0,
      max: 0.06,
      help: "Disposition brokerage, transfer tax where seller-paid, legal and closing.",
    },
    {
      key: "discount_rate",
      label: "Discount rate",
      group: "Returns",
      type: "percent",
      default: 0.1,
      min: 0,
      max: 0.4,
      help: "Required return used for the NPV. Set at the sponsor's cost of equity.",
    },
  ],

  lines: [
    // ---------------------------------------------------------- headline --
    {
      key: "purchase_price",
      label: "Purchase price",
      group: "Headline",
      formula: "price",
      unit: "USD",
      format: "currency",
      emphasis: "hero",
    },
    {
      key: "price_per_unit",
      label: "Price per unit",
      group: "Headline",
      formula: "purchase_price / unit_count",
      unit: "USD/unit",
      format: "currency",
      precision: 0,
      emphasis: "hero",
    },
    {
      key: "total_sqft",
      label: "Total rentable area",
      group: "Property",
      formula: "ifnull(total_rentable_sqft, unit_count * avg_unit_sqft)",
      unit: "sqft",
      format: "number",
      precision: 0,
    },
    {
      key: "price_per_sqft",
      label: "Price per sqft",
      group: "Headline",
      formula: "purchase_price / total_sqft",
      unit: "USD/sqft",
      format: "per_sqft",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "building_age_years",
      label: "Building age",
      group: "Property",
      formula: "2026 - year_built",
      unit: "years",
      format: "integer",
    },

    // ------------------------------------------------------------ income --
    {
      key: "revenue_units",
      label: "Revenue units",
      group: "Income",
      formula: "unit_count - ifnull(non_revenue_units, 0)",
      format: "integer",
      help: "Units capable of producing rent, after model, employee and down units.",
    },
    {
      key: "in_place_rent_pu",
      label: "In-place rent per unit (effective)",
      group: "Income",
      formula: "ifnull(in_place_rent_total / 12 / revenue_units, in_place_rent_per_unit)",
      unit: "USD/month",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "The rent roll total spread over revenue units where a rent roll was uploaded, otherwise the per-unit figure entered above. Everything downstream uses this.",
    },
    {
      key: "market_rent_pu",
      label: "Market rent per unit (effective)",
      group: "Income",
      formula: "ifnull(market_rent_total / 12 / revenue_units, market_rent_per_unit)",
      unit: "USD/month",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "gross_potential_rent",
      label: "Gross potential rent",
      group: "Income",
      formula: "market_rent_pu * 12 * revenue_units",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "Every revenue unit let at market rent for twelve months. The top of the income waterfall — everything below it is a deduction.",
    },
    {
      key: "loss_to_lease",
      label: "Less: loss to lease",
      group: "Income",
      formula: "(market_rent_pu - in_place_rent_pu) * 12 * revenue_units",
      unit: "USD",
      format: "currency",
      precision: 0,
      help: "The gap between market and in-place rent across the rent roll. Positive means the property is under-rented and the gap can be captured as leases roll; negative means in-place rents are above market and will fall.",
    },
    {
      key: "loss_to_lease_pct",
      label: "Loss to lease",
      group: "Income",
      formula: "loss_to_lease / gross_potential_rent",
      format: "percent",
      precision: 1,
      emphasis: "strong",
      help: "As a share of gross potential rent. Above 10% on a stabilised property, ask why the manager has not been pushing rents — the answer is usually that market rent is not what the OM says it is.",
    },
    {
      key: "in_place_rental_income",
      label: "In-place rental income",
      group: "Income",
      formula: "gross_potential_rent - loss_to_lease",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "vacancy_loss",
      label: "Less: physical vacancy",
      group: "Income",
      formula: "in_place_rental_income * physical_vacancy",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "concessions_loss",
      label: "Less: concessions",
      group: "Income",
      formula: "gross_potential_rent * concessions_pct",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "bad_debt_loss",
      label: "Less: bad debt",
      group: "Income",
      formula: "gross_potential_rent * bad_debt_pct",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "non_revenue_loss",
      label: "Less: non-revenue units",
      group: "Income",
      formula: "market_rent_pu * 12 * ifnull(non_revenue_units, 0)",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "net_rental_income",
      label: "Net rental income",
      group: "Income",
      formula: "in_place_rental_income - vacancy_loss - concessions_loss - bad_debt_loss",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "economic_vacancy",
      label: "Economic vacancy",
      group: "Income",
      formula:
        "(loss_to_lease + vacancy_loss + concessions_loss + bad_debt_loss + non_revenue_loss) / gross_potential_rent",
      format: "percent",
      precision: 1,
      emphasis: "strong",
      help: "Total leakage from gross potential rent, including loss to lease, physical vacancy, concessions, bad debt and non-revenue units. Routinely double the physical vacancy figure quoted in an OM, and it is the number that actually determines collections.",
    },
    {
      key: "other_income",
      label: "Other income",
      group: "Income",
      formula: "other_income_per_unit * 12 * revenue_units * (1 - physical_vacancy)",
      unit: "USD",
      format: "currency",
      precision: 0,
      help: "RUBS, parking, pet and fee income, earned only on occupied units.",
    },
    {
      key: "effective_gross_income",
      label: "Effective gross income",
      group: "Income",
      formula: "net_rental_income + other_income",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },

    // -------------------------------------------------------- expenses --
    {
      key: "assessed_value",
      label: "Reassessed value",
      group: "Operating expenses",
      formula: "purchase_price * assessment_ratio",
      unit: "USD",
      format: "currency",
      precision: 0,
      help: "The assessor's likely new basis: purchase price times the assessment ratio.",
    },
    {
      key: "property_tax_reassessed",
      label: "Property tax (reassessed)",
      group: "Operating expenses",
      formula: "assessed_value * millage_rate",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "property_tax",
      label: "Property tax (underwritten)",
      group: "Operating expenses",
      formula: "if(reassess_on_sale, property_tax_reassessed, property_tax_t12)",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "The number actually used. Where the jurisdiction reassesses on transfer, this is the reassessed liability, not the seller's T12 bill.",
    },
    {
      key: "property_tax_step_up",
      label: "Property tax step-up vs T12",
      group: "Operating expenses",
      formula: "property_tax - property_tax_t12",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
      help: "How much the tax bill rises on transfer. Divide by the going-in cap rate to see how much value the seller's T12 was quietly claiming.",
    },
    {
      key: "property_tax_step_up_pct",
      label: "Property tax step-up",
      group: "Operating expenses",
      formula: "property_tax_step_up / property_tax_t12",
      format: "percent",
      precision: 1,
    },
    {
      key: "insurance_cost",
      label: "Insurance",
      group: "Operating expenses",
      formula: "insurance_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "payroll_cost",
      label: "Payroll",
      group: "Operating expenses",
      formula: "payroll_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "repairs_cost",
      label: "Repairs and maintenance",
      group: "Operating expenses",
      formula: "repairs_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "utilities_cost",
      label: "Utilities",
      group: "Operating expenses",
      formula: "utilities_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "contract_services_cost",
      label: "Contract services",
      group: "Operating expenses",
      formula: "contract_services_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "marketing_cost",
      label: "Marketing",
      group: "Operating expenses",
      formula: "marketing_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "admin_cost",
      label: "General and administrative",
      group: "Operating expenses",
      formula: "admin_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "management_fee",
      label: "Property management fee",
      group: "Operating expenses",
      formula: "effective_gross_income * management_fee_pct",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "replacement_reserves",
      label: "Replacement reserves",
      group: "Operating expenses",
      formula: "replacement_reserves_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "controllable_opex",
      label: "Controllable operating expenses",
      group: "Operating expenses",
      formula:
        "payroll_cost + repairs_cost + utilities_cost + contract_services_cost + marketing_cost + admin_cost + management_fee",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "total_opex",
      label: "Total operating expenses",
      group: "Operating expenses",
      formula: "controllable_opex + property_tax + insurance_cost + replacement_reserves",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "opex_per_unit",
      label: "OpEx per unit",
      group: "Operating expenses",
      formula: "total_opex / unit_count",
      unit: "USD/unit/yr",
      format: "currency",
      precision: 0,
      help: "US multifamily typically runs $4,500-7,500 per unit per year all-in. Well below that range on older stock in a high-tax state is a red flag on the expense assumptions.",
    },
    {
      key: "opex_ratio",
      label: "OpEx ratio",
      group: "Operating expenses",
      formula: "total_opex / effective_gross_income",
      format: "percent",
      precision: 1,
      help: "Stabilised US multifamily typically runs 38-50% of EGI including taxes, insurance and reserves.",
    },
    {
      key: "opex_variance_to_t12",
      label: "Modelled OpEx vs T12 actual",
      group: "Operating expenses",
      formula:
        "if(isnull(t12_opex_total), null, (total_opex - replacement_reserves - t12_opex_total) / t12_opex_total)",
      format: "percent",
      precision: 1,
      help: "Compared excluding replacement reserves, which are an underwriting item and will not appear in a seller's T12. Blank when no T12 has been uploaded.",
    },
    {
      key: "noi",
      label: "Net operating income",
      group: "Income",
      formula: "effective_gross_income - total_opex",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "hero",
      help: "After replacement reserves, which is the conservative convention and the one an agency lender will apply.",
    },

    // ------------------------------------------------------ capitalisation --
    {
      key: "closing_costs",
      label: "Closing costs",
      group: "Acquisition costs",
      formula: "purchase_price * closing_costs_pct",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "loan_amount",
      label: "Loan amount",
      group: "Financing",
      formula: "purchase_price * ltv",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "loan_fee",
      label: "Loan origination fee",
      group: "Acquisition costs",
      formula: "loan_amount * loan_fee_pct",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "upfront_capex",
      label: "Upfront capital budget",
      group: "Acquisition costs",
      formula: "capex_budget_per_unit * unit_count",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "total_acquisition_costs",
      label: "Total acquisition costs",
      group: "Acquisition costs",
      formula: "closing_costs + loan_fee + upfront_capex",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "all_in_cost",
      label: "All-in cost",
      group: "Acquisition costs",
      formula: "purchase_price + total_acquisition_costs",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "equity_required",
      label: "Equity required",
      group: "Financing",
      formula: "all_in_cost - loan_amount",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "gross_yield",
      label: "Gross yield",
      group: "Headline",
      formula: "in_place_rental_income / purchase_price",
      format: "percent",
      precision: 2,
      emphasis: "strong",
      help: "In-place rental income over price. Crude, but it is the fastest way to see whether the price is anywhere near the income before the expense debate starts.",
    },
    {
      key: "going_in_cap_rate",
      label: "Going-in cap rate",
      group: "Headline",
      formula: "noi / purchase_price",
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "NOI over purchase price, after reassessed property tax and replacement reserves. Compare against the broker's quoted cap, which will be struck on the seller's tax bill and usually before reserves.",
    },
    {
      key: "net_yield",
      label: "Net yield (on all-in cost)",
      group: "Headline",
      formula: "noi / all_in_cost",
      format: "percent",
      precision: 2,
      emphasis: "hero",
      help: "NOI over price plus closing costs, loan fees and the day-one capital budget. The yield the equity actually earns.",
    },
    {
      key: "rent_per_sqft",
      label: "Rent per sqft",
      group: "Headline",
      formula: "in_place_rent_pu * 12 * revenue_units / total_sqft",
      unit: "USD/sqft/yr",
      format: "per_sqft",
      precision: 2,
    },

    // ------------------------------------------------------------- debt --
    {
      key: "monthly_rate",
      label: "Monthly rate",
      group: "Financing",
      formula: "interest_rate / 12",
      format: "percent",
      precision: 4,
      hidden: true,
    },
    {
      key: "amortising_months",
      label: "Amortising months",
      group: "Financing",
      formula: "amort_years * 12",
      format: "integer",
      hidden: true,
    },
    {
      key: "amortising_debt_service",
      label: "Debt service (amortising)",
      group: "Financing",
      formula: "if(loan_amount > 0, pmt(monthly_rate, amortising_months, loan_amount) * 12, 0)",
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "interest_only_debt_service",
      label: "Debt service (interest only)",
      group: "Financing",
      formula: "loan_amount * interest_rate",
      unit: "USD",
      format: "currency",
      precision: 0,
      hidden: true,
    },
    {
      key: "annual_debt_service",
      label: "Annual debt service (year 1)",
      group: "Financing",
      formula: "if(io_period_years >= 1, interest_only_debt_service, amortising_debt_service)",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "stabilised_debt_service",
      label: "Debt service after IO burn-off",
      group: "Financing",
      formula: "amortising_debt_service",
      unit: "USD",
      format: "currency",
      precision: 0,
      help: "What the payment becomes once the interest-only period ends. Test the DSCR against this, not against the IO payment.",
    },
    {
      key: "dscr",
      label: "DSCR (year 1)",
      group: "Financing",
      formula: "if(annual_debt_service > 0, noi / annual_debt_service, null)",
      format: "ratio",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "dscr_amortising",
      label: "DSCR (fully amortising)",
      group: "Financing",
      formula: "if(amortising_debt_service > 0, noi / amortising_debt_service, null)",
      format: "ratio",
      precision: 2,
      emphasis: "strong",
      help: "The test that matters once interest-only burns off. An agency lender sizes on this figure, not on the IO payment.",
    },
    {
      key: "debt_yield",
      label: "Debt yield",
      group: "Financing",
      formula: "if(loan_amount > 0, noi / loan_amount, null)",
      format: "percent",
      precision: 2,
      emphasis: "strong",
      help: "NOI over loan amount. The rate-independent leverage test agency and CMBS lenders size to — typically 8-10% minimum.",
    },
    {
      key: "negative_leverage",
      label: "Negative leverage",
      group: "Financing",
      formula: "if(loan_amount > 0, going_in_cap_rate < interest_rate, false)",
      format: "boolean",
    },
    {
      key: "levered_cash_flow",
      label: "Cash flow after debt service (year 1)",
      group: "Returns",
      formula: "noi - annual_debt_service",
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "cash_on_cash",
      label: "Cash-on-cash (year 1)",
      group: "Returns",
      formula: "levered_cash_flow / equity_required",
      format: "percent",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "payback_years",
      label: "Payback period",
      group: "Returns",
      formula: "all_in_cost / noi",
      unit: "years",
      format: "years",
      precision: 1,
      help: "All-in cost over NOI — the inverse of the net yield.",
    },
    {
      key: "break_even_occupancy",
      label: "Break-even occupancy",
      group: "Returns",
      formula: "(total_opex + annual_debt_service) / (gross_potential_rent + other_income)",
      format: "percent",
      precision: 1,
    },
  ],

  projection: {
    years: "hold_period",
    rows: [
      {
        key: "market_rent_year",
        label: "Market rent per unit (monthly)",
        formula: "market_rent_pu * pow(1 + rent_growth, year - 1)",
        unit: "USD/month",
        format: "currency",
        precision: 0,
      },
      {
        key: "in_place_rent_year",
        label: "In-place rent per unit (monthly)",
        formula:
          "if(year == 1, in_place_rent_pu, min(market_rent_year, prev.in_place_rent_year * (1 + rent_growth) + (market_rent_year - prev.in_place_rent_year * (1 + rent_growth)) * loss_to_lease_burnoff))",
        unit: "USD/month",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "gpr_year",
        label: "Gross potential rent",
        formula: "market_rent_year * 12 * revenue_units",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "loss_to_lease_year",
        label: "Less: loss to lease",
        formula: "0 - (market_rent_year - in_place_rent_year) * 12 * revenue_units",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "vacancy_loss_year",
        label: "Less: physical vacancy",
        formula: "-in_place_rent_year * 12 * revenue_units * physical_vacancy",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "concessions_year",
        label: "Less: concessions",
        formula: "-gpr_year * concessions_pct",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "bad_debt_year",
        label: "Less: bad debt",
        formula: "-gpr_year * bad_debt_pct",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "net_rental_income_year",
        label: "Net rental income",
        formula: "gpr_year + loss_to_lease_year + vacancy_loss_year + concessions_year + bad_debt_year",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "other_income_year",
        label: "Other income",
        formula:
          "other_income_per_unit * 12 * revenue_units * (1 - physical_vacancy) * pow(1 + rent_growth, year - 1)",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "egi_year",
        label: "Effective gross income",
        formula: "net_rental_income_year + other_income_year",
        unit: "USD",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "opex_escalator",
        label: "OpEx index (year 1 = 1.00)",
        formula: "pow(1 + opex_growth, year - 1)",
        format: "number",
        precision: 3,
      },
      {
        key: "property_tax_year",
        label: "Less: property tax",
        formula: "-property_tax * pow(1 + tax_growth, year - 1)",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "insurance_year",
        label: "Less: insurance",
        formula: "-insurance_cost * opex_escalator",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "controllable_opex_year",
        label: "Less: controllable operating expenses",
        formula:
          "-(payroll_cost + repairs_cost + utilities_cost + contract_services_cost + marketing_cost + admin_cost) * opex_escalator - egi_year * management_fee_pct",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "reserves_year",
        label: "Less: replacement reserves",
        formula: "-replacement_reserves * opex_escalator",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "total_opex_year",
        label: "Total operating expenses",
        formula: "property_tax_year + insurance_year + controllable_opex_year + reserves_year",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "noi_year",
        label: "Net operating income",
        formula: "egi_year + total_opex_year",
        unit: "USD",
        format: "currency",
        precision: 0,
        emphasis: "hero",
      },
      {
        key: "loan_balance_open",
        label: "Loan balance (opening)",
        formula: "if(year == 1, loan_amount, prev.loan_balance_close)",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "loan_balance_close",
        label: "Loan balance (closing)",
        formula:
          "if(loan_amount <= 0, 0, if(year <= io_period_years, loan_amount, balance(monthly_rate, amortising_months, loan_amount, (year - io_period_years) * 12)))",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "debt_service_year",
        label: "Less: debt service",
        formula:
          "if(loan_amount <= 0, 0, if(year <= io_period_years, -interest_only_debt_service, -amortising_debt_service))",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "dscr_year",
        label: "DSCR",
        formula: "if(loan_amount > 0, noi_year / -debt_service_year, null)",
        format: "ratio",
        precision: 2,
        emphasis: "strong",
      },
      {
        key: "debt_yield_year",
        label: "Debt yield",
        formula: "if(loan_amount > 0, noi_year / loan_balance_close, null)",
        format: "percent",
        precision: 2,
      },
      {
        key: "levered_cf_year",
        label: "Levered cash flow (operations)",
        formula: "noi_year + debt_service_year",
        unit: "USD",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "exit_gross_value",
        label: "Exit gross value",
        formula: "if(year < years, 0, noi_year / exit_cap_rate)",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "exit_selling_costs",
        label: "Less: selling costs",
        formula: "if(year < years, 0, -exit_gross_value * selling_costs_pct)",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "loan_repayment",
        label: "Less: loan repayment",
        formula: "if(year < years, 0, -loan_balance_close)",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "net_sale_proceeds",
        label: "Net sale proceeds",
        formula: "exit_gross_value + exit_selling_costs + loan_repayment",
        unit: "USD",
        format: "currency",
        precision: 0,
        emphasis: "strong",
      },
      {
        key: "unlevered_cf_year",
        label: "Unlevered cash flow",
        formula: "noi_year + if(year < years, 0, exit_gross_value + exit_selling_costs)",
        unit: "USD",
        format: "currency",
        precision: 0,
      },
      {
        key: "net_cash_flow_year",
        label: "Net cash flow to equity",
        formula: "levered_cf_year + net_sale_proceeds",
        unit: "USD",
        format: "currency",
        precision: 0,
        emphasis: "hero",
      },
    ],
  },

  returns: [
    {
      key: "exit_value",
      label: "Exit gross value",
      group: "Returns",
      formula: 'series_last("exit_gross_value")',
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
    {
      key: "exit_price_per_unit",
      label: "Exit price per unit",
      group: "Returns",
      formula: "exit_value / unit_count",
      unit: "USD/unit",
      format: "currency",
      precision: 0,
    },
    {
      key: "total_distributions",
      label: "Total cash to equity",
      group: "Returns",
      formula: 'series_sum("net_cash_flow_year")',
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "levered_irr",
      label: "Levered IRR",
      group: "Returns",
      formula: 'series_irr("net_cash_flow_year", -equity_required)',
      format: "percent",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "unlevered_irr",
      label: "Unlevered IRR",
      group: "Returns",
      formula: 'series_irr("unlevered_cf_year", -all_in_cost)',
      format: "percent",
      precision: 2,
    },
    {
      key: "equity_multiple",
      label: "Equity multiple",
      group: "Returns",
      formula: "total_distributions / equity_required",
      format: "multiple",
      precision: 2,
      emphasis: "hero",
    },
    {
      key: "avg_levered_cash_flow",
      label: "Average annual cash flow",
      group: "Returns",
      formula: 'series_avg("levered_cf_year")',
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "avg_cash_on_cash",
      label: "Average cash-on-cash",
      group: "Returns",
      formula: "avg_levered_cash_flow / equity_required",
      format: "percent",
      precision: 2,
      emphasis: "strong",
    },
    {
      key: "min_levered_cash_flow",
      label: "Worst-year cash flow",
      group: "Returns",
      formula: 'series_min("levered_cf_year")',
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "min_dscr",
      label: "Minimum DSCR",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_min("dscr_year"), null)',
      format: "ratio",
      precision: 2,
      emphasis: "strong",
    },
    {
      key: "peak_dscr",
      label: "Peak DSCR",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_max("dscr_year"), null)',
      format: "ratio",
      precision: 2,
    },
    {
      key: "years_below_covenant",
      label: "Years below DSCR covenant",
      group: "Returns",
      formula: 'if(loan_amount > 0, series_count_below("dscr_year", dscr_covenant), 0)',
      format: "integer",
    },
    {
      key: "exit_noi",
      label: "Exit-year NOI",
      group: "Returns",
      formula: 'series_last("noi_year")',
      unit: "USD",
      format: "currency",
      precision: 0,
    },
    {
      key: "noi_growth_total",
      label: "NOI growth over hold",
      group: "Returns",
      formula: '(exit_noi - series_first("noi_year")) / series_first("noi_year")',
      format: "percent",
      precision: 1,
    },
    {
      key: "npv_at_discount",
      label: "NPV at discount rate",
      group: "Returns",
      formula: 'series_npv("net_cash_flow_year", discount_rate, -equity_required)',
      unit: "USD",
      format: "currency",
      precision: 0,
      emphasis: "strong",
    },
  ],

  summary: [
    "price_per_unit",
    "purchase_price",
    "going_in_cap_rate",
    "net_yield",
    "noi",
    "cash_on_cash",
    "dscr",
    "debt_yield",
    "economic_vacancy",
  ],

  benchmarks: [
    {
      key: "dscr",
      label: "DSCR (year 1)",
      direction: "higher",
      good: 1.35,
      warn: 1.25,
      unit: "x",
      note: "Agency minimum is typically 1.25x on fixed-rate stabilised debt.",
    },
    {
      key: "dscr_amortising",
      label: "DSCR (fully amortising)",
      direction: "higher",
      good: 1.3,
      warn: 1.2,
      unit: "x",
      note: "The test that binds once interest-only burns off.",
    },
    {
      key: "min_dscr",
      label: "Minimum DSCR over hold",
      direction: "higher",
      good: 1.3,
      warn: 1.2,
      unit: "x",
    },
    {
      key: "debt_yield",
      label: "Debt yield",
      direction: "higher",
      good: 0.1,
      warn: 0.08,
      note: "Agency and CMBS lenders size to 8-10% minimum.",
    },
    {
      key: "going_in_cap_rate",
      label: "Going-in cap rate",
      direction: "higher",
      good: 0.055,
      warn: 0.045,
      note: "After reassessed property tax and replacement reserves.",
    },
    {
      key: "net_yield",
      label: "Net yield (all-in cost)",
      direction: "higher",
      good: 0.05,
      warn: 0.042,
    },
    {
      key: "gross_yield",
      label: "Gross yield",
      direction: "higher",
      good: 0.1,
      warn: 0.08,
    },
    {
      key: "cash_on_cash",
      label: "Cash-on-cash (year 1)",
      direction: "higher",
      good: 0.06,
      warn: 0.035,
    },
    {
      key: "avg_cash_on_cash",
      label: "Average cash-on-cash",
      direction: "higher",
      good: 0.06,
      warn: 0.035,
    },
    {
      key: "levered_irr",
      label: "Levered IRR",
      direction: "higher",
      good: 0.15,
      warn: 0.12,
    },
    {
      key: "equity_multiple",
      label: "Equity multiple",
      direction: "higher",
      good: 1.8,
      warn: 1.45,
      unit: "x",
    },
    {
      key: "opex_ratio",
      label: "OpEx ratio",
      direction: "lower",
      good: 0.42,
      warn: 0.52,
      note: "Stabilised US multifamily runs 38-50% of EGI including taxes, insurance and reserves.",
    },
  ],

  flags: [
    {
      id: "property_tax_reassessment",
      when: "reassess_on_sale and property_tax_step_up > property_tax_t12 * 0.15",
      severity: "red",
      title: "Property tax steps up sharply on transfer",
      detail:
        "The seller's T12 tax bill of {property_tax_t12} becomes {property_tax} on reassessment at the purchase basis — an increase of {property_tax_step_up} ({property_tax_step_up_pct}). At the going-in cap of {going_in_cap_rate} that step-up alone is worth several hundred basis points of value that the OM's cap rate does not reflect.",
      metric: "property_tax_step_up",
      dd: "Confirm the jurisdiction's reassessment practice and the parcel's current assessed value and millage with the assessor. Get a tax consultant's opinion on the likely post-sale assessment and on the prospects for an appeal.",
    },
    {
      id: "no_reassessment_assumed",
      when: "not reassess_on_sale",
      severity: "amber",
      title: "No reassessment on transfer assumed",
      detail:
        "The model is carrying the seller's T12 property tax of {property_tax_t12} rather than the reassessed {property_tax_reassessed}. If the jurisdiction does reassess, NOI falls by {property_tax_step_up} and the going-in cap of {going_in_cap_rate} is overstated.",
      metric: "property_tax_reassessed",
      dd: "Verify with the county assessor that transfer does not trigger reassessment, and check for any acquisition-related recapture or change-of-ownership rules.",
    },
    {
      id: "opex_diverges_from_t12",
      when: "abs(opex_variance_to_t12) > 20%",
      severity: "amber",
      title: "Modelled OpEx diverges from the T12",
      detail:
        "The build-up carries {total_opex} of operating expenses against a T12 actual of {t12_opex_total}, a variance of {opex_variance_to_t12} before reserves. NOI of {noi} and the {going_in_cap_rate} going-in cap move directly with it.",
      metric: "opex_variance_to_t12",
      dd: "Reconcile the per-unit build-up against the T12 line by line. Check for turn costs capitalised out of R&M, an affiliate management fee below market, and a property tax line that has not yet been reassessed.",
    },
    {
      id: "dscr_below_covenant",
      when: "loan_amount > 0 and dscr < dscr_covenant",
      severity: "red",
      title: "Year-one DSCR below the covenant",
      detail:
        "DSCR is {dscr} against a {dscr_covenant}× covenant, on NOI of {noi} and debt service of {annual_debt_service}. Debt yield is {debt_yield}.",
      metric: "dscr",
      dd: "Ask the lender which constraint binds — LTV, DSCR or debt yield — and re-size proceeds to the binding test before committing the equity.",
    },
    {
      id: "io_masking_coverage",
      when: "io_period_years >= 1 and dscr_amortising < dscr_covenant",
      severity: "red",
      title: "Interest-only is masking the real coverage",
      detail:
        "DSCR is {dscr} on the interest-only payment of {annual_debt_service}, but only {dscr_amortising} once amortisation begins at {stabilised_debt_service}. The deal does not cover its own debt on a fully amortising basis at today's NOI.",
      metric: "dscr_amortising",
      dd: "Confirm the NOI growth required to clear the covenant at the IO burn-off date, and whether it depends on the loss-to-lease capture actually happening.",
    },
    {
      id: "debt_yield_thin",
      when: "loan_amount > 0 and debt_yield < 8%",
      severity: "amber",
      title: "Debt yield below the agency floor",
      detail:
        "Debt yield is {debt_yield} on a loan of {loan_amount}. Agency and CMBS lenders size to 8-10%, so proceeds are likely to be cut regardless of what the DSCR shows at today's rate.",
      metric: "debt_yield",
      dd: "Re-run at the proceeds implied by an 8% debt yield and confirm the equity cheque and returns still work.",
    },
    {
      id: "loss_to_lease_aggressive",
      when: "loss_to_lease_pct > 10%",
      severity: "amber",
      title: "Loss to lease above 10%",
      detail:
        "In-place rent of {in_place_rent_pu} against a market rent of {market_rent_pu} implies loss to lease of {loss_to_lease_pct}, worth {loss_to_lease} a year. On a stabilised property that gap usually means the market rent assumption is optimistic rather than that the manager has been asleep.",
      metric: "loss_to_lease_pct",
      dd: "Pull the last 90 days of signed leases from the rent roll and compare against the assumed market rent. Trade-out on new leases is the only evidence that counts.",
    },
    {
      id: "in_place_above_market",
      when: "loss_to_lease_pct < -2%",
      severity: "red",
      title: "In-place rents are above market",
      detail:
        "In-place rent of {in_place_rent_pu} exceeds market rent of {market_rent_pu}. Income falls as leases roll, and the {rent_growth} rent growth assumption is being applied to a base that is already too high.",
      metric: "loss_to_lease_pct",
      dd: "Review the concession log and the lease trade-out report. Rents above market usually mean heavy concessions that are not visible in the headline rent roll.",
    },
    {
      id: "economic_vacancy_high",
      when: "economic_vacancy > 18%",
      severity: "amber",
      title: "Economic vacancy above 18%",
      detail:
        "Total leakage from gross potential rent is {economic_vacancy}, against a physical vacancy of {physical_vacancy}. Loss to lease of {loss_to_lease}, concessions of {concessions_loss} and bad debt of {bad_debt_loss} together are doing more damage than the empty units.",
      metric: "economic_vacancy",
      dd: "Reconcile the T12 collections to the rent roll month by month. Ask specifically for the concession log and the delinquency ageing.",
    },
    {
      id: "insurance_underwritten_low",
      when: "insurance_per_unit < 400",
      severity: "amber",
      title: "Insurance underwritten below market",
      detail:
        "Insurance is underwritten at {insurance_per_unit} per unit ({insurance_cost} total). US multifamily insurance has repriced hard since 2021, particularly in coastal, hail and wildfire markets, and inheriting the seller's premium is not a valid assumption.",
      metric: "insurance_cost",
      dd: "Obtain a bindable quote from your own broker on the current loss runs before closing, and check the deductible structure for named-storm and wind/hail perils.",
    },
    {
      id: "opex_below_range",
      when: "opex_per_unit < 4500",
      severity: "amber",
      title: "Operating expenses below the normal range",
      detail:
        "Total OpEx is {opex_per_unit} per unit per year ({opex_ratio} of EGI), below the $4,500-7,500 range typical for US multifamily including taxes, insurance and reserves.",
      metric: "opex_per_unit",
      dd: "Compare line by line against the T12 and against two comparable assets in the same submarket. Check whether turn costs have been capitalised out of R&M.",
    },
    {
      id: "reserves_light",
      when: "replacement_reserves_per_unit < 250",
      severity: "amber",
      title: "Replacement reserves below the agency minimum",
      detail:
        "Reserves are {replacement_reserves_per_unit} per unit per year on a property built in {year_built}, now {building_age_years} years old. Agency lenders require $250-350 and more on older vintage, so the lender will impose its own number regardless of the model.",
      metric: "replacement_reserves",
      dd: "Commission a property condition assessment and price the twelve-year capital plan. Reserve at the PCA's number, not at a round figure.",
    },
    {
      id: "old_vintage_capex",
      when: "building_age_years > 35",
      severity: "amber",
      title: "Vintage stock — deferred capital exposure",
      detail:
        "Built in {year_built}, the asset is {building_age_years} years old. Plumbing, electrical panels, roofs and cladding all fall due in this window, and reserves of {replacement_reserves} a year will not fund them.",
      metric: "replacement_reserves",
      dd: "Order a full PCA with a twelve-year capital plan, and sewer-scope and electrical panel inspections. Check for aluminium wiring, polybutylene and Federal Pacific panels, all of which affect insurability.",
    },
    {
      id: "negative_leverage",
      when: "negative_leverage",
      severity: "red",
      title: "Negative leverage",
      detail:
        "The going-in cap rate of {going_in_cap_rate} is below the interest rate of {interest_rate}. Levered IRR of {levered_irr} against unlevered {unlevered_irr} shows the debt is subtracting from the equity return until NOI grows through the coupon.",
      metric: "going_in_cap_rate",
      dd: "Establish how many years of NOI growth are needed to reach positive leverage and whether the business plan actually delivers it.",
    },
    {
      id: "exit_cap_compression",
      when: "exit_cap_rate < going_in_cap_rate",
      severity: "red",
      title: "Exit cap rate tighter than going-in",
      detail:
        "The exit cap of {exit_cap_rate} is below the going-in cap of {going_in_cap_rate} on an asset that will be {hold_period} years older at sale. Part of the {levered_irr} levered IRR is a market call, not an operating result.",
      metric: "exit_cap_rate",
      dd: "Re-run at going-in cap plus 50bps. If the deal fails that test, the return is a rate bet rather than a real estate one.",
    },
    {
      id: "negative_cash_flow_year",
      when: "min_levered_cash_flow < 0",
      severity: "red",
      title: "Negative levered cash flow in at least one year",
      detail:
        "The worst projected year produces {min_levered_cash_flow} after debt service, against average annual cash flow of {avg_levered_cash_flow}. Most likely the year interest-only burns off.",
      metric: "min_levered_cash_flow",
      dd: "Confirm the operating reserve sized at closing covers the shortfall, and check whether the loan documents permit a distribution stop in that year.",
    },
    {
      id: "dscr_breach_in_projection",
      when: "loan_amount > 0 and years_below_covenant > 0 and dscr >= dscr_covenant",
      severity: "amber",
      title: "DSCR falls below covenant later in the hold",
      detail:
        "The deal opens above covenant but breaches in {years_below_covenant} of the projected years, bottoming at {min_dscr}, as interest-only burns off and property tax grows at {tax_growth}.",
      metric: "min_dscr",
      dd: "Model the covenant test date by date against the loan documents, and confirm the cure rights and cash management trigger.",
    },
    {
      id: "concessions_heavy",
      when: "concessions_pct > 5%",
      severity: "amber",
      title: "Heavy concessions in the market",
      detail:
        "Concessions run at {concessions_pct} of gross potential rent ({concessions_loss}), which is roughly {concessions_pct} of a month's free rent per lease. Effective rent is materially below the headline rent the OM quotes.",
      metric: "concessions_loss",
      dd: "Get net effective rent, not headline rent, from the comps. Establish whether concessions are a lease-up artefact or a structural feature of the submarket's supply pipeline.",
    },
  ],

  methodology:
    "Income is built from gross potential rent (every revenue unit at market rent for twelve months) and worked down through loss to lease, physical vacancy, concessions, bad debt and non-revenue units, so economic vacancy is visible separately from the physical vacancy an OM quotes. Loss to lease burns off over the hold at the specified rate as leases roll, and in-place rent is never allowed to exceed market rent. Property tax is reassessed at the purchase basis where the jurisdiction reassesses on transfer — assessed value equals price times the assessment ratio, taxed at the parcel millage — and the step-up against the seller's T12 bill is shown explicitly, because inheriting the seller's tax line is the most common and most expensive error in US multifamily underwriting. Property tax then grows at its own assessed-value growth rate rather than at general OpEx inflation. Replacement reserves are deducted above NOI, which is the conservative convention and the one an agency lender applies. Debt amortises monthly with an optional interest-only period; DSCR is reported both on the actual year-one payment and on the fully amortising payment, because the amortising figure is what binds once interest-only burns off. Debt yield is reported because it is the rate-independent test agency and CMBS lenders actually size to. The exit capitalises the final-year NOI at the exit cap rate and deducts selling costs. What this model does NOT do: it does not model a unit-by-unit rent roll or unit mix, does not model a lease-up or a value-add renovation schedule beyond a day-one capital budget, does not model a refinance, a supplemental loan, an interest rate cap or a rate reset, does not model a promote or waterfall to the LP and GP, does not model depreciation, cost segregation, bonus depreciation or any US federal or state income tax, and does not model tax abatements, LIHTC or any rent-regulated regime. Where a rent roll is uploaded, unit count, rentable area and the in-place and market rent totals come from it and override the per-unit averages; where a T12 is uploaded, the property tax line is taken from it and the modelled OpEx is cross-checked against the T12 total excluding reserves. Returns are property-level to the equity as a whole.",
};
